// Code generated by ent, DO NOT EDIT.

package configitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/coder-lulu/newbee-io-rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v uint8) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldStatus, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldTenantID, v))
}

// DepartmentID applies equality check predicate on the "department_id" field. It's identical to DepartmentIDEQ.
func DepartmentID(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldDepartmentID, v))
}

// ConfigKey applies equality check predicate on the "config_key" field. It's identical to ConfigKeyEQ.
func ConfigKey(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldConfigKey, v))
}

// ConfigValue applies equality check predicate on the "config_value" field. It's identical to ConfigValueEQ.
func ConfigValue(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldConfigValue, v))
}

// ValueType applies equality check predicate on the "value_type" field. It's identical to ValueTypeEQ.
func ValueType(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldValueType, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldCategory, v))
}

// ServiceName applies equality check predicate on the "service_name" field. It's identical to ServiceNameEQ.
func ServiceName(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldServiceName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldDescription, v))
}

// DefaultValue applies equality check predicate on the "default_value" field. It's identical to DefaultValueEQ.
func DefaultValue(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldDefaultValue, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldVersion, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldUpdatedBy, v))
}

// IsReadonly applies equality check predicate on the "is_readonly" field. It's identical to IsReadonlyEQ.
func IsReadonly(v bool) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldIsReadonly, v))
}

// IsSensitive applies equality check predicate on the "is_sensitive" field. It's identical to IsSensitiveEQ.
func IsSensitive(v bool) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldIsSensitive, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldScope, v))
}

// ConfigGroup applies equality check predicate on the "config_group" field. It's identical to ConfigGroupEQ.
func ConfigGroup(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldConfigGroup, v))
}

// Tags applies equality check predicate on the "tags" field. It's identical to TagsEQ.
func Tags(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldTags, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v uint8) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v uint8) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...uint8) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...uint8) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v uint8) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v uint8) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v uint8) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v uint8) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotNull(FieldStatus))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldTenantID, v))
}

// DepartmentIDEQ applies the EQ predicate on the "department_id" field.
func DepartmentIDEQ(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldDepartmentID, v))
}

// DepartmentIDNEQ applies the NEQ predicate on the "department_id" field.
func DepartmentIDNEQ(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldDepartmentID, v))
}

// DepartmentIDIn applies the In predicate on the "department_id" field.
func DepartmentIDIn(vs ...uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldDepartmentID, vs...))
}

// DepartmentIDNotIn applies the NotIn predicate on the "department_id" field.
func DepartmentIDNotIn(vs ...uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldDepartmentID, vs...))
}

// DepartmentIDGT applies the GT predicate on the "department_id" field.
func DepartmentIDGT(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldDepartmentID, v))
}

// DepartmentIDGTE applies the GTE predicate on the "department_id" field.
func DepartmentIDGTE(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldDepartmentID, v))
}

// DepartmentIDLT applies the LT predicate on the "department_id" field.
func DepartmentIDLT(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldDepartmentID, v))
}

// DepartmentIDLTE applies the LTE predicate on the "department_id" field.
func DepartmentIDLTE(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldDepartmentID, v))
}

// DepartmentIDIsNil applies the IsNil predicate on the "department_id" field.
func DepartmentIDIsNil() predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIsNull(FieldDepartmentID))
}

// DepartmentIDNotNil applies the NotNil predicate on the "department_id" field.
func DepartmentIDNotNil() predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotNull(FieldDepartmentID))
}

// ConfigKeyEQ applies the EQ predicate on the "config_key" field.
func ConfigKeyEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldConfigKey, v))
}

// ConfigKeyNEQ applies the NEQ predicate on the "config_key" field.
func ConfigKeyNEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldConfigKey, v))
}

// ConfigKeyIn applies the In predicate on the "config_key" field.
func ConfigKeyIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldConfigKey, vs...))
}

// ConfigKeyNotIn applies the NotIn predicate on the "config_key" field.
func ConfigKeyNotIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldConfigKey, vs...))
}

// ConfigKeyGT applies the GT predicate on the "config_key" field.
func ConfigKeyGT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldConfigKey, v))
}

// ConfigKeyGTE applies the GTE predicate on the "config_key" field.
func ConfigKeyGTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldConfigKey, v))
}

// ConfigKeyLT applies the LT predicate on the "config_key" field.
func ConfigKeyLT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldConfigKey, v))
}

// ConfigKeyLTE applies the LTE predicate on the "config_key" field.
func ConfigKeyLTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldConfigKey, v))
}

// ConfigKeyContains applies the Contains predicate on the "config_key" field.
func ConfigKeyContains(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContains(FieldConfigKey, v))
}

// ConfigKeyHasPrefix applies the HasPrefix predicate on the "config_key" field.
func ConfigKeyHasPrefix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasPrefix(FieldConfigKey, v))
}

// ConfigKeyHasSuffix applies the HasSuffix predicate on the "config_key" field.
func ConfigKeyHasSuffix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasSuffix(FieldConfigKey, v))
}

// ConfigKeyEqualFold applies the EqualFold predicate on the "config_key" field.
func ConfigKeyEqualFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEqualFold(FieldConfigKey, v))
}

// ConfigKeyContainsFold applies the ContainsFold predicate on the "config_key" field.
func ConfigKeyContainsFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContainsFold(FieldConfigKey, v))
}

// ConfigValueEQ applies the EQ predicate on the "config_value" field.
func ConfigValueEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldConfigValue, v))
}

// ConfigValueNEQ applies the NEQ predicate on the "config_value" field.
func ConfigValueNEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldConfigValue, v))
}

// ConfigValueIn applies the In predicate on the "config_value" field.
func ConfigValueIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldConfigValue, vs...))
}

// ConfigValueNotIn applies the NotIn predicate on the "config_value" field.
func ConfigValueNotIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldConfigValue, vs...))
}

// ConfigValueGT applies the GT predicate on the "config_value" field.
func ConfigValueGT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldConfigValue, v))
}

// ConfigValueGTE applies the GTE predicate on the "config_value" field.
func ConfigValueGTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldConfigValue, v))
}

// ConfigValueLT applies the LT predicate on the "config_value" field.
func ConfigValueLT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldConfigValue, v))
}

// ConfigValueLTE applies the LTE predicate on the "config_value" field.
func ConfigValueLTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldConfigValue, v))
}

// ConfigValueContains applies the Contains predicate on the "config_value" field.
func ConfigValueContains(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContains(FieldConfigValue, v))
}

// ConfigValueHasPrefix applies the HasPrefix predicate on the "config_value" field.
func ConfigValueHasPrefix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasPrefix(FieldConfigValue, v))
}

// ConfigValueHasSuffix applies the HasSuffix predicate on the "config_value" field.
func ConfigValueHasSuffix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasSuffix(FieldConfigValue, v))
}

// ConfigValueEqualFold applies the EqualFold predicate on the "config_value" field.
func ConfigValueEqualFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEqualFold(FieldConfigValue, v))
}

// ConfigValueContainsFold applies the ContainsFold predicate on the "config_value" field.
func ConfigValueContainsFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContainsFold(FieldConfigValue, v))
}

// ValueTypeEQ applies the EQ predicate on the "value_type" field.
func ValueTypeEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldValueType, v))
}

// ValueTypeNEQ applies the NEQ predicate on the "value_type" field.
func ValueTypeNEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldValueType, v))
}

// ValueTypeIn applies the In predicate on the "value_type" field.
func ValueTypeIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldValueType, vs...))
}

// ValueTypeNotIn applies the NotIn predicate on the "value_type" field.
func ValueTypeNotIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldValueType, vs...))
}

// ValueTypeGT applies the GT predicate on the "value_type" field.
func ValueTypeGT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldValueType, v))
}

// ValueTypeGTE applies the GTE predicate on the "value_type" field.
func ValueTypeGTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldValueType, v))
}

// ValueTypeLT applies the LT predicate on the "value_type" field.
func ValueTypeLT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldValueType, v))
}

// ValueTypeLTE applies the LTE predicate on the "value_type" field.
func ValueTypeLTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldValueType, v))
}

// ValueTypeContains applies the Contains predicate on the "value_type" field.
func ValueTypeContains(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContains(FieldValueType, v))
}

// ValueTypeHasPrefix applies the HasPrefix predicate on the "value_type" field.
func ValueTypeHasPrefix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasPrefix(FieldValueType, v))
}

// ValueTypeHasSuffix applies the HasSuffix predicate on the "value_type" field.
func ValueTypeHasSuffix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasSuffix(FieldValueType, v))
}

// ValueTypeEqualFold applies the EqualFold predicate on the "value_type" field.
func ValueTypeEqualFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEqualFold(FieldValueType, v))
}

// ValueTypeContainsFold applies the ContainsFold predicate on the "value_type" field.
func ValueTypeContainsFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContainsFold(FieldValueType, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContainsFold(FieldCategory, v))
}

// ServiceNameEQ applies the EQ predicate on the "service_name" field.
func ServiceNameEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldServiceName, v))
}

// ServiceNameNEQ applies the NEQ predicate on the "service_name" field.
func ServiceNameNEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldServiceName, v))
}

// ServiceNameIn applies the In predicate on the "service_name" field.
func ServiceNameIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldServiceName, vs...))
}

// ServiceNameNotIn applies the NotIn predicate on the "service_name" field.
func ServiceNameNotIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldServiceName, vs...))
}

// ServiceNameGT applies the GT predicate on the "service_name" field.
func ServiceNameGT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldServiceName, v))
}

// ServiceNameGTE applies the GTE predicate on the "service_name" field.
func ServiceNameGTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldServiceName, v))
}

// ServiceNameLT applies the LT predicate on the "service_name" field.
func ServiceNameLT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldServiceName, v))
}

// ServiceNameLTE applies the LTE predicate on the "service_name" field.
func ServiceNameLTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldServiceName, v))
}

// ServiceNameContains applies the Contains predicate on the "service_name" field.
func ServiceNameContains(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContains(FieldServiceName, v))
}

// ServiceNameHasPrefix applies the HasPrefix predicate on the "service_name" field.
func ServiceNameHasPrefix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasPrefix(FieldServiceName, v))
}

// ServiceNameHasSuffix applies the HasSuffix predicate on the "service_name" field.
func ServiceNameHasSuffix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasSuffix(FieldServiceName, v))
}

// ServiceNameIsNil applies the IsNil predicate on the "service_name" field.
func ServiceNameIsNil() predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIsNull(FieldServiceName))
}

// ServiceNameNotNil applies the NotNil predicate on the "service_name" field.
func ServiceNameNotNil() predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotNull(FieldServiceName))
}

// ServiceNameEqualFold applies the EqualFold predicate on the "service_name" field.
func ServiceNameEqualFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEqualFold(FieldServiceName, v))
}

// ServiceNameContainsFold applies the ContainsFold predicate on the "service_name" field.
func ServiceNameContainsFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContainsFold(FieldServiceName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContainsFold(FieldDescription, v))
}

// DefaultValueEQ applies the EQ predicate on the "default_value" field.
func DefaultValueEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldDefaultValue, v))
}

// DefaultValueNEQ applies the NEQ predicate on the "default_value" field.
func DefaultValueNEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldDefaultValue, v))
}

// DefaultValueIn applies the In predicate on the "default_value" field.
func DefaultValueIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldDefaultValue, vs...))
}

// DefaultValueNotIn applies the NotIn predicate on the "default_value" field.
func DefaultValueNotIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldDefaultValue, vs...))
}

// DefaultValueGT applies the GT predicate on the "default_value" field.
func DefaultValueGT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldDefaultValue, v))
}

// DefaultValueGTE applies the GTE predicate on the "default_value" field.
func DefaultValueGTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldDefaultValue, v))
}

// DefaultValueLT applies the LT predicate on the "default_value" field.
func DefaultValueLT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldDefaultValue, v))
}

// DefaultValueLTE applies the LTE predicate on the "default_value" field.
func DefaultValueLTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldDefaultValue, v))
}

// DefaultValueContains applies the Contains predicate on the "default_value" field.
func DefaultValueContains(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContains(FieldDefaultValue, v))
}

// DefaultValueHasPrefix applies the HasPrefix predicate on the "default_value" field.
func DefaultValueHasPrefix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasPrefix(FieldDefaultValue, v))
}

// DefaultValueHasSuffix applies the HasSuffix predicate on the "default_value" field.
func DefaultValueHasSuffix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasSuffix(FieldDefaultValue, v))
}

// DefaultValueIsNil applies the IsNil predicate on the "default_value" field.
func DefaultValueIsNil() predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIsNull(FieldDefaultValue))
}

// DefaultValueNotNil applies the NotNil predicate on the "default_value" field.
func DefaultValueNotNil() predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotNull(FieldDefaultValue))
}

// DefaultValueEqualFold applies the EqualFold predicate on the "default_value" field.
func DefaultValueEqualFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEqualFold(FieldDefaultValue, v))
}

// DefaultValueContainsFold applies the ContainsFold predicate on the "default_value" field.
func DefaultValueContainsFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContainsFold(FieldDefaultValue, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldVersion, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint64) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotNull(FieldUpdatedBy))
}

// IsReadonlyEQ applies the EQ predicate on the "is_readonly" field.
func IsReadonlyEQ(v bool) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldIsReadonly, v))
}

// IsReadonlyNEQ applies the NEQ predicate on the "is_readonly" field.
func IsReadonlyNEQ(v bool) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldIsReadonly, v))
}

// IsSensitiveEQ applies the EQ predicate on the "is_sensitive" field.
func IsSensitiveEQ(v bool) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldIsSensitive, v))
}

// IsSensitiveNEQ applies the NEQ predicate on the "is_sensitive" field.
func IsSensitiveNEQ(v bool) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldIsSensitive, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContainsFold(FieldScope, v))
}

// ConfigGroupEQ applies the EQ predicate on the "config_group" field.
func ConfigGroupEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldConfigGroup, v))
}

// ConfigGroupNEQ applies the NEQ predicate on the "config_group" field.
func ConfigGroupNEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldConfigGroup, v))
}

// ConfigGroupIn applies the In predicate on the "config_group" field.
func ConfigGroupIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldConfigGroup, vs...))
}

// ConfigGroupNotIn applies the NotIn predicate on the "config_group" field.
func ConfigGroupNotIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldConfigGroup, vs...))
}

// ConfigGroupGT applies the GT predicate on the "config_group" field.
func ConfigGroupGT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldConfigGroup, v))
}

// ConfigGroupGTE applies the GTE predicate on the "config_group" field.
func ConfigGroupGTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldConfigGroup, v))
}

// ConfigGroupLT applies the LT predicate on the "config_group" field.
func ConfigGroupLT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldConfigGroup, v))
}

// ConfigGroupLTE applies the LTE predicate on the "config_group" field.
func ConfigGroupLTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldConfigGroup, v))
}

// ConfigGroupContains applies the Contains predicate on the "config_group" field.
func ConfigGroupContains(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContains(FieldConfigGroup, v))
}

// ConfigGroupHasPrefix applies the HasPrefix predicate on the "config_group" field.
func ConfigGroupHasPrefix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasPrefix(FieldConfigGroup, v))
}

// ConfigGroupHasSuffix applies the HasSuffix predicate on the "config_group" field.
func ConfigGroupHasSuffix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasSuffix(FieldConfigGroup, v))
}

// ConfigGroupIsNil applies the IsNil predicate on the "config_group" field.
func ConfigGroupIsNil() predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIsNull(FieldConfigGroup))
}

// ConfigGroupNotNil applies the NotNil predicate on the "config_group" field.
func ConfigGroupNotNil() predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotNull(FieldConfigGroup))
}

// ConfigGroupEqualFold applies the EqualFold predicate on the "config_group" field.
func ConfigGroupEqualFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEqualFold(FieldConfigGroup, v))
}

// ConfigGroupContainsFold applies the ContainsFold predicate on the "config_group" field.
func ConfigGroupContainsFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContainsFold(FieldConfigGroup, v))
}

// TagsEQ applies the EQ predicate on the "tags" field.
func TagsEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEQ(FieldTags, v))
}

// TagsNEQ applies the NEQ predicate on the "tags" field.
func TagsNEQ(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNEQ(FieldTags, v))
}

// TagsIn applies the In predicate on the "tags" field.
func TagsIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIn(FieldTags, vs...))
}

// TagsNotIn applies the NotIn predicate on the "tags" field.
func TagsNotIn(vs ...string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotIn(FieldTags, vs...))
}

// TagsGT applies the GT predicate on the "tags" field.
func TagsGT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGT(FieldTags, v))
}

// TagsGTE applies the GTE predicate on the "tags" field.
func TagsGTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldGTE(FieldTags, v))
}

// TagsLT applies the LT predicate on the "tags" field.
func TagsLT(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLT(FieldTags, v))
}

// TagsLTE applies the LTE predicate on the "tags" field.
func TagsLTE(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldLTE(FieldTags, v))
}

// TagsContains applies the Contains predicate on the "tags" field.
func TagsContains(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContains(FieldTags, v))
}

// TagsHasPrefix applies the HasPrefix predicate on the "tags" field.
func TagsHasPrefix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasPrefix(FieldTags, v))
}

// TagsHasSuffix applies the HasSuffix predicate on the "tags" field.
func TagsHasSuffix(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldHasSuffix(FieldTags, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldNotNull(FieldTags))
}

// TagsEqualFold applies the EqualFold predicate on the "tags" field.
func TagsEqualFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldEqualFold(FieldTags, v))
}

// TagsContainsFold applies the ContainsFold predicate on the "tags" field.
func TagsContainsFold(v string) predicate.ConfigItem {
	return predicate.ConfigItem(sql.FieldContainsFold(FieldTags, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ConfigItem) predicate.ConfigItem {
	return predicate.ConfigItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ConfigItem) predicate.ConfigItem {
	return predicate.ConfigItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ConfigItem) predicate.ConfigItem {
	return predicate.ConfigItem(sql.NotPredicates(p))
}
