// Code generated by ent, DO NOT EDIT.

package outputtask

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the outputtask type in the database.
	Label = "output_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTaskName holds the string denoting the task_name field in the database.
	FieldTaskName = "task_name"
	// FieldTaskType holds the string denoting the task_type field in the database.
	FieldTaskType = "task_type"
	// FieldOutputTarget holds the string denoting the output_target field in the database.
	FieldOutputTarget = "output_target"
	// FieldTargetConfig holds the string denoting the target_config field in the database.
	FieldTargetConfig = "target_config"
	// FieldTaskStatus holds the string denoting the task_status field in the database.
	FieldTaskStatus = "task_status"
	// FieldDataTargetID holds the string denoting the data_target_id field in the database.
	FieldDataTargetID = "data_target_id"
	// FieldScheduledAt holds the string denoting the scheduled_at field in the database.
	FieldScheduledAt = "scheduled_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldTotalRecords holds the string denoting the total_records field in the database.
	FieldTotalRecords = "total_records"
	// FieldProcessedRecords holds the string denoting the processed_records field in the database.
	FieldProcessedRecords = "processed_records"
	// FieldSuccessRecords holds the string denoting the success_records field in the database.
	FieldSuccessRecords = "success_records"
	// FieldFailedRecords holds the string denoting the failed_records field in the database.
	FieldFailedRecords = "failed_records"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// Table holds the table name of the outputtask in the database.
	Table = "io_output_tasks"
)

// Columns holds all SQL columns for outputtask fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTenantID,
	FieldStatus,
	FieldTaskName,
	FieldTaskType,
	FieldOutputTarget,
	FieldTargetConfig,
	FieldTaskStatus,
	FieldDataTargetID,
	FieldScheduledAt,
	FieldStartedAt,
	FieldCompletedAt,
	FieldTotalRecords,
	FieldProcessedRecords,
	FieldSuccessRecords,
	FieldFailedRecords,
	FieldErrorMessage,
	FieldMetadata,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus uint8
	// TaskNameValidator is a validator for the "task_name" field. It is called by the builders before save.
	TaskNameValidator func(string) error
	// DefaultTaskType holds the default value on creation for the "task_type" field.
	DefaultTaskType string
	// TaskTypeValidator is a validator for the "task_type" field. It is called by the builders before save.
	TaskTypeValidator func(string) error
	// OutputTargetValidator is a validator for the "output_target" field. It is called by the builders before save.
	OutputTargetValidator func(string) error
	// DefaultTaskStatus holds the default value on creation for the "task_status" field.
	DefaultTaskStatus string
	// TaskStatusValidator is a validator for the "task_status" field. It is called by the builders before save.
	TaskStatusValidator func(string) error
	// DefaultTotalRecords holds the default value on creation for the "total_records" field.
	DefaultTotalRecords int64
	// DefaultProcessedRecords holds the default value on creation for the "processed_records" field.
	DefaultProcessedRecords int64
	// DefaultSuccessRecords holds the default value on creation for the "success_records" field.
	DefaultSuccessRecords int64
	// DefaultFailedRecords holds the default value on creation for the "failed_records" field.
	DefaultFailedRecords int64
)

// OrderOption defines the ordering options for the OutputTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTaskName orders the results by the task_name field.
func ByTaskName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskName, opts...).ToFunc()
}

// ByTaskType orders the results by the task_type field.
func ByTaskType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskType, opts...).ToFunc()
}

// ByOutputTarget orders the results by the output_target field.
func ByOutputTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTarget, opts...).ToFunc()
}

// ByTargetConfig orders the results by the target_config field.
func ByTargetConfig(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetConfig, opts...).ToFunc()
}

// ByTaskStatus orders the results by the task_status field.
func ByTaskStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskStatus, opts...).ToFunc()
}

// ByDataTargetID orders the results by the data_target_id field.
func ByDataTargetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataTargetID, opts...).ToFunc()
}

// ByScheduledAt orders the results by the scheduled_at field.
func ByScheduledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScheduledAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByTotalRecords orders the results by the total_records field.
func ByTotalRecords(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalRecords, opts...).ToFunc()
}

// ByProcessedRecords orders the results by the processed_records field.
func ByProcessedRecords(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessedRecords, opts...).ToFunc()
}

// BySuccessRecords orders the results by the success_records field.
func BySuccessRecords(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessRecords, opts...).ToFunc()
}

// ByFailedRecords orders the results by the failed_records field.
func ByFailedRecords(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailedRecords, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByMetadata orders the results by the metadata field.
func ByMetadata(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadata, opts...).ToFunc()
}
