// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-io-rpc/ent/cichangehistory"
)

// CiChangeHistoryCreate is the builder for creating a CiChangeHistory entity.
type CiChangeHistoryCreate struct {
	config
	mutation *CiChangeHistoryMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *CiChangeHistoryCreate) SetCreatedAt(v time.Time) *CiChangeHistoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableCreatedAt(v *time.Time) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CiChangeHistoryCreate) SetUpdatedAt(v time.Time) *CiChangeHistoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableUpdatedAt(v *time.Time) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *CiChangeHistoryCreate) SetTenantID(v uint64) *CiChangeHistoryCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableTenantID(v *uint64) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetDepartmentID sets the "department_id" field.
func (_c *CiChangeHistoryCreate) SetDepartmentID(v uint64) *CiChangeHistoryCreate {
	_c.mutation.SetDepartmentID(v)
	return _c
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableDepartmentID(v *uint64) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetDepartmentID(*v)
	}
	return _c
}

// SetOperationID sets the "operation_id" field.
func (_c *CiChangeHistoryCreate) SetOperationID(v string) *CiChangeHistoryCreate {
	_c.mutation.SetOperationID(v)
	return _c
}

// SetCiID sets the "ci_id" field.
func (_c *CiChangeHistoryCreate) SetCiID(v uint64) *CiChangeHistoryCreate {
	_c.mutation.SetCiID(v)
	return _c
}

// SetNillableCiID sets the "ci_id" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableCiID(v *uint64) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetCiID(*v)
	}
	return _c
}

// SetCiTypeID sets the "ci_type_id" field.
func (_c *CiChangeHistoryCreate) SetCiTypeID(v uint64) *CiChangeHistoryCreate {
	_c.mutation.SetCiTypeID(v)
	return _c
}

// SetNillableCiTypeID sets the "ci_type_id" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableCiTypeID(v *uint64) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetCiTypeID(*v)
	}
	return _c
}

// SetCiType sets the "ci_type" field.
func (_c *CiChangeHistoryCreate) SetCiType(v string) *CiChangeHistoryCreate {
	_c.mutation.SetCiType(v)
	return _c
}

// SetNillableCiType sets the "ci_type" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableCiType(v *string) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetCiType(*v)
	}
	return _c
}

// SetOperationType sets the "operation_type" field.
func (_c *CiChangeHistoryCreate) SetOperationType(v string) *CiChangeHistoryCreate {
	_c.mutation.SetOperationType(v)
	return _c
}

// SetOperationName sets the "operation_name" field.
func (_c *CiChangeHistoryCreate) SetOperationName(v string) *CiChangeHistoryCreate {
	_c.mutation.SetOperationName(v)
	return _c
}

// SetNillableOperationName sets the "operation_name" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableOperationName(v *string) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetOperationName(*v)
	}
	return _c
}

// SetOperatorID sets the "operator_id" field.
func (_c *CiChangeHistoryCreate) SetOperatorID(v uint64) *CiChangeHistoryCreate {
	_c.mutation.SetOperatorID(v)
	return _c
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableOperatorID(v *uint64) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetOperatorID(*v)
	}
	return _c
}

// SetOperatorName sets the "operator_name" field.
func (_c *CiChangeHistoryCreate) SetOperatorName(v string) *CiChangeHistoryCreate {
	_c.mutation.SetOperatorName(v)
	return _c
}

// SetNillableOperatorName sets the "operator_name" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableOperatorName(v *string) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetOperatorName(*v)
	}
	return _c
}

// SetChangedFields sets the "changed_fields" field.
func (_c *CiChangeHistoryCreate) SetChangedFields(v string) *CiChangeHistoryCreate {
	_c.mutation.SetChangedFields(v)
	return _c
}

// SetNillableChangedFields sets the "changed_fields" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableChangedFields(v *string) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetChangedFields(*v)
	}
	return _c
}

// SetOldValues sets the "old_values" field.
func (_c *CiChangeHistoryCreate) SetOldValues(v string) *CiChangeHistoryCreate {
	_c.mutation.SetOldValues(v)
	return _c
}

// SetNillableOldValues sets the "old_values" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableOldValues(v *string) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetOldValues(*v)
	}
	return _c
}

// SetNewValues sets the "new_values" field.
func (_c *CiChangeHistoryCreate) SetNewValues(v string) *CiChangeHistoryCreate {
	_c.mutation.SetNewValues(v)
	return _c
}

// SetNillableNewValues sets the "new_values" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableNewValues(v *string) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetNewValues(*v)
	}
	return _c
}

// SetChangeReason sets the "change_reason" field.
func (_c *CiChangeHistoryCreate) SetChangeReason(v string) *CiChangeHistoryCreate {
	_c.mutation.SetChangeReason(v)
	return _c
}

// SetNillableChangeReason sets the "change_reason" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableChangeReason(v *string) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetChangeReason(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *CiChangeHistoryCreate) SetSource(v string) *CiChangeHistoryCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableSource(v *string) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetSourceDetail sets the "source_detail" field.
func (_c *CiChangeHistoryCreate) SetSourceDetail(v string) *CiChangeHistoryCreate {
	_c.mutation.SetSourceDetail(v)
	return _c
}

// SetNillableSourceDetail sets the "source_detail" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableSourceDetail(v *string) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetSourceDetail(*v)
	}
	return _c
}

// SetSourceTaskID sets the "source_task_id" field.
func (_c *CiChangeHistoryCreate) SetSourceTaskID(v string) *CiChangeHistoryCreate {
	_c.mutation.SetSourceTaskID(v)
	return _c
}

// SetNillableSourceTaskID sets the "source_task_id" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableSourceTaskID(v *string) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetSourceTaskID(*v)
	}
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *CiChangeHistoryCreate) SetIPAddress(v string) *CiChangeHistoryCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableIPAddress(v *string) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetIPAddress(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *CiChangeHistoryCreate) SetUserAgent(v string) *CiChangeHistoryCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableUserAgent(v *string) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetNeedsApproval sets the "needs_approval" field.
func (_c *CiChangeHistoryCreate) SetNeedsApproval(v bool) *CiChangeHistoryCreate {
	_c.mutation.SetNeedsApproval(v)
	return _c
}

// SetNillableNeedsApproval sets the "needs_approval" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableNeedsApproval(v *bool) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetNeedsApproval(*v)
	}
	return _c
}

// SetIsApproved sets the "is_approved" field.
func (_c *CiChangeHistoryCreate) SetIsApproved(v bool) *CiChangeHistoryCreate {
	_c.mutation.SetIsApproved(v)
	return _c
}

// SetNillableIsApproved sets the "is_approved" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableIsApproved(v *bool) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetIsApproved(*v)
	}
	return _c
}

// SetApprovedBy sets the "approved_by" field.
func (_c *CiChangeHistoryCreate) SetApprovedBy(v uint64) *CiChangeHistoryCreate {
	_c.mutation.SetApprovedBy(v)
	return _c
}

// SetNillableApprovedBy sets the "approved_by" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableApprovedBy(v *uint64) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetApprovedBy(*v)
	}
	return _c
}

// SetApprovedByName sets the "approved_by_name" field.
func (_c *CiChangeHistoryCreate) SetApprovedByName(v string) *CiChangeHistoryCreate {
	_c.mutation.SetApprovedByName(v)
	return _c
}

// SetNillableApprovedByName sets the "approved_by_name" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableApprovedByName(v *string) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetApprovedByName(*v)
	}
	return _c
}

// SetApprovedAt sets the "approved_at" field.
func (_c *CiChangeHistoryCreate) SetApprovedAt(v time.Time) *CiChangeHistoryCreate {
	_c.mutation.SetApprovedAt(v)
	return _c
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableApprovedAt(v *time.Time) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetApprovedAt(*v)
	}
	return _c
}

// SetApprovalComment sets the "approval_comment" field.
func (_c *CiChangeHistoryCreate) SetApprovalComment(v string) *CiChangeHistoryCreate {
	_c.mutation.SetApprovalComment(v)
	return _c
}

// SetNillableApprovalComment sets the "approval_comment" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableApprovalComment(v *string) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetApprovalComment(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CiChangeHistoryCreate) SetStatus(v string) *CiChangeHistoryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableStatus(v *string) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *CiChangeHistoryCreate) SetErrorMessage(v string) *CiChangeHistoryCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableErrorMessage(v *string) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetIsRollback sets the "is_rollback" field.
func (_c *CiChangeHistoryCreate) SetIsRollback(v bool) *CiChangeHistoryCreate {
	_c.mutation.SetIsRollback(v)
	return _c
}

// SetNillableIsRollback sets the "is_rollback" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableIsRollback(v *bool) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetIsRollback(*v)
	}
	return _c
}

// SetRollbackFromID sets the "rollback_from_id" field.
func (_c *CiChangeHistoryCreate) SetRollbackFromID(v uint64) *CiChangeHistoryCreate {
	_c.mutation.SetRollbackFromID(v)
	return _c
}

// SetNillableRollbackFromID sets the "rollback_from_id" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableRollbackFromID(v *uint64) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetRollbackFromID(*v)
	}
	return _c
}

// SetCanRollback sets the "can_rollback" field.
func (_c *CiChangeHistoryCreate) SetCanRollback(v bool) *CiChangeHistoryCreate {
	_c.mutation.SetCanRollback(v)
	return _c
}

// SetNillableCanRollback sets the "can_rollback" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableCanRollback(v *bool) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetCanRollback(*v)
	}
	return _c
}

// SetAffectedCount sets the "affected_count" field.
func (_c *CiChangeHistoryCreate) SetAffectedCount(v int) *CiChangeHistoryCreate {
	_c.mutation.SetAffectedCount(v)
	return _c
}

// SetNillableAffectedCount sets the "affected_count" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableAffectedCount(v *int) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetAffectedCount(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *CiChangeHistoryCreate) SetDurationMs(v int) *CiChangeHistoryCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableDurationMs(v *int) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *CiChangeHistoryCreate) SetMetadata(v string) *CiChangeHistoryCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_c *CiChangeHistoryCreate) SetNillableMetadata(v *string) *CiChangeHistoryCreate {
	if v != nil {
		_c.SetMetadata(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CiChangeHistoryCreate) SetID(v uint64) *CiChangeHistoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CiChangeHistoryMutation object of the builder.
func (_c *CiChangeHistoryCreate) Mutation() *CiChangeHistoryMutation {
	return _c.mutation
}

// Save creates the CiChangeHistory in the database.
func (_c *CiChangeHistoryCreate) Save(ctx context.Context) (*CiChangeHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CiChangeHistoryCreate) SaveX(ctx context.Context) *CiChangeHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CiChangeHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CiChangeHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CiChangeHistoryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cichangehistory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cichangehistory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := cichangehistory.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.NeedsApproval(); !ok {
		v := cichangehistory.DefaultNeedsApproval
		_c.mutation.SetNeedsApproval(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := cichangehistory.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.IsRollback(); !ok {
		v := cichangehistory.DefaultIsRollback
		_c.mutation.SetIsRollback(v)
	}
	if _, ok := _c.mutation.CanRollback(); !ok {
		v := cichangehistory.DefaultCanRollback
		_c.mutation.SetCanRollback(v)
	}
	if _, ok := _c.mutation.AffectedCount(); !ok {
		v := cichangehistory.DefaultAffectedCount
		_c.mutation.SetAffectedCount(v)
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := cichangehistory.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CiChangeHistoryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CiChangeHistory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CiChangeHistory.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "CiChangeHistory.tenant_id"`)}
	}
	if _, ok := _c.mutation.OperationID(); !ok {
		return &ValidationError{Name: "operation_id", err: errors.New(`ent: missing required field "CiChangeHistory.operation_id"`)}
	}
	if v, ok := _c.mutation.OperationID(); ok {
		if err := cichangehistory.OperationIDValidator(v); err != nil {
			return &ValidationError{Name: "operation_id", err: fmt.Errorf(`ent: validator failed for field "CiChangeHistory.operation_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CiType(); ok {
		if err := cichangehistory.CiTypeValidator(v); err != nil {
			return &ValidationError{Name: "ci_type", err: fmt.Errorf(`ent: validator failed for field "CiChangeHistory.ci_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OperationType(); !ok {
		return &ValidationError{Name: "operation_type", err: errors.New(`ent: missing required field "CiChangeHistory.operation_type"`)}
	}
	if v, ok := _c.mutation.OperationType(); ok {
		if err := cichangehistory.OperationTypeValidator(v); err != nil {
			return &ValidationError{Name: "operation_type", err: fmt.Errorf(`ent: validator failed for field "CiChangeHistory.operation_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.OperationName(); ok {
		if err := cichangehistory.OperationNameValidator(v); err != nil {
			return &ValidationError{Name: "operation_name", err: fmt.Errorf(`ent: validator failed for field "CiChangeHistory.operation_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.OperatorName(); ok {
		if err := cichangehistory.OperatorNameValidator(v); err != nil {
			return &ValidationError{Name: "operator_name", err: fmt.Errorf(`ent: validator failed for field "CiChangeHistory.operator_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ChangeReason(); ok {
		if err := cichangehistory.ChangeReasonValidator(v); err != nil {
			return &ValidationError{Name: "change_reason", err: fmt.Errorf(`ent: validator failed for field "CiChangeHistory.change_reason": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := cichangehistory.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "CiChangeHistory.source": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SourceDetail(); ok {
		if err := cichangehistory.SourceDetailValidator(v); err != nil {
			return &ValidationError{Name: "source_detail", err: fmt.Errorf(`ent: validator failed for field "CiChangeHistory.source_detail": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SourceTaskID(); ok {
		if err := cichangehistory.SourceTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "source_task_id", err: fmt.Errorf(`ent: validator failed for field "CiChangeHistory.source_task_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IPAddress(); ok {
		if err := cichangehistory.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "CiChangeHistory.ip_address": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := cichangehistory.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "CiChangeHistory.user_agent": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NeedsApproval(); !ok {
		return &ValidationError{Name: "needs_approval", err: errors.New(`ent: missing required field "CiChangeHistory.needs_approval"`)}
	}
	if v, ok := _c.mutation.ApprovedByName(); ok {
		if err := cichangehistory.ApprovedByNameValidator(v); err != nil {
			return &ValidationError{Name: "approved_by_name", err: fmt.Errorf(`ent: validator failed for field "CiChangeHistory.approved_by_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ApprovalComment(); ok {
		if err := cichangehistory.ApprovalCommentValidator(v); err != nil {
			return &ValidationError{Name: "approval_comment", err: fmt.Errorf(`ent: validator failed for field "CiChangeHistory.approval_comment": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CiChangeHistory.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := cichangehistory.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CiChangeHistory.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ErrorMessage(); ok {
		if err := cichangehistory.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "CiChangeHistory.error_message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsRollback(); !ok {
		return &ValidationError{Name: "is_rollback", err: errors.New(`ent: missing required field "CiChangeHistory.is_rollback"`)}
	}
	if _, ok := _c.mutation.CanRollback(); !ok {
		return &ValidationError{Name: "can_rollback", err: errors.New(`ent: missing required field "CiChangeHistory.can_rollback"`)}
	}
	if _, ok := _c.mutation.AffectedCount(); !ok {
		return &ValidationError{Name: "affected_count", err: errors.New(`ent: missing required field "CiChangeHistory.affected_count"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "CiChangeHistory.duration_ms"`)}
	}
	return nil
}

func (_c *CiChangeHistoryCreate) sqlSave(ctx context.Context) (*CiChangeHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CiChangeHistoryCreate) createSpec() (*CiChangeHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &CiChangeHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cichangehistory.Table, sqlgraph.NewFieldSpec(cichangehistory.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cichangehistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cichangehistory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(cichangehistory.FieldTenantID, field.TypeUint64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.DepartmentID(); ok {
		_spec.SetField(cichangehistory.FieldDepartmentID, field.TypeUint64, value)
		_node.DepartmentID = value
	}
	if value, ok := _c.mutation.OperationID(); ok {
		_spec.SetField(cichangehistory.FieldOperationID, field.TypeString, value)
		_node.OperationID = value
	}
	if value, ok := _c.mutation.CiID(); ok {
		_spec.SetField(cichangehistory.FieldCiID, field.TypeUint64, value)
		_node.CiID = value
	}
	if value, ok := _c.mutation.CiTypeID(); ok {
		_spec.SetField(cichangehistory.FieldCiTypeID, field.TypeUint64, value)
		_node.CiTypeID = value
	}
	if value, ok := _c.mutation.CiType(); ok {
		_spec.SetField(cichangehistory.FieldCiType, field.TypeString, value)
		_node.CiType = value
	}
	if value, ok := _c.mutation.OperationType(); ok {
		_spec.SetField(cichangehistory.FieldOperationType, field.TypeString, value)
		_node.OperationType = value
	}
	if value, ok := _c.mutation.OperationName(); ok {
		_spec.SetField(cichangehistory.FieldOperationName, field.TypeString, value)
		_node.OperationName = value
	}
	if value, ok := _c.mutation.OperatorID(); ok {
		_spec.SetField(cichangehistory.FieldOperatorID, field.TypeUint64, value)
		_node.OperatorID = value
	}
	if value, ok := _c.mutation.OperatorName(); ok {
		_spec.SetField(cichangehistory.FieldOperatorName, field.TypeString, value)
		_node.OperatorName = value
	}
	if value, ok := _c.mutation.ChangedFields(); ok {
		_spec.SetField(cichangehistory.FieldChangedFields, field.TypeString, value)
		_node.ChangedFields = value
	}
	if value, ok := _c.mutation.OldValues(); ok {
		_spec.SetField(cichangehistory.FieldOldValues, field.TypeString, value)
		_node.OldValues = value
	}
	if value, ok := _c.mutation.NewValues(); ok {
		_spec.SetField(cichangehistory.FieldNewValues, field.TypeString, value)
		_node.NewValues = value
	}
	if value, ok := _c.mutation.ChangeReason(); ok {
		_spec.SetField(cichangehistory.FieldChangeReason, field.TypeString, value)
		_node.ChangeReason = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(cichangehistory.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.SourceDetail(); ok {
		_spec.SetField(cichangehistory.FieldSourceDetail, field.TypeString, value)
		_node.SourceDetail = value
	}
	if value, ok := _c.mutation.SourceTaskID(); ok {
		_spec.SetField(cichangehistory.FieldSourceTaskID, field.TypeString, value)
		_node.SourceTaskID = value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(cichangehistory.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(cichangehistory.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.NeedsApproval(); ok {
		_spec.SetField(cichangehistory.FieldNeedsApproval, field.TypeBool, value)
		_node.NeedsApproval = value
	}
	if value, ok := _c.mutation.IsApproved(); ok {
		_spec.SetField(cichangehistory.FieldIsApproved, field.TypeBool, value)
		_node.IsApproved = value
	}
	if value, ok := _c.mutation.ApprovedBy(); ok {
		_spec.SetField(cichangehistory.FieldApprovedBy, field.TypeUint64, value)
		_node.ApprovedBy = value
	}
	if value, ok := _c.mutation.ApprovedByName(); ok {
		_spec.SetField(cichangehistory.FieldApprovedByName, field.TypeString, value)
		_node.ApprovedByName = value
	}
	if value, ok := _c.mutation.ApprovedAt(); ok {
		_spec.SetField(cichangehistory.FieldApprovedAt, field.TypeTime, value)
		_node.ApprovedAt = value
	}
	if value, ok := _c.mutation.ApprovalComment(); ok {
		_spec.SetField(cichangehistory.FieldApprovalComment, field.TypeString, value)
		_node.ApprovalComment = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(cichangehistory.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(cichangehistory.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.IsRollback(); ok {
		_spec.SetField(cichangehistory.FieldIsRollback, field.TypeBool, value)
		_node.IsRollback = value
	}
	if value, ok := _c.mutation.RollbackFromID(); ok {
		_spec.SetField(cichangehistory.FieldRollbackFromID, field.TypeUint64, value)
		_node.RollbackFromID = value
	}
	if value, ok := _c.mutation.CanRollback(); ok {
		_spec.SetField(cichangehistory.FieldCanRollback, field.TypeBool, value)
		_node.CanRollback = value
	}
	if value, ok := _c.mutation.AffectedCount(); ok {
		_spec.SetField(cichangehistory.FieldAffectedCount, field.TypeInt, value)
		_node.AffectedCount = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(cichangehistory.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(cichangehistory.FieldMetadata, field.TypeString, value)
		_node.Metadata = value
	}
	return _node, _spec
}

// CiChangeHistoryCreateBulk is the builder for creating many CiChangeHistory entities in bulk.
type CiChangeHistoryCreateBulk struct {
	config
	err      error
	builders []*CiChangeHistoryCreate
}

// Save creates the CiChangeHistory entities in the database.
func (_c *CiChangeHistoryCreateBulk) Save(ctx context.Context) ([]*CiChangeHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CiChangeHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CiChangeHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CiChangeHistoryCreateBulk) SaveX(ctx context.Context) []*CiChangeHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CiChangeHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CiChangeHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
