// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/coder-lulu/newbee-io-rpc/ent/cilifecyclestate"
)

// CiLifecycleState is the model entity for the CiLifecycleState schema.
type CiLifecycleState struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// Create Time | 创建日期
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Update Time | 修改日期
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Tenant ID | 租户 ID
	TenantID uint64 `json:"tenant_id,omitempty"`
	// Department ID | 部门 ID
	DepartmentID uint64 `json:"department_id,omitempty"`
	// 状态ID
	StateID string `json:"state_id,omitempty"`
	// CI实例ID
	CiID uint64 `json:"ci_id,omitempty"`
	// CI类型ID
	CiTypeID uint64 `json:"ci_type_id,omitempty"`
	// 状态名称
	StateName string `json:"state_name,omitempty"`
	// 状态类型: draft/submitted/validated/approved/executed/completed/cancelled/expired
	StateType string `json:"state_type,omitempty"`
	// 上一个状态
	PreviousState string `json:"previous_state,omitempty"`
	// 进入该状态的时间
	EnteredAt time.Time `json:"entered_at,omitempty"`
	// 退出该状态的时间
	ExitedAt time.Time `json:"exited_at,omitempty"`
	// 预期退出时间（用于超时检测）
	ExpectedExitAt time.Time `json:"expected_exit_at,omitempty"`
	// 在该状态停留的秒数
	DurationSeconds int `json:"duration_seconds,omitempty"`
	// 触发类型: manual/auto/scheduled/event
	TriggerType string `json:"trigger_type,omitempty"`
	// 触发人用户ID
	TriggeredBy uint64 `json:"triggered_by,omitempty"`
	// 触发人用户名
	TriggeredByName string `json:"triggered_by_name,omitempty"`
	// 状态相关数据JSON
	StateData string `json:"state_data,omitempty"`
	// 元数据JSON
	Metadata string `json:"metadata,omitempty"`
	// 是否超时
	IsTimeout bool `json:"is_timeout,omitempty"`
	// 是否有错误
	HasError bool `json:"has_error,omitempty"`
	// 错误信息
	ErrorMessage string `json:"error_message,omitempty"`
	// 错误代码
	ErrorCode string `json:"error_code,omitempty"`
	// 关联的操作ID
	OperationID string `json:"operation_id,omitempty"`
	// 关联的变更记录ID
	ChangeRecordID string `json:"change_record_id,omitempty"`
	// 是否为当前状态
	IsCurrent bool `json:"is_current,omitempty"`
	// 是否为最终状态
	IsFinal bool `json:"is_final,omitempty"`
	// 是否可以重试
	CanRetry bool `json:"can_retry,omitempty"`
	// 重试次数
	RetryCount int `json:"retry_count,omitempty"`
	// 最大重试次数
	MaxRetryCount int `json:"max_retry_count,omitempty"`
	// 最后重试时间
	LastRetryAt time.Time `json:"last_retry_at,omitempty"`
	// 备注说明
	Comment      string `json:"comment,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CiLifecycleState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cilifecyclestate.FieldIsTimeout, cilifecyclestate.FieldHasError, cilifecyclestate.FieldIsCurrent, cilifecyclestate.FieldIsFinal, cilifecyclestate.FieldCanRetry:
			values[i] = new(sql.NullBool)
		case cilifecyclestate.FieldID, cilifecyclestate.FieldTenantID, cilifecyclestate.FieldDepartmentID, cilifecyclestate.FieldCiID, cilifecyclestate.FieldCiTypeID, cilifecyclestate.FieldDurationSeconds, cilifecyclestate.FieldTriggeredBy, cilifecyclestate.FieldRetryCount, cilifecyclestate.FieldMaxRetryCount:
			values[i] = new(sql.NullInt64)
		case cilifecyclestate.FieldStateID, cilifecyclestate.FieldStateName, cilifecyclestate.FieldStateType, cilifecyclestate.FieldPreviousState, cilifecyclestate.FieldTriggerType, cilifecyclestate.FieldTriggeredByName, cilifecyclestate.FieldStateData, cilifecyclestate.FieldMetadata, cilifecyclestate.FieldErrorMessage, cilifecyclestate.FieldErrorCode, cilifecyclestate.FieldOperationID, cilifecyclestate.FieldChangeRecordID, cilifecyclestate.FieldComment:
			values[i] = new(sql.NullString)
		case cilifecyclestate.FieldCreatedAt, cilifecyclestate.FieldUpdatedAt, cilifecyclestate.FieldEnteredAt, cilifecyclestate.FieldExitedAt, cilifecyclestate.FieldExpectedExitAt, cilifecyclestate.FieldLastRetryAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CiLifecycleState fields.
func (_m *CiLifecycleState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cilifecyclestate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case cilifecyclestate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case cilifecyclestate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case cilifecyclestate.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = uint64(value.Int64)
			}
		case cilifecyclestate.FieldDepartmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field department_id", values[i])
			} else if value.Valid {
				_m.DepartmentID = uint64(value.Int64)
			}
		case cilifecyclestate.FieldStateID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state_id", values[i])
			} else if value.Valid {
				_m.StateID = value.String
			}
		case cilifecyclestate.FieldCiID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ci_id", values[i])
			} else if value.Valid {
				_m.CiID = uint64(value.Int64)
			}
		case cilifecyclestate.FieldCiTypeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ci_type_id", values[i])
			} else if value.Valid {
				_m.CiTypeID = uint64(value.Int64)
			}
		case cilifecyclestate.FieldStateName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state_name", values[i])
			} else if value.Valid {
				_m.StateName = value.String
			}
		case cilifecyclestate.FieldStateType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state_type", values[i])
			} else if value.Valid {
				_m.StateType = value.String
			}
		case cilifecyclestate.FieldPreviousState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field previous_state", values[i])
			} else if value.Valid {
				_m.PreviousState = value.String
			}
		case cilifecyclestate.FieldEnteredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field entered_at", values[i])
			} else if value.Valid {
				_m.EnteredAt = value.Time
			}
		case cilifecyclestate.FieldExitedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field exited_at", values[i])
			} else if value.Valid {
				_m.ExitedAt = value.Time
			}
		case cilifecyclestate.FieldExpectedExitAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expected_exit_at", values[i])
			} else if value.Valid {
				_m.ExpectedExitAt = value.Time
			}
		case cilifecyclestate.FieldDurationSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_seconds", values[i])
			} else if value.Valid {
				_m.DurationSeconds = int(value.Int64)
			}
		case cilifecyclestate.FieldTriggerType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_type", values[i])
			} else if value.Valid {
				_m.TriggerType = value.String
			}
		case cilifecyclestate.FieldTriggeredBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field triggered_by", values[i])
			} else if value.Valid {
				_m.TriggeredBy = uint64(value.Int64)
			}
		case cilifecyclestate.FieldTriggeredByName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field triggered_by_name", values[i])
			} else if value.Valid {
				_m.TriggeredByName = value.String
			}
		case cilifecyclestate.FieldStateData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state_data", values[i])
			} else if value.Valid {
				_m.StateData = value.String
			}
		case cilifecyclestate.FieldMetadata:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value.Valid {
				_m.Metadata = value.String
			}
		case cilifecyclestate.FieldIsTimeout:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_timeout", values[i])
			} else if value.Valid {
				_m.IsTimeout = value.Bool
			}
		case cilifecyclestate.FieldHasError:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field has_error", values[i])
			} else if value.Valid {
				_m.HasError = value.Bool
			}
		case cilifecyclestate.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case cilifecyclestate.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = value.String
			}
		case cilifecyclestate.FieldOperationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation_id", values[i])
			} else if value.Valid {
				_m.OperationID = value.String
			}
		case cilifecyclestate.FieldChangeRecordID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field change_record_id", values[i])
			} else if value.Valid {
				_m.ChangeRecordID = value.String
			}
		case cilifecyclestate.FieldIsCurrent:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_current", values[i])
			} else if value.Valid {
				_m.IsCurrent = value.Bool
			}
		case cilifecyclestate.FieldIsFinal:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_final", values[i])
			} else if value.Valid {
				_m.IsFinal = value.Bool
			}
		case cilifecyclestate.FieldCanRetry:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field can_retry", values[i])
			} else if value.Valid {
				_m.CanRetry = value.Bool
			}
		case cilifecyclestate.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				_m.RetryCount = int(value.Int64)
			}
		case cilifecyclestate.FieldMaxRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_retry_count", values[i])
			} else if value.Valid {
				_m.MaxRetryCount = int(value.Int64)
			}
		case cilifecyclestate.FieldLastRetryAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_retry_at", values[i])
			} else if value.Valid {
				_m.LastRetryAt = value.Time
			}
		case cilifecyclestate.FieldComment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field comment", values[i])
			} else if value.Valid {
				_m.Comment = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CiLifecycleState.
// This includes values selected through modifiers, order, etc.
func (_m *CiLifecycleState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CiLifecycleState.
// Note that you need to call CiLifecycleState.Unwrap() before calling this method if this CiLifecycleState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CiLifecycleState) Update() *CiLifecycleStateUpdateOne {
	return NewCiLifecycleStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CiLifecycleState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CiLifecycleState) Unwrap() *CiLifecycleState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CiLifecycleState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CiLifecycleState) String() string {
	var builder strings.Builder
	builder.WriteString("CiLifecycleState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("department_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DepartmentID))
	builder.WriteString(", ")
	builder.WriteString("state_id=")
	builder.WriteString(_m.StateID)
	builder.WriteString(", ")
	builder.WriteString("ci_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CiID))
	builder.WriteString(", ")
	builder.WriteString("ci_type_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CiTypeID))
	builder.WriteString(", ")
	builder.WriteString("state_name=")
	builder.WriteString(_m.StateName)
	builder.WriteString(", ")
	builder.WriteString("state_type=")
	builder.WriteString(_m.StateType)
	builder.WriteString(", ")
	builder.WriteString("previous_state=")
	builder.WriteString(_m.PreviousState)
	builder.WriteString(", ")
	builder.WriteString("entered_at=")
	builder.WriteString(_m.EnteredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("exited_at=")
	builder.WriteString(_m.ExitedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expected_exit_at=")
	builder.WriteString(_m.ExpectedExitAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("duration_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationSeconds))
	builder.WriteString(", ")
	builder.WriteString("trigger_type=")
	builder.WriteString(_m.TriggerType)
	builder.WriteString(", ")
	builder.WriteString("triggered_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.TriggeredBy))
	builder.WriteString(", ")
	builder.WriteString("triggered_by_name=")
	builder.WriteString(_m.TriggeredByName)
	builder.WriteString(", ")
	builder.WriteString("state_data=")
	builder.WriteString(_m.StateData)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(_m.Metadata)
	builder.WriteString(", ")
	builder.WriteString("is_timeout=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsTimeout))
	builder.WriteString(", ")
	builder.WriteString("has_error=")
	builder.WriteString(fmt.Sprintf("%v", _m.HasError))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("error_code=")
	builder.WriteString(_m.ErrorCode)
	builder.WriteString(", ")
	builder.WriteString("operation_id=")
	builder.WriteString(_m.OperationID)
	builder.WriteString(", ")
	builder.WriteString("change_record_id=")
	builder.WriteString(_m.ChangeRecordID)
	builder.WriteString(", ")
	builder.WriteString("is_current=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsCurrent))
	builder.WriteString(", ")
	builder.WriteString("is_final=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsFinal))
	builder.WriteString(", ")
	builder.WriteString("can_retry=")
	builder.WriteString(fmt.Sprintf("%v", _m.CanRetry))
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryCount))
	builder.WriteString(", ")
	builder.WriteString("max_retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxRetryCount))
	builder.WriteString(", ")
	builder.WriteString("last_retry_at=")
	builder.WriteString(_m.LastRetryAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("comment=")
	builder.WriteString(_m.Comment)
	builder.WriteByte(')')
	return builder.String()
}

// CiLifecycleStates is a parsable slice of CiLifecycleState.
type CiLifecycleStates []*CiLifecycleState
