// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/coder-lulu/newbee-io-rpc/ent/configauditlog"
)

// ConfigAuditLog is the model entity for the ConfigAuditLog schema.
type ConfigAuditLog struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// Create Time | 创建日期
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Update Time | 修改日期
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Tenant ID | 租户 ID
	TenantID uint64 `json:"tenant_id,omitempty"`
	// Department ID | 部门 ID
	DepartmentID uint64 `json:"department_id,omitempty"`
	// 配置键
	ConfigKey string `json:"config_key,omitempty"`
	// 旧值
	OldValue string `json:"old_value,omitempty"`
	// 新值
	NewValue string `json:"new_value,omitempty"`
	// 变更类型: create/update/delete
	ChangeType string `json:"change_type,omitempty"`
	// 变更人用户ID
	ChangedBy uint64 `json:"changed_by,omitempty"`
	// 变更人用户名
	ChangedByName string `json:"changed_by_name,omitempty"`
	// 所属服务名称
	ServiceName string `json:"service_name,omitempty"`
	// 配置分类
	Category string `json:"category,omitempty"`
	// 配置组
	ConfigGroup string `json:"config_group,omitempty"`
	// 变更原因
	ChangeReason string `json:"change_reason,omitempty"`
	// 操作IP地址
	IPAddress string `json:"ip_address,omitempty"`
	// 用户代理
	UserAgent string `json:"user_agent,omitempty"`
	// 旧版本号
	OldVersion int `json:"old_version,omitempty"`
	// 新版本号
	NewVersion int `json:"new_version,omitempty"`
	// 是否为回滚操作
	IsRollback bool `json:"is_rollback,omitempty"`
	// 回滚来源日志ID
	RollbackFromLogID string `json:"rollback_from_log_id,omitempty"`
	selectValues      sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ConfigAuditLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case configauditlog.FieldIsRollback:
			values[i] = new(sql.NullBool)
		case configauditlog.FieldID, configauditlog.FieldTenantID, configauditlog.FieldDepartmentID, configauditlog.FieldChangedBy, configauditlog.FieldOldVersion, configauditlog.FieldNewVersion:
			values[i] = new(sql.NullInt64)
		case configauditlog.FieldConfigKey, configauditlog.FieldOldValue, configauditlog.FieldNewValue, configauditlog.FieldChangeType, configauditlog.FieldChangedByName, configauditlog.FieldServiceName, configauditlog.FieldCategory, configauditlog.FieldConfigGroup, configauditlog.FieldChangeReason, configauditlog.FieldIPAddress, configauditlog.FieldUserAgent, configauditlog.FieldRollbackFromLogID:
			values[i] = new(sql.NullString)
		case configauditlog.FieldCreatedAt, configauditlog.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ConfigAuditLog fields.
func (_m *ConfigAuditLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case configauditlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case configauditlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case configauditlog.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case configauditlog.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = uint64(value.Int64)
			}
		case configauditlog.FieldDepartmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field department_id", values[i])
			} else if value.Valid {
				_m.DepartmentID = uint64(value.Int64)
			}
		case configauditlog.FieldConfigKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config_key", values[i])
			} else if value.Valid {
				_m.ConfigKey = value.String
			}
		case configauditlog.FieldOldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field old_value", values[i])
			} else if value.Valid {
				_m.OldValue = value.String
			}
		case configauditlog.FieldNewValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field new_value", values[i])
			} else if value.Valid {
				_m.NewValue = value.String
			}
		case configauditlog.FieldChangeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field change_type", values[i])
			} else if value.Valid {
				_m.ChangeType = value.String
			}
		case configauditlog.FieldChangedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field changed_by", values[i])
			} else if value.Valid {
				_m.ChangedBy = uint64(value.Int64)
			}
		case configauditlog.FieldChangedByName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field changed_by_name", values[i])
			} else if value.Valid {
				_m.ChangedByName = value.String
			}
		case configauditlog.FieldServiceName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service_name", values[i])
			} else if value.Valid {
				_m.ServiceName = value.String
			}
		case configauditlog.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case configauditlog.FieldConfigGroup:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config_group", values[i])
			} else if value.Valid {
				_m.ConfigGroup = value.String
			}
		case configauditlog.FieldChangeReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field change_reason", values[i])
			} else if value.Valid {
				_m.ChangeReason = value.String
			}
		case configauditlog.FieldIPAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_address", values[i])
			} else if value.Valid {
				_m.IPAddress = value.String
			}
		case configauditlog.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case configauditlog.FieldOldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field old_version", values[i])
			} else if value.Valid {
				_m.OldVersion = int(value.Int64)
			}
		case configauditlog.FieldNewVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field new_version", values[i])
			} else if value.Valid {
				_m.NewVersion = int(value.Int64)
			}
		case configauditlog.FieldIsRollback:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_rollback", values[i])
			} else if value.Valid {
				_m.IsRollback = value.Bool
			}
		case configauditlog.FieldRollbackFromLogID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rollback_from_log_id", values[i])
			} else if value.Valid {
				_m.RollbackFromLogID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ConfigAuditLog.
// This includes values selected through modifiers, order, etc.
func (_m *ConfigAuditLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ConfigAuditLog.
// Note that you need to call ConfigAuditLog.Unwrap() before calling this method if this ConfigAuditLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ConfigAuditLog) Update() *ConfigAuditLogUpdateOne {
	return NewConfigAuditLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ConfigAuditLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ConfigAuditLog) Unwrap() *ConfigAuditLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ConfigAuditLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ConfigAuditLog) String() string {
	var builder strings.Builder
	builder.WriteString("ConfigAuditLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("department_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DepartmentID))
	builder.WriteString(", ")
	builder.WriteString("config_key=")
	builder.WriteString(_m.ConfigKey)
	builder.WriteString(", ")
	builder.WriteString("old_value=")
	builder.WriteString(_m.OldValue)
	builder.WriteString(", ")
	builder.WriteString("new_value=")
	builder.WriteString(_m.NewValue)
	builder.WriteString(", ")
	builder.WriteString("change_type=")
	builder.WriteString(_m.ChangeType)
	builder.WriteString(", ")
	builder.WriteString("changed_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChangedBy))
	builder.WriteString(", ")
	builder.WriteString("changed_by_name=")
	builder.WriteString(_m.ChangedByName)
	builder.WriteString(", ")
	builder.WriteString("service_name=")
	builder.WriteString(_m.ServiceName)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("config_group=")
	builder.WriteString(_m.ConfigGroup)
	builder.WriteString(", ")
	builder.WriteString("change_reason=")
	builder.WriteString(_m.ChangeReason)
	builder.WriteString(", ")
	builder.WriteString("ip_address=")
	builder.WriteString(_m.IPAddress)
	builder.WriteString(", ")
	builder.WriteString("user_agent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("old_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.OldVersion))
	builder.WriteString(", ")
	builder.WriteString("new_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.NewVersion))
	builder.WriteString(", ")
	builder.WriteString("is_rollback=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsRollback))
	builder.WriteString(", ")
	builder.WriteString("rollback_from_log_id=")
	builder.WriteString(_m.RollbackFromLogID)
	builder.WriteByte(')')
	return builder.String()
}

// ConfigAuditLogs is a parsable slice of ConfigAuditLog.
type ConfigAuditLogs []*ConfigAuditLog
