// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-io-rpc/ent/configauditlog"
	"github.com/coder-lulu/newbee-io-rpc/ent/predicate"
)

// ConfigAuditLogUpdate is the builder for updating ConfigAuditLog entities.
type ConfigAuditLogUpdate struct {
	config
	hooks     []Hook
	mutation  *ConfigAuditLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ConfigAuditLogUpdate builder.
func (_u *ConfigAuditLogUpdate) Where(ps ...predicate.ConfigAuditLog) *ConfigAuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConfigAuditLogUpdate) SetUpdatedAt(v time.Time) *ConfigAuditLogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *ConfigAuditLogUpdate) SetDepartmentID(v uint64) *ConfigAuditLogUpdate {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *ConfigAuditLogUpdate) SetNillableDepartmentID(v *uint64) *ConfigAuditLogUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *ConfigAuditLogUpdate) AddDepartmentID(v int64) *ConfigAuditLogUpdate {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *ConfigAuditLogUpdate) ClearDepartmentID() *ConfigAuditLogUpdate {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetConfigKey sets the "config_key" field.
func (_u *ConfigAuditLogUpdate) SetConfigKey(v string) *ConfigAuditLogUpdate {
	_u.mutation.SetConfigKey(v)
	return _u
}

// SetNillableConfigKey sets the "config_key" field if the given value is not nil.
func (_u *ConfigAuditLogUpdate) SetNillableConfigKey(v *string) *ConfigAuditLogUpdate {
	if v != nil {
		_u.SetConfigKey(*v)
	}
	return _u
}

// SetOldValue sets the "old_value" field.
func (_u *ConfigAuditLogUpdate) SetOldValue(v string) *ConfigAuditLogUpdate {
	_u.mutation.SetOldValue(v)
	return _u
}

// SetNillableOldValue sets the "old_value" field if the given value is not nil.
func (_u *ConfigAuditLogUpdate) SetNillableOldValue(v *string) *ConfigAuditLogUpdate {
	if v != nil {
		_u.SetOldValue(*v)
	}
	return _u
}

// ClearOldValue clears the value of the "old_value" field.
func (_u *ConfigAuditLogUpdate) ClearOldValue() *ConfigAuditLogUpdate {
	_u.mutation.ClearOldValue()
	return _u
}

// SetNewValue sets the "new_value" field.
func (_u *ConfigAuditLogUpdate) SetNewValue(v string) *ConfigAuditLogUpdate {
	_u.mutation.SetNewValue(v)
	return _u
}

// SetNillableNewValue sets the "new_value" field if the given value is not nil.
func (_u *ConfigAuditLogUpdate) SetNillableNewValue(v *string) *ConfigAuditLogUpdate {
	if v != nil {
		_u.SetNewValue(*v)
	}
	return _u
}

// ClearNewValue clears the value of the "new_value" field.
func (_u *ConfigAuditLogUpdate) ClearNewValue() *ConfigAuditLogUpdate {
	_u.mutation.ClearNewValue()
	return _u
}

// SetChangeType sets the "change_type" field.
func (_u *ConfigAuditLogUpdate) SetChangeType(v string) *ConfigAuditLogUpdate {
	_u.mutation.SetChangeType(v)
	return _u
}

// SetNillableChangeType sets the "change_type" field if the given value is not nil.
func (_u *ConfigAuditLogUpdate) SetNillableChangeType(v *string) *ConfigAuditLogUpdate {
	if v != nil {
		_u.SetChangeType(*v)
	}
	return _u
}

// SetChangedBy sets the "changed_by" field.
func (_u *ConfigAuditLogUpdate) SetChangedBy(v uint64) *ConfigAuditLogUpdate {
	_u.mutation.ResetChangedBy()
	_u.mutation.SetChangedBy(v)
	return _u
}

// SetNillableChangedBy sets the "changed_by" field if the given value is not nil.
func (_u *ConfigAuditLogUpdate) SetNillableChangedBy(v *uint64) *ConfigAuditLogUpdate {
	if v != nil {
		_u.SetChangedBy(*v)
	}
	return _u
}

// AddChangedBy adds value to the "changed_by" field.
func (_u *ConfigAuditLogUpdate) AddChangedBy(v int64) *ConfigAuditLogUpdate {
	_u.mutation.AddChangedBy(v)
	return _u
}

// ClearChangedBy clears the value of the "changed_by" field.
func (_u *ConfigAuditLogUpdate) ClearChangedBy() *ConfigAuditLogUpdate {
	_u.mutation.ClearChangedBy()
	return _u
}

// SetChangedByName sets the "changed_by_name" field.
func (_u *ConfigAuditLogUpdate) SetChangedByName(v string) *ConfigAuditLogUpdate {
	_u.mutation.SetChangedByName(v)
	return _u
}

// SetNillableChangedByName sets the "changed_by_name" field if the given value is not nil.
func (_u *ConfigAuditLogUpdate) SetNillableChangedByName(v *string) *ConfigAuditLogUpdate {
	if v != nil {
		_u.SetChangedByName(*v)
	}
	return _u
}

// ClearChangedByName clears the value of the "changed_by_name" field.
func (_u *ConfigAuditLogUpdate) ClearChangedByName() *ConfigAuditLogUpdate {
	_u.mutation.ClearChangedByName()
	return _u
}

// SetServiceName sets the "service_name" field.
func (_u *ConfigAuditLogUpdate) SetServiceName(v string) *ConfigAuditLogUpdate {
	_u.mutation.SetServiceName(v)
	return _u
}

// SetNillableServiceName sets the "service_name" field if the given value is not nil.
func (_u *ConfigAuditLogUpdate) SetNillableServiceName(v *string) *ConfigAuditLogUpdate {
	if v != nil {
		_u.SetServiceName(*v)
	}
	return _u
}

// ClearServiceName clears the value of the "service_name" field.
func (_u *ConfigAuditLogUpdate) ClearServiceName() *ConfigAuditLogUpdate {
	_u.mutation.ClearServiceName()
	return _u
}

// SetCategory sets the "category" field.
func (_u *ConfigAuditLogUpdate) SetCategory(v string) *ConfigAuditLogUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ConfigAuditLogUpdate) SetNillableCategory(v *string) *ConfigAuditLogUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *ConfigAuditLogUpdate) ClearCategory() *ConfigAuditLogUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// SetConfigGroup sets the "config_group" field.
func (_u *ConfigAuditLogUpdate) SetConfigGroup(v string) *ConfigAuditLogUpdate {
	_u.mutation.SetConfigGroup(v)
	return _u
}

// SetNillableConfigGroup sets the "config_group" field if the given value is not nil.
func (_u *ConfigAuditLogUpdate) SetNillableConfigGroup(v *string) *ConfigAuditLogUpdate {
	if v != nil {
		_u.SetConfigGroup(*v)
	}
	return _u
}

// ClearConfigGroup clears the value of the "config_group" field.
func (_u *ConfigAuditLogUpdate) ClearConfigGroup() *ConfigAuditLogUpdate {
	_u.mutation.ClearConfigGroup()
	return _u
}

// SetChangeReason sets the "change_reason" field.
func (_u *ConfigAuditLogUpdate) SetChangeReason(v string) *ConfigAuditLogUpdate {
	_u.mutation.SetChangeReason(v)
	return _u
}

// SetNillableChangeReason sets the "change_reason" field if the given value is not nil.
func (_u *ConfigAuditLogUpdate) SetNillableChangeReason(v *string) *ConfigAuditLogUpdate {
	if v != nil {
		_u.SetChangeReason(*v)
	}
	return _u
}

// ClearChangeReason clears the value of the "change_reason" field.
func (_u *ConfigAuditLogUpdate) ClearChangeReason() *ConfigAuditLogUpdate {
	_u.mutation.ClearChangeReason()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *ConfigAuditLogUpdate) SetIPAddress(v string) *ConfigAuditLogUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *ConfigAuditLogUpdate) SetNillableIPAddress(v *string) *ConfigAuditLogUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *ConfigAuditLogUpdate) ClearIPAddress() *ConfigAuditLogUpdate {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *ConfigAuditLogUpdate) SetUserAgent(v string) *ConfigAuditLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *ConfigAuditLogUpdate) SetNillableUserAgent(v *string) *ConfigAuditLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *ConfigAuditLogUpdate) ClearUserAgent() *ConfigAuditLogUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetOldVersion sets the "old_version" field.
func (_u *ConfigAuditLogUpdate) SetOldVersion(v int) *ConfigAuditLogUpdate {
	_u.mutation.ResetOldVersion()
	_u.mutation.SetOldVersion(v)
	return _u
}

// SetNillableOldVersion sets the "old_version" field if the given value is not nil.
func (_u *ConfigAuditLogUpdate) SetNillableOldVersion(v *int) *ConfigAuditLogUpdate {
	if v != nil {
		_u.SetOldVersion(*v)
	}
	return _u
}

// AddOldVersion adds value to the "old_version" field.
func (_u *ConfigAuditLogUpdate) AddOldVersion(v int) *ConfigAuditLogUpdate {
	_u.mutation.AddOldVersion(v)
	return _u
}

// ClearOldVersion clears the value of the "old_version" field.
func (_u *ConfigAuditLogUpdate) ClearOldVersion() *ConfigAuditLogUpdate {
	_u.mutation.ClearOldVersion()
	return _u
}

// SetNewVersion sets the "new_version" field.
func (_u *ConfigAuditLogUpdate) SetNewVersion(v int) *ConfigAuditLogUpdate {
	_u.mutation.ResetNewVersion()
	_u.mutation.SetNewVersion(v)
	return _u
}

// SetNillableNewVersion sets the "new_version" field if the given value is not nil.
func (_u *ConfigAuditLogUpdate) SetNillableNewVersion(v *int) *ConfigAuditLogUpdate {
	if v != nil {
		_u.SetNewVersion(*v)
	}
	return _u
}

// AddNewVersion adds value to the "new_version" field.
func (_u *ConfigAuditLogUpdate) AddNewVersion(v int) *ConfigAuditLogUpdate {
	_u.mutation.AddNewVersion(v)
	return _u
}

// ClearNewVersion clears the value of the "new_version" field.
func (_u *ConfigAuditLogUpdate) ClearNewVersion() *ConfigAuditLogUpdate {
	_u.mutation.ClearNewVersion()
	return _u
}

// SetIsRollback sets the "is_rollback" field.
func (_u *ConfigAuditLogUpdate) SetIsRollback(v bool) *ConfigAuditLogUpdate {
	_u.mutation.SetIsRollback(v)
	return _u
}

// SetNillableIsRollback sets the "is_rollback" field if the given value is not nil.
func (_u *ConfigAuditLogUpdate) SetNillableIsRollback(v *bool) *ConfigAuditLogUpdate {
	if v != nil {
		_u.SetIsRollback(*v)
	}
	return _u
}

// SetRollbackFromLogID sets the "rollback_from_log_id" field.
func (_u *ConfigAuditLogUpdate) SetRollbackFromLogID(v string) *ConfigAuditLogUpdate {
	_u.mutation.SetRollbackFromLogID(v)
	return _u
}

// SetNillableRollbackFromLogID sets the "rollback_from_log_id" field if the given value is not nil.
func (_u *ConfigAuditLogUpdate) SetNillableRollbackFromLogID(v *string) *ConfigAuditLogUpdate {
	if v != nil {
		_u.SetRollbackFromLogID(*v)
	}
	return _u
}

// ClearRollbackFromLogID clears the value of the "rollback_from_log_id" field.
func (_u *ConfigAuditLogUpdate) ClearRollbackFromLogID() *ConfigAuditLogUpdate {
	_u.mutation.ClearRollbackFromLogID()
	return _u
}

// Mutation returns the ConfigAuditLogMutation object of the builder.
func (_u *ConfigAuditLogUpdate) Mutation() *ConfigAuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConfigAuditLogUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigAuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConfigAuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigAuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConfigAuditLogUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := configauditlog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConfigAuditLogUpdate) check() error {
	if v, ok := _u.mutation.ConfigKey(); ok {
		if err := configauditlog.ConfigKeyValidator(v); err != nil {
			return &ValidationError{Name: "config_key", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.config_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OldValue(); ok {
		if err := configauditlog.OldValueValidator(v); err != nil {
			return &ValidationError{Name: "old_value", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.old_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NewValue(); ok {
		if err := configauditlog.NewValueValidator(v); err != nil {
			return &ValidationError{Name: "new_value", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.new_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChangeType(); ok {
		if err := configauditlog.ChangeTypeValidator(v); err != nil {
			return &ValidationError{Name: "change_type", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.change_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChangedByName(); ok {
		if err := configauditlog.ChangedByNameValidator(v); err != nil {
			return &ValidationError{Name: "changed_by_name", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.changed_by_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServiceName(); ok {
		if err := configauditlog.ServiceNameValidator(v); err != nil {
			return &ValidationError{Name: "service_name", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.service_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := configauditlog.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfigGroup(); ok {
		if err := configauditlog.ConfigGroupValidator(v); err != nil {
			return &ValidationError{Name: "config_group", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.config_group": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChangeReason(); ok {
		if err := configauditlog.ChangeReasonValidator(v); err != nil {
			return &ValidationError{Name: "change_reason", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.change_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := configauditlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := configauditlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RollbackFromLogID(); ok {
		if err := configauditlog.RollbackFromLogIDValidator(v); err != nil {
			return &ValidationError{Name: "rollback_from_log_id", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.rollback_from_log_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ConfigAuditLogUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ConfigAuditLogUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ConfigAuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(configauditlog.Table, configauditlog.Columns, sqlgraph.NewFieldSpec(configauditlog.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(configauditlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(configauditlog.FieldDepartmentID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(configauditlog.FieldDepartmentID, field.TypeUint64, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(configauditlog.FieldDepartmentID, field.TypeUint64)
	}
	if value, ok := _u.mutation.ConfigKey(); ok {
		_spec.SetField(configauditlog.FieldConfigKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.OldValue(); ok {
		_spec.SetField(configauditlog.FieldOldValue, field.TypeString, value)
	}
	if _u.mutation.OldValueCleared() {
		_spec.ClearField(configauditlog.FieldOldValue, field.TypeString)
	}
	if value, ok := _u.mutation.NewValue(); ok {
		_spec.SetField(configauditlog.FieldNewValue, field.TypeString, value)
	}
	if _u.mutation.NewValueCleared() {
		_spec.ClearField(configauditlog.FieldNewValue, field.TypeString)
	}
	if value, ok := _u.mutation.ChangeType(); ok {
		_spec.SetField(configauditlog.FieldChangeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChangedBy(); ok {
		_spec.SetField(configauditlog.FieldChangedBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedChangedBy(); ok {
		_spec.AddField(configauditlog.FieldChangedBy, field.TypeUint64, value)
	}
	if _u.mutation.ChangedByCleared() {
		_spec.ClearField(configauditlog.FieldChangedBy, field.TypeUint64)
	}
	if value, ok := _u.mutation.ChangedByName(); ok {
		_spec.SetField(configauditlog.FieldChangedByName, field.TypeString, value)
	}
	if _u.mutation.ChangedByNameCleared() {
		_spec.ClearField(configauditlog.FieldChangedByName, field.TypeString)
	}
	if value, ok := _u.mutation.ServiceName(); ok {
		_spec.SetField(configauditlog.FieldServiceName, field.TypeString, value)
	}
	if _u.mutation.ServiceNameCleared() {
		_spec.ClearField(configauditlog.FieldServiceName, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(configauditlog.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(configauditlog.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.ConfigGroup(); ok {
		_spec.SetField(configauditlog.FieldConfigGroup, field.TypeString, value)
	}
	if _u.mutation.ConfigGroupCleared() {
		_spec.ClearField(configauditlog.FieldConfigGroup, field.TypeString)
	}
	if value, ok := _u.mutation.ChangeReason(); ok {
		_spec.SetField(configauditlog.FieldChangeReason, field.TypeString, value)
	}
	if _u.mutation.ChangeReasonCleared() {
		_spec.ClearField(configauditlog.FieldChangeReason, field.TypeString)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(configauditlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(configauditlog.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(configauditlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(configauditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.OldVersion(); ok {
		_spec.SetField(configauditlog.FieldOldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOldVersion(); ok {
		_spec.AddField(configauditlog.FieldOldVersion, field.TypeInt, value)
	}
	if _u.mutation.OldVersionCleared() {
		_spec.ClearField(configauditlog.FieldOldVersion, field.TypeInt)
	}
	if value, ok := _u.mutation.NewVersion(); ok {
		_spec.SetField(configauditlog.FieldNewVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNewVersion(); ok {
		_spec.AddField(configauditlog.FieldNewVersion, field.TypeInt, value)
	}
	if _u.mutation.NewVersionCleared() {
		_spec.ClearField(configauditlog.FieldNewVersion, field.TypeInt)
	}
	if value, ok := _u.mutation.IsRollback(); ok {
		_spec.SetField(configauditlog.FieldIsRollback, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RollbackFromLogID(); ok {
		_spec.SetField(configauditlog.FieldRollbackFromLogID, field.TypeString, value)
	}
	if _u.mutation.RollbackFromLogIDCleared() {
		_spec.ClearField(configauditlog.FieldRollbackFromLogID, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConfigAuditLogUpdateOne is the builder for updating a single ConfigAuditLog entity.
type ConfigAuditLogUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ConfigAuditLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConfigAuditLogUpdateOne) SetUpdatedAt(v time.Time) *ConfigAuditLogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *ConfigAuditLogUpdateOne) SetDepartmentID(v uint64) *ConfigAuditLogUpdateOne {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *ConfigAuditLogUpdateOne) SetNillableDepartmentID(v *uint64) *ConfigAuditLogUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *ConfigAuditLogUpdateOne) AddDepartmentID(v int64) *ConfigAuditLogUpdateOne {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *ConfigAuditLogUpdateOne) ClearDepartmentID() *ConfigAuditLogUpdateOne {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetConfigKey sets the "config_key" field.
func (_u *ConfigAuditLogUpdateOne) SetConfigKey(v string) *ConfigAuditLogUpdateOne {
	_u.mutation.SetConfigKey(v)
	return _u
}

// SetNillableConfigKey sets the "config_key" field if the given value is not nil.
func (_u *ConfigAuditLogUpdateOne) SetNillableConfigKey(v *string) *ConfigAuditLogUpdateOne {
	if v != nil {
		_u.SetConfigKey(*v)
	}
	return _u
}

// SetOldValue sets the "old_value" field.
func (_u *ConfigAuditLogUpdateOne) SetOldValue(v string) *ConfigAuditLogUpdateOne {
	_u.mutation.SetOldValue(v)
	return _u
}

// SetNillableOldValue sets the "old_value" field if the given value is not nil.
func (_u *ConfigAuditLogUpdateOne) SetNillableOldValue(v *string) *ConfigAuditLogUpdateOne {
	if v != nil {
		_u.SetOldValue(*v)
	}
	return _u
}

// ClearOldValue clears the value of the "old_value" field.
func (_u *ConfigAuditLogUpdateOne) ClearOldValue() *ConfigAuditLogUpdateOne {
	_u.mutation.ClearOldValue()
	return _u
}

// SetNewValue sets the "new_value" field.
func (_u *ConfigAuditLogUpdateOne) SetNewValue(v string) *ConfigAuditLogUpdateOne {
	_u.mutation.SetNewValue(v)
	return _u
}

// SetNillableNewValue sets the "new_value" field if the given value is not nil.
func (_u *ConfigAuditLogUpdateOne) SetNillableNewValue(v *string) *ConfigAuditLogUpdateOne {
	if v != nil {
		_u.SetNewValue(*v)
	}
	return _u
}

// ClearNewValue clears the value of the "new_value" field.
func (_u *ConfigAuditLogUpdateOne) ClearNewValue() *ConfigAuditLogUpdateOne {
	_u.mutation.ClearNewValue()
	return _u
}

// SetChangeType sets the "change_type" field.
func (_u *ConfigAuditLogUpdateOne) SetChangeType(v string) *ConfigAuditLogUpdateOne {
	_u.mutation.SetChangeType(v)
	return _u
}

// SetNillableChangeType sets the "change_type" field if the given value is not nil.
func (_u *ConfigAuditLogUpdateOne) SetNillableChangeType(v *string) *ConfigAuditLogUpdateOne {
	if v != nil {
		_u.SetChangeType(*v)
	}
	return _u
}

// SetChangedBy sets the "changed_by" field.
func (_u *ConfigAuditLogUpdateOne) SetChangedBy(v uint64) *ConfigAuditLogUpdateOne {
	_u.mutation.ResetChangedBy()
	_u.mutation.SetChangedBy(v)
	return _u
}

// SetNillableChangedBy sets the "changed_by" field if the given value is not nil.
func (_u *ConfigAuditLogUpdateOne) SetNillableChangedBy(v *uint64) *ConfigAuditLogUpdateOne {
	if v != nil {
		_u.SetChangedBy(*v)
	}
	return _u
}

// AddChangedBy adds value to the "changed_by" field.
func (_u *ConfigAuditLogUpdateOne) AddChangedBy(v int64) *ConfigAuditLogUpdateOne {
	_u.mutation.AddChangedBy(v)
	return _u
}

// ClearChangedBy clears the value of the "changed_by" field.
func (_u *ConfigAuditLogUpdateOne) ClearChangedBy() *ConfigAuditLogUpdateOne {
	_u.mutation.ClearChangedBy()
	return _u
}

// SetChangedByName sets the "changed_by_name" field.
func (_u *ConfigAuditLogUpdateOne) SetChangedByName(v string) *ConfigAuditLogUpdateOne {
	_u.mutation.SetChangedByName(v)
	return _u
}

// SetNillableChangedByName sets the "changed_by_name" field if the given value is not nil.
func (_u *ConfigAuditLogUpdateOne) SetNillableChangedByName(v *string) *ConfigAuditLogUpdateOne {
	if v != nil {
		_u.SetChangedByName(*v)
	}
	return _u
}

// ClearChangedByName clears the value of the "changed_by_name" field.
func (_u *ConfigAuditLogUpdateOne) ClearChangedByName() *ConfigAuditLogUpdateOne {
	_u.mutation.ClearChangedByName()
	return _u
}

// SetServiceName sets the "service_name" field.
func (_u *ConfigAuditLogUpdateOne) SetServiceName(v string) *ConfigAuditLogUpdateOne {
	_u.mutation.SetServiceName(v)
	return _u
}

// SetNillableServiceName sets the "service_name" field if the given value is not nil.
func (_u *ConfigAuditLogUpdateOne) SetNillableServiceName(v *string) *ConfigAuditLogUpdateOne {
	if v != nil {
		_u.SetServiceName(*v)
	}
	return _u
}

// ClearServiceName clears the value of the "service_name" field.
func (_u *ConfigAuditLogUpdateOne) ClearServiceName() *ConfigAuditLogUpdateOne {
	_u.mutation.ClearServiceName()
	return _u
}

// SetCategory sets the "category" field.
func (_u *ConfigAuditLogUpdateOne) SetCategory(v string) *ConfigAuditLogUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ConfigAuditLogUpdateOne) SetNillableCategory(v *string) *ConfigAuditLogUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *ConfigAuditLogUpdateOne) ClearCategory() *ConfigAuditLogUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// SetConfigGroup sets the "config_group" field.
func (_u *ConfigAuditLogUpdateOne) SetConfigGroup(v string) *ConfigAuditLogUpdateOne {
	_u.mutation.SetConfigGroup(v)
	return _u
}

// SetNillableConfigGroup sets the "config_group" field if the given value is not nil.
func (_u *ConfigAuditLogUpdateOne) SetNillableConfigGroup(v *string) *ConfigAuditLogUpdateOne {
	if v != nil {
		_u.SetConfigGroup(*v)
	}
	return _u
}

// ClearConfigGroup clears the value of the "config_group" field.
func (_u *ConfigAuditLogUpdateOne) ClearConfigGroup() *ConfigAuditLogUpdateOne {
	_u.mutation.ClearConfigGroup()
	return _u
}

// SetChangeReason sets the "change_reason" field.
func (_u *ConfigAuditLogUpdateOne) SetChangeReason(v string) *ConfigAuditLogUpdateOne {
	_u.mutation.SetChangeReason(v)
	return _u
}

// SetNillableChangeReason sets the "change_reason" field if the given value is not nil.
func (_u *ConfigAuditLogUpdateOne) SetNillableChangeReason(v *string) *ConfigAuditLogUpdateOne {
	if v != nil {
		_u.SetChangeReason(*v)
	}
	return _u
}

// ClearChangeReason clears the value of the "change_reason" field.
func (_u *ConfigAuditLogUpdateOne) ClearChangeReason() *ConfigAuditLogUpdateOne {
	_u.mutation.ClearChangeReason()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *ConfigAuditLogUpdateOne) SetIPAddress(v string) *ConfigAuditLogUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *ConfigAuditLogUpdateOne) SetNillableIPAddress(v *string) *ConfigAuditLogUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *ConfigAuditLogUpdateOne) ClearIPAddress() *ConfigAuditLogUpdateOne {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *ConfigAuditLogUpdateOne) SetUserAgent(v string) *ConfigAuditLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *ConfigAuditLogUpdateOne) SetNillableUserAgent(v *string) *ConfigAuditLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *ConfigAuditLogUpdateOne) ClearUserAgent() *ConfigAuditLogUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetOldVersion sets the "old_version" field.
func (_u *ConfigAuditLogUpdateOne) SetOldVersion(v int) *ConfigAuditLogUpdateOne {
	_u.mutation.ResetOldVersion()
	_u.mutation.SetOldVersion(v)
	return _u
}

// SetNillableOldVersion sets the "old_version" field if the given value is not nil.
func (_u *ConfigAuditLogUpdateOne) SetNillableOldVersion(v *int) *ConfigAuditLogUpdateOne {
	if v != nil {
		_u.SetOldVersion(*v)
	}
	return _u
}

// AddOldVersion adds value to the "old_version" field.
func (_u *ConfigAuditLogUpdateOne) AddOldVersion(v int) *ConfigAuditLogUpdateOne {
	_u.mutation.AddOldVersion(v)
	return _u
}

// ClearOldVersion clears the value of the "old_version" field.
func (_u *ConfigAuditLogUpdateOne) ClearOldVersion() *ConfigAuditLogUpdateOne {
	_u.mutation.ClearOldVersion()
	return _u
}

// SetNewVersion sets the "new_version" field.
func (_u *ConfigAuditLogUpdateOne) SetNewVersion(v int) *ConfigAuditLogUpdateOne {
	_u.mutation.ResetNewVersion()
	_u.mutation.SetNewVersion(v)
	return _u
}

// SetNillableNewVersion sets the "new_version" field if the given value is not nil.
func (_u *ConfigAuditLogUpdateOne) SetNillableNewVersion(v *int) *ConfigAuditLogUpdateOne {
	if v != nil {
		_u.SetNewVersion(*v)
	}
	return _u
}

// AddNewVersion adds value to the "new_version" field.
func (_u *ConfigAuditLogUpdateOne) AddNewVersion(v int) *ConfigAuditLogUpdateOne {
	_u.mutation.AddNewVersion(v)
	return _u
}

// ClearNewVersion clears the value of the "new_version" field.
func (_u *ConfigAuditLogUpdateOne) ClearNewVersion() *ConfigAuditLogUpdateOne {
	_u.mutation.ClearNewVersion()
	return _u
}

// SetIsRollback sets the "is_rollback" field.
func (_u *ConfigAuditLogUpdateOne) SetIsRollback(v bool) *ConfigAuditLogUpdateOne {
	_u.mutation.SetIsRollback(v)
	return _u
}

// SetNillableIsRollback sets the "is_rollback" field if the given value is not nil.
func (_u *ConfigAuditLogUpdateOne) SetNillableIsRollback(v *bool) *ConfigAuditLogUpdateOne {
	if v != nil {
		_u.SetIsRollback(*v)
	}
	return _u
}

// SetRollbackFromLogID sets the "rollback_from_log_id" field.
func (_u *ConfigAuditLogUpdateOne) SetRollbackFromLogID(v string) *ConfigAuditLogUpdateOne {
	_u.mutation.SetRollbackFromLogID(v)
	return _u
}

// SetNillableRollbackFromLogID sets the "rollback_from_log_id" field if the given value is not nil.
func (_u *ConfigAuditLogUpdateOne) SetNillableRollbackFromLogID(v *string) *ConfigAuditLogUpdateOne {
	if v != nil {
		_u.SetRollbackFromLogID(*v)
	}
	return _u
}

// ClearRollbackFromLogID clears the value of the "rollback_from_log_id" field.
func (_u *ConfigAuditLogUpdateOne) ClearRollbackFromLogID() *ConfigAuditLogUpdateOne {
	_u.mutation.ClearRollbackFromLogID()
	return _u
}

// Mutation returns the ConfigAuditLogMutation object of the builder.
func (_u *ConfigAuditLogUpdateOne) Mutation() *ConfigAuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the ConfigAuditLogUpdate builder.
func (_u *ConfigAuditLogUpdateOne) Where(ps ...predicate.ConfigAuditLog) *ConfigAuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConfigAuditLogUpdateOne) Select(field string, fields ...string) *ConfigAuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ConfigAuditLog entity.
func (_u *ConfigAuditLogUpdateOne) Save(ctx context.Context) (*ConfigAuditLog, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigAuditLogUpdateOne) SaveX(ctx context.Context) *ConfigAuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConfigAuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigAuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConfigAuditLogUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := configauditlog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConfigAuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.ConfigKey(); ok {
		if err := configauditlog.ConfigKeyValidator(v); err != nil {
			return &ValidationError{Name: "config_key", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.config_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OldValue(); ok {
		if err := configauditlog.OldValueValidator(v); err != nil {
			return &ValidationError{Name: "old_value", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.old_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NewValue(); ok {
		if err := configauditlog.NewValueValidator(v); err != nil {
			return &ValidationError{Name: "new_value", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.new_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChangeType(); ok {
		if err := configauditlog.ChangeTypeValidator(v); err != nil {
			return &ValidationError{Name: "change_type", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.change_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChangedByName(); ok {
		if err := configauditlog.ChangedByNameValidator(v); err != nil {
			return &ValidationError{Name: "changed_by_name", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.changed_by_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServiceName(); ok {
		if err := configauditlog.ServiceNameValidator(v); err != nil {
			return &ValidationError{Name: "service_name", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.service_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := configauditlog.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfigGroup(); ok {
		if err := configauditlog.ConfigGroupValidator(v); err != nil {
			return &ValidationError{Name: "config_group", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.config_group": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChangeReason(); ok {
		if err := configauditlog.ChangeReasonValidator(v); err != nil {
			return &ValidationError{Name: "change_reason", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.change_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := configauditlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := configauditlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RollbackFromLogID(); ok {
		if err := configauditlog.RollbackFromLogIDValidator(v); err != nil {
			return &ValidationError{Name: "rollback_from_log_id", err: fmt.Errorf(`ent: validator failed for field "ConfigAuditLog.rollback_from_log_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ConfigAuditLogUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ConfigAuditLogUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ConfigAuditLogUpdateOne) sqlSave(ctx context.Context) (_node *ConfigAuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(configauditlog.Table, configauditlog.Columns, sqlgraph.NewFieldSpec(configauditlog.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ConfigAuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, configauditlog.FieldID)
		for _, f := range fields {
			if !configauditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != configauditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(configauditlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(configauditlog.FieldDepartmentID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(configauditlog.FieldDepartmentID, field.TypeUint64, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(configauditlog.FieldDepartmentID, field.TypeUint64)
	}
	if value, ok := _u.mutation.ConfigKey(); ok {
		_spec.SetField(configauditlog.FieldConfigKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.OldValue(); ok {
		_spec.SetField(configauditlog.FieldOldValue, field.TypeString, value)
	}
	if _u.mutation.OldValueCleared() {
		_spec.ClearField(configauditlog.FieldOldValue, field.TypeString)
	}
	if value, ok := _u.mutation.NewValue(); ok {
		_spec.SetField(configauditlog.FieldNewValue, field.TypeString, value)
	}
	if _u.mutation.NewValueCleared() {
		_spec.ClearField(configauditlog.FieldNewValue, field.TypeString)
	}
	if value, ok := _u.mutation.ChangeType(); ok {
		_spec.SetField(configauditlog.FieldChangeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChangedBy(); ok {
		_spec.SetField(configauditlog.FieldChangedBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedChangedBy(); ok {
		_spec.AddField(configauditlog.FieldChangedBy, field.TypeUint64, value)
	}
	if _u.mutation.ChangedByCleared() {
		_spec.ClearField(configauditlog.FieldChangedBy, field.TypeUint64)
	}
	if value, ok := _u.mutation.ChangedByName(); ok {
		_spec.SetField(configauditlog.FieldChangedByName, field.TypeString, value)
	}
	if _u.mutation.ChangedByNameCleared() {
		_spec.ClearField(configauditlog.FieldChangedByName, field.TypeString)
	}
	if value, ok := _u.mutation.ServiceName(); ok {
		_spec.SetField(configauditlog.FieldServiceName, field.TypeString, value)
	}
	if _u.mutation.ServiceNameCleared() {
		_spec.ClearField(configauditlog.FieldServiceName, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(configauditlog.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(configauditlog.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.ConfigGroup(); ok {
		_spec.SetField(configauditlog.FieldConfigGroup, field.TypeString, value)
	}
	if _u.mutation.ConfigGroupCleared() {
		_spec.ClearField(configauditlog.FieldConfigGroup, field.TypeString)
	}
	if value, ok := _u.mutation.ChangeReason(); ok {
		_spec.SetField(configauditlog.FieldChangeReason, field.TypeString, value)
	}
	if _u.mutation.ChangeReasonCleared() {
		_spec.ClearField(configauditlog.FieldChangeReason, field.TypeString)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(configauditlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(configauditlog.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(configauditlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(configauditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.OldVersion(); ok {
		_spec.SetField(configauditlog.FieldOldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOldVersion(); ok {
		_spec.AddField(configauditlog.FieldOldVersion, field.TypeInt, value)
	}
	if _u.mutation.OldVersionCleared() {
		_spec.ClearField(configauditlog.FieldOldVersion, field.TypeInt)
	}
	if value, ok := _u.mutation.NewVersion(); ok {
		_spec.SetField(configauditlog.FieldNewVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNewVersion(); ok {
		_spec.AddField(configauditlog.FieldNewVersion, field.TypeInt, value)
	}
	if _u.mutation.NewVersionCleared() {
		_spec.ClearField(configauditlog.FieldNewVersion, field.TypeInt)
	}
	if value, ok := _u.mutation.IsRollback(); ok {
		_spec.SetField(configauditlog.FieldIsRollback, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RollbackFromLogID(); ok {
		_spec.SetField(configauditlog.FieldRollbackFromLogID, field.TypeString, value)
	}
	if _u.mutation.RollbackFromLogIDCleared() {
		_spec.ClearField(configauditlog.FieldRollbackFromLogID, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ConfigAuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
