// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/coder-lulu/newbee-io-rpc/ent/datatarget"
)

// DataTarget is the model entity for the DataTarget schema.
type DataTarget struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// Create Time | 创建日期
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Update Time | 修改日期
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Tenant ID | 租户 ID
	TenantID uint64 `json:"tenant_id,omitempty"`
	// Status 1: normal 2: ban | 状态 1 正常 2 禁用
	Status uint8 `json:"status,omitempty"`
	// 目标名称
	TargetName string `json:"target_name,omitempty"`
	// 目标编码
	TargetCode string `json:"target_code,omitempty"`
	// 描述
	Description string `json:"description,omitempty"`
	// 目标类型: database, api, file, mq, cache
	TargetType string `json:"target_type,omitempty"`
	// 目标系统名称
	TargetSystem string `json:"target_system,omitempty"`
	// 连接配置JSON
	ConnectionConfig string `json:"connection_config,omitempty"`
	// 认证配置JSON
	AuthConfig string `json:"auth_config,omitempty"`
	// 是否启用
	IsActive bool `json:"is_active,omitempty"`
	// 扩展元数据JSON
	Metadata     string `json:"metadata,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DataTarget) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case datatarget.FieldIsActive:
			values[i] = new(sql.NullBool)
		case datatarget.FieldID, datatarget.FieldTenantID, datatarget.FieldStatus:
			values[i] = new(sql.NullInt64)
		case datatarget.FieldTargetName, datatarget.FieldTargetCode, datatarget.FieldDescription, datatarget.FieldTargetType, datatarget.FieldTargetSystem, datatarget.FieldConnectionConfig, datatarget.FieldAuthConfig, datatarget.FieldMetadata:
			values[i] = new(sql.NullString)
		case datatarget.FieldCreatedAt, datatarget.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DataTarget fields.
func (_m *DataTarget) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case datatarget.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case datatarget.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case datatarget.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case datatarget.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = uint64(value.Int64)
			}
		case datatarget.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = uint8(value.Int64)
			}
		case datatarget.FieldTargetName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_name", values[i])
			} else if value.Valid {
				_m.TargetName = value.String
			}
		case datatarget.FieldTargetCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_code", values[i])
			} else if value.Valid {
				_m.TargetCode = value.String
			}
		case datatarget.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case datatarget.FieldTargetType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_type", values[i])
			} else if value.Valid {
				_m.TargetType = value.String
			}
		case datatarget.FieldTargetSystem:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_system", values[i])
			} else if value.Valid {
				_m.TargetSystem = value.String
			}
		case datatarget.FieldConnectionConfig:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field connection_config", values[i])
			} else if value.Valid {
				_m.ConnectionConfig = value.String
			}
		case datatarget.FieldAuthConfig:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_config", values[i])
			} else if value.Valid {
				_m.AuthConfig = value.String
			}
		case datatarget.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case datatarget.FieldMetadata:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value.Valid {
				_m.Metadata = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DataTarget.
// This includes values selected through modifiers, order, etc.
func (_m *DataTarget) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DataTarget.
// Note that you need to call DataTarget.Unwrap() before calling this method if this DataTarget
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DataTarget) Update() *DataTargetUpdateOne {
	return NewDataTargetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DataTarget entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DataTarget) Unwrap() *DataTarget {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DataTarget is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DataTarget) String() string {
	var builder strings.Builder
	builder.WriteString("DataTarget(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("target_name=")
	builder.WriteString(_m.TargetName)
	builder.WriteString(", ")
	builder.WriteString("target_code=")
	builder.WriteString(_m.TargetCode)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("target_type=")
	builder.WriteString(_m.TargetType)
	builder.WriteString(", ")
	builder.WriteString("target_system=")
	builder.WriteString(_m.TargetSystem)
	builder.WriteString(", ")
	builder.WriteString("connection_config=")
	builder.WriteString(_m.ConnectionConfig)
	builder.WriteString(", ")
	builder.WriteString("auth_config=")
	builder.WriteString(_m.AuthConfig)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(_m.Metadata)
	builder.WriteByte(')')
	return builder.String()
}

// DataTargets is a parsable slice of DataTarget.
type DataTargets []*DataTarget
