// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-io-rpc/ent/discoverytemplate"
	"github.com/coder-lulu/newbee-io-rpc/ent/predicate"
)

// DiscoveryTemplateDelete is the builder for deleting a DiscoveryTemplate entity.
type DiscoveryTemplateDelete struct {
	config
	hooks    []Hook
	mutation *DiscoveryTemplateMutation
}

// Where appends a list predicates to the DiscoveryTemplateDelete builder.
func (_d *DiscoveryTemplateDelete) Where(ps ...predicate.DiscoveryTemplate) *DiscoveryTemplateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DiscoveryTemplateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DiscoveryTemplateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DiscoveryTemplateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(discoverytemplate.Table, sqlgraph.NewFieldSpec(discoverytemplate.FieldID, field.TypeUint64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DiscoveryTemplateDeleteOne is the builder for deleting a single DiscoveryTemplate entity.
type DiscoveryTemplateDeleteOne struct {
	_d *DiscoveryTemplateDelete
}

// Where appends a list predicates to the DiscoveryTemplateDelete builder.
func (_d *DiscoveryTemplateDeleteOne) Where(ps ...predicate.DiscoveryTemplate) *DiscoveryTemplateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DiscoveryTemplateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{discoverytemplate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DiscoveryTemplateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
