// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/coder-lulu/newbee-io-rpc/ent/discoveryproviderschema"
)

// DiscoveryProviderSchema is the model entity for the DiscoveryProviderSchema schema.
type DiscoveryProviderSchema struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// Create Time | 创建日期
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Update Time | 修改日期
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Status 1: normal 2: ban | 状态 1 正常 2 禁用
	Status uint8 `json:"status,omitempty"`
	// Tenant ID | 租户 ID
	TenantID uint64 `json:"tenant_id,omitempty"`
	// Department ID | 部门 ID (0=所有部门共享)
	DepartmentID uint64 `json:"department_id,omitempty"`
	// Provider唯一标识
	ProviderID string `json:"provider_id,omitempty"`
	// Provider名称
	ProviderName string `json:"provider_name,omitempty"`
	// Provider类别
	Category discoveryproviderschema.Category `json:"category,omitempty"`
	// 参数定义Schema(JSON)
	ParameterSchema []interface{} `json:"parameter_schema,omitempty"`
	// 字段定义Schema(JSON)
	FieldSchema []interface{} `json:"field_schema,omitempty"`
	// 描述
	Description string `json:"description,omitempty"`
	// 版本号
	Version string `json:"version,omitempty"`
	// 图标URL
	IconURL string `json:"icon_url,omitempty"`
	// 是否内置Provider
	IsBuiltin bool `json:"is_builtin,omitempty"`
	// 执行模式: worker-后台任务, agent-Agent执行, direct-直接执行
	ExecutionMode discoveryproviderschema.ExecutionMode `json:"execution_mode,omitempty"`
	// 是否启用
	IsActive     bool `json:"is_active,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DiscoveryProviderSchema) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case discoveryproviderschema.FieldParameterSchema, discoveryproviderschema.FieldFieldSchema:
			values[i] = new([]byte)
		case discoveryproviderschema.FieldIsBuiltin, discoveryproviderschema.FieldIsActive:
			values[i] = new(sql.NullBool)
		case discoveryproviderschema.FieldID, discoveryproviderschema.FieldStatus, discoveryproviderschema.FieldTenantID, discoveryproviderschema.FieldDepartmentID:
			values[i] = new(sql.NullInt64)
		case discoveryproviderschema.FieldProviderID, discoveryproviderschema.FieldProviderName, discoveryproviderschema.FieldCategory, discoveryproviderschema.FieldDescription, discoveryproviderschema.FieldVersion, discoveryproviderschema.FieldIconURL, discoveryproviderschema.FieldExecutionMode:
			values[i] = new(sql.NullString)
		case discoveryproviderschema.FieldCreatedAt, discoveryproviderschema.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DiscoveryProviderSchema fields.
func (_m *DiscoveryProviderSchema) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case discoveryproviderschema.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case discoveryproviderschema.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case discoveryproviderschema.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case discoveryproviderschema.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = uint8(value.Int64)
			}
		case discoveryproviderschema.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = uint64(value.Int64)
			}
		case discoveryproviderschema.FieldDepartmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field department_id", values[i])
			} else if value.Valid {
				_m.DepartmentID = uint64(value.Int64)
			}
		case discoveryproviderschema.FieldProviderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = value.String
			}
		case discoveryproviderschema.FieldProviderName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_name", values[i])
			} else if value.Valid {
				_m.ProviderName = value.String
			}
		case discoveryproviderschema.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = discoveryproviderschema.Category(value.String)
			}
		case discoveryproviderschema.FieldParameterSchema:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field parameter_schema", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ParameterSchema); err != nil {
					return fmt.Errorf("unmarshal field parameter_schema: %w", err)
				}
			}
		case discoveryproviderschema.FieldFieldSchema:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field field_schema", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.FieldSchema); err != nil {
					return fmt.Errorf("unmarshal field field_schema: %w", err)
				}
			}
		case discoveryproviderschema.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case discoveryproviderschema.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case discoveryproviderschema.FieldIconURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon_url", values[i])
			} else if value.Valid {
				_m.IconURL = value.String
			}
		case discoveryproviderschema.FieldIsBuiltin:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_builtin", values[i])
			} else if value.Valid {
				_m.IsBuiltin = value.Bool
			}
		case discoveryproviderschema.FieldExecutionMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field execution_mode", values[i])
			} else if value.Valid {
				_m.ExecutionMode = discoveryproviderschema.ExecutionMode(value.String)
			}
		case discoveryproviderschema.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DiscoveryProviderSchema.
// This includes values selected through modifiers, order, etc.
func (_m *DiscoveryProviderSchema) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DiscoveryProviderSchema.
// Note that you need to call DiscoveryProviderSchema.Unwrap() before calling this method if this DiscoveryProviderSchema
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DiscoveryProviderSchema) Update() *DiscoveryProviderSchemaUpdateOne {
	return NewDiscoveryProviderSchemaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DiscoveryProviderSchema entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DiscoveryProviderSchema) Unwrap() *DiscoveryProviderSchema {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DiscoveryProviderSchema is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DiscoveryProviderSchema) String() string {
	var builder strings.Builder
	builder.WriteString("DiscoveryProviderSchema(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("department_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DepartmentID))
	builder.WriteString(", ")
	builder.WriteString("provider_id=")
	builder.WriteString(_m.ProviderID)
	builder.WriteString(", ")
	builder.WriteString("provider_name=")
	builder.WriteString(_m.ProviderName)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(fmt.Sprintf("%v", _m.Category))
	builder.WriteString(", ")
	builder.WriteString("parameter_schema=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParameterSchema))
	builder.WriteString(", ")
	builder.WriteString("field_schema=")
	builder.WriteString(fmt.Sprintf("%v", _m.FieldSchema))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("icon_url=")
	builder.WriteString(_m.IconURL)
	builder.WriteString(", ")
	builder.WriteString("is_builtin=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsBuiltin))
	builder.WriteString(", ")
	builder.WriteString("execution_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExecutionMode))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteByte(')')
	return builder.String()
}

// DiscoveryProviderSchemas is a parsable slice of DiscoveryProviderSchema.
type DiscoveryProviderSchemas []*DiscoveryProviderSchema
