// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-io-rpc/ent/fieldmapping"
	"github.com/coder-lulu/newbee-io-rpc/ent/predicate"
)

// FieldMappingUpdate is the builder for updating FieldMapping entities.
type FieldMappingUpdate struct {
	config
	hooks     []Hook
	mutation  *FieldMappingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the FieldMappingUpdate builder.
func (_u *FieldMappingUpdate) Where(ps ...predicate.FieldMapping) *FieldMappingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FieldMappingUpdate) SetUpdatedAt(v time.Time) *FieldMappingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *FieldMappingUpdate) SetStatus(v uint8) *FieldMappingUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableStatus(v *uint8) *FieldMappingUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *FieldMappingUpdate) AddStatus(v int8) *FieldMappingUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *FieldMappingUpdate) ClearStatus() *FieldMappingUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetMappingName sets the "mapping_name" field.
func (_u *FieldMappingUpdate) SetMappingName(v string) *FieldMappingUpdate {
	_u.mutation.SetMappingName(v)
	return _u
}

// SetNillableMappingName sets the "mapping_name" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableMappingName(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetMappingName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *FieldMappingUpdate) SetDescription(v string) *FieldMappingUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableDescription(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FieldMappingUpdate) ClearDescription() *FieldMappingUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetMappingType sets the "mapping_type" field.
func (_u *FieldMappingUpdate) SetMappingType(v string) *FieldMappingUpdate {
	_u.mutation.SetMappingType(v)
	return _u
}

// SetNillableMappingType sets the "mapping_type" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableMappingType(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetMappingType(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *FieldMappingUpdate) SetIsActive(v bool) *FieldMappingUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableIsActive(v *bool) *FieldMappingUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetSourceField sets the "source_field" field.
func (_u *FieldMappingUpdate) SetSourceField(v string) *FieldMappingUpdate {
	_u.mutation.SetSourceField(v)
	return _u
}

// SetNillableSourceField sets the "source_field" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableSourceField(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetSourceField(*v)
	}
	return _u
}

// SetSourceFieldPath sets the "source_field_path" field.
func (_u *FieldMappingUpdate) SetSourceFieldPath(v string) *FieldMappingUpdate {
	_u.mutation.SetSourceFieldPath(v)
	return _u
}

// SetNillableSourceFieldPath sets the "source_field_path" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableSourceFieldPath(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetSourceFieldPath(*v)
	}
	return _u
}

// ClearSourceFieldPath clears the value of the "source_field_path" field.
func (_u *FieldMappingUpdate) ClearSourceFieldPath() *FieldMappingUpdate {
	_u.mutation.ClearSourceFieldPath()
	return _u
}

// SetSourceDataType sets the "source_data_type" field.
func (_u *FieldMappingUpdate) SetSourceDataType(v string) *FieldMappingUpdate {
	_u.mutation.SetSourceDataType(v)
	return _u
}

// SetNillableSourceDataType sets the "source_data_type" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableSourceDataType(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetSourceDataType(*v)
	}
	return _u
}

// ClearSourceDataType clears the value of the "source_data_type" field.
func (_u *FieldMappingUpdate) ClearSourceDataType() *FieldMappingUpdate {
	_u.mutation.ClearSourceDataType()
	return _u
}

// SetSourceFormat sets the "source_format" field.
func (_u *FieldMappingUpdate) SetSourceFormat(v string) *FieldMappingUpdate {
	_u.mutation.SetSourceFormat(v)
	return _u
}

// SetNillableSourceFormat sets the "source_format" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableSourceFormat(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetSourceFormat(*v)
	}
	return _u
}

// ClearSourceFormat clears the value of the "source_format" field.
func (_u *FieldMappingUpdate) ClearSourceFormat() *FieldMappingUpdate {
	_u.mutation.ClearSourceFormat()
	return _u
}

// SetTargetField sets the "target_field" field.
func (_u *FieldMappingUpdate) SetTargetField(v string) *FieldMappingUpdate {
	_u.mutation.SetTargetField(v)
	return _u
}

// SetNillableTargetField sets the "target_field" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableTargetField(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetTargetField(*v)
	}
	return _u
}

// SetTargetFieldPath sets the "target_field_path" field.
func (_u *FieldMappingUpdate) SetTargetFieldPath(v string) *FieldMappingUpdate {
	_u.mutation.SetTargetFieldPath(v)
	return _u
}

// SetNillableTargetFieldPath sets the "target_field_path" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableTargetFieldPath(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetTargetFieldPath(*v)
	}
	return _u
}

// ClearTargetFieldPath clears the value of the "target_field_path" field.
func (_u *FieldMappingUpdate) ClearTargetFieldPath() *FieldMappingUpdate {
	_u.mutation.ClearTargetFieldPath()
	return _u
}

// SetTargetDataType sets the "target_data_type" field.
func (_u *FieldMappingUpdate) SetTargetDataType(v string) *FieldMappingUpdate {
	_u.mutation.SetTargetDataType(v)
	return _u
}

// SetNillableTargetDataType sets the "target_data_type" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableTargetDataType(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetTargetDataType(*v)
	}
	return _u
}

// ClearTargetDataType clears the value of the "target_data_type" field.
func (_u *FieldMappingUpdate) ClearTargetDataType() *FieldMappingUpdate {
	_u.mutation.ClearTargetDataType()
	return _u
}

// SetTargetFormat sets the "target_format" field.
func (_u *FieldMappingUpdate) SetTargetFormat(v string) *FieldMappingUpdate {
	_u.mutation.SetTargetFormat(v)
	return _u
}

// SetNillableTargetFormat sets the "target_format" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableTargetFormat(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetTargetFormat(*v)
	}
	return _u
}

// ClearTargetFormat clears the value of the "target_format" field.
func (_u *FieldMappingUpdate) ClearTargetFormat() *FieldMappingUpdate {
	_u.mutation.ClearTargetFormat()
	return _u
}

// SetTransformType sets the "transform_type" field.
func (_u *FieldMappingUpdate) SetTransformType(v string) *FieldMappingUpdate {
	_u.mutation.SetTransformType(v)
	return _u
}

// SetNillableTransformType sets the "transform_type" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableTransformType(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetTransformType(*v)
	}
	return _u
}

// SetTransformConfig sets the "transform_config" field.
func (_u *FieldMappingUpdate) SetTransformConfig(v string) *FieldMappingUpdate {
	_u.mutation.SetTransformConfig(v)
	return _u
}

// SetNillableTransformConfig sets the "transform_config" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableTransformConfig(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetTransformConfig(*v)
	}
	return _u
}

// ClearTransformConfig clears the value of the "transform_config" field.
func (_u *FieldMappingUpdate) ClearTransformConfig() *FieldMappingUpdate {
	_u.mutation.ClearTransformConfig()
	return _u
}

// SetDefaultValue sets the "default_value" field.
func (_u *FieldMappingUpdate) SetDefaultValue(v string) *FieldMappingUpdate {
	_u.mutation.SetDefaultValue(v)
	return _u
}

// SetNillableDefaultValue sets the "default_value" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableDefaultValue(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetDefaultValue(*v)
	}
	return _u
}

// ClearDefaultValue clears the value of the "default_value" field.
func (_u *FieldMappingUpdate) ClearDefaultValue() *FieldMappingUpdate {
	_u.mutation.ClearDefaultValue()
	return _u
}

// SetAllowNull sets the "allow_null" field.
func (_u *FieldMappingUpdate) SetAllowNull(v bool) *FieldMappingUpdate {
	_u.mutation.SetAllowNull(v)
	return _u
}

// SetNillableAllowNull sets the "allow_null" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableAllowNull(v *bool) *FieldMappingUpdate {
	if v != nil {
		_u.SetAllowNull(*v)
	}
	return _u
}

// SetIsRequired sets the "is_required" field.
func (_u *FieldMappingUpdate) SetIsRequired(v bool) *FieldMappingUpdate {
	_u.mutation.SetIsRequired(v)
	return _u
}

// SetNillableIsRequired sets the "is_required" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableIsRequired(v *bool) *FieldMappingUpdate {
	if v != nil {
		_u.SetIsRequired(*v)
	}
	return _u
}

// SetValidationRules sets the "validation_rules" field.
func (_u *FieldMappingUpdate) SetValidationRules(v string) *FieldMappingUpdate {
	_u.mutation.SetValidationRules(v)
	return _u
}

// SetNillableValidationRules sets the "validation_rules" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableValidationRules(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetValidationRules(*v)
	}
	return _u
}

// ClearValidationRules clears the value of the "validation_rules" field.
func (_u *FieldMappingUpdate) ClearValidationRules() *FieldMappingUpdate {
	_u.mutation.ClearValidationRules()
	return _u
}

// SetValidationRegex sets the "validation_regex" field.
func (_u *FieldMappingUpdate) SetValidationRegex(v string) *FieldMappingUpdate {
	_u.mutation.SetValidationRegex(v)
	return _u
}

// SetNillableValidationRegex sets the "validation_regex" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableValidationRegex(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetValidationRegex(*v)
	}
	return _u
}

// ClearValidationRegex clears the value of the "validation_regex" field.
func (_u *FieldMappingUpdate) ClearValidationRegex() *FieldMappingUpdate {
	_u.mutation.ClearValidationRegex()
	return _u
}

// SetLookupTable sets the "lookup_table" field.
func (_u *FieldMappingUpdate) SetLookupTable(v string) *FieldMappingUpdate {
	_u.mutation.SetLookupTable(v)
	return _u
}

// SetNillableLookupTable sets the "lookup_table" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableLookupTable(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetLookupTable(*v)
	}
	return _u
}

// ClearLookupTable clears the value of the "lookup_table" field.
func (_u *FieldMappingUpdate) ClearLookupTable() *FieldMappingUpdate {
	_u.mutation.ClearLookupTable()
	return _u
}

// SetLookupCaseSensitive sets the "lookup_case_sensitive" field.
func (_u *FieldMappingUpdate) SetLookupCaseSensitive(v bool) *FieldMappingUpdate {
	_u.mutation.SetLookupCaseSensitive(v)
	return _u
}

// SetNillableLookupCaseSensitive sets the "lookup_case_sensitive" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableLookupCaseSensitive(v *bool) *FieldMappingUpdate {
	if v != nil {
		_u.SetLookupCaseSensitive(*v)
	}
	return _u
}

// SetConditionRules sets the "condition_rules" field.
func (_u *FieldMappingUpdate) SetConditionRules(v string) *FieldMappingUpdate {
	_u.mutation.SetConditionRules(v)
	return _u
}

// SetNillableConditionRules sets the "condition_rules" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableConditionRules(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetConditionRules(*v)
	}
	return _u
}

// ClearConditionRules clears the value of the "condition_rules" field.
func (_u *FieldMappingUpdate) ClearConditionRules() *FieldMappingUpdate {
	_u.mutation.ClearConditionRules()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *FieldMappingUpdate) SetPriority(v int) *FieldMappingUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillablePriority(v *int) *FieldMappingUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *FieldMappingUpdate) AddPriority(v int) *FieldMappingUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *FieldMappingUpdate) SetSortOrder(v int) *FieldMappingUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableSortOrder(v *int) *FieldMappingUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *FieldMappingUpdate) AddSortOrder(v int) *FieldMappingUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetDiscoveryPoolID sets the "discovery_pool_id" field.
func (_u *FieldMappingUpdate) SetDiscoveryPoolID(v uint64) *FieldMappingUpdate {
	_u.mutation.ResetDiscoveryPoolID()
	_u.mutation.SetDiscoveryPoolID(v)
	return _u
}

// SetNillableDiscoveryPoolID sets the "discovery_pool_id" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableDiscoveryPoolID(v *uint64) *FieldMappingUpdate {
	if v != nil {
		_u.SetDiscoveryPoolID(*v)
	}
	return _u
}

// AddDiscoveryPoolID adds value to the "discovery_pool_id" field.
func (_u *FieldMappingUpdate) AddDiscoveryPoolID(v int64) *FieldMappingUpdate {
	_u.mutation.AddDiscoveryPoolID(v)
	return _u
}

// ClearDiscoveryPoolID clears the value of the "discovery_pool_id" field.
func (_u *FieldMappingUpdate) ClearDiscoveryPoolID() *FieldMappingUpdate {
	_u.mutation.ClearDiscoveryPoolID()
	return _u
}

// SetInputTaskID sets the "input_task_id" field.
func (_u *FieldMappingUpdate) SetInputTaskID(v uint64) *FieldMappingUpdate {
	_u.mutation.ResetInputTaskID()
	_u.mutation.SetInputTaskID(v)
	return _u
}

// SetNillableInputTaskID sets the "input_task_id" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableInputTaskID(v *uint64) *FieldMappingUpdate {
	if v != nil {
		_u.SetInputTaskID(*v)
	}
	return _u
}

// AddInputTaskID adds value to the "input_task_id" field.
func (_u *FieldMappingUpdate) AddInputTaskID(v int64) *FieldMappingUpdate {
	_u.mutation.AddInputTaskID(v)
	return _u
}

// ClearInputTaskID clears the value of the "input_task_id" field.
func (_u *FieldMappingUpdate) ClearInputTaskID() *FieldMappingUpdate {
	_u.mutation.ClearInputTaskID()
	return _u
}

// SetOutputTaskID sets the "output_task_id" field.
func (_u *FieldMappingUpdate) SetOutputTaskID(v uint64) *FieldMappingUpdate {
	_u.mutation.ResetOutputTaskID()
	_u.mutation.SetOutputTaskID(v)
	return _u
}

// SetNillableOutputTaskID sets the "output_task_id" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableOutputTaskID(v *uint64) *FieldMappingUpdate {
	if v != nil {
		_u.SetOutputTaskID(*v)
	}
	return _u
}

// AddOutputTaskID adds value to the "output_task_id" field.
func (_u *FieldMappingUpdate) AddOutputTaskID(v int64) *FieldMappingUpdate {
	_u.mutation.AddOutputTaskID(v)
	return _u
}

// ClearOutputTaskID clears the value of the "output_task_id" field.
func (_u *FieldMappingUpdate) ClearOutputTaskID() *FieldMappingUpdate {
	_u.mutation.ClearOutputTaskID()
	return _u
}

// SetUsageCount sets the "usage_count" field.
func (_u *FieldMappingUpdate) SetUsageCount(v int64) *FieldMappingUpdate {
	_u.mutation.ResetUsageCount()
	_u.mutation.SetUsageCount(v)
	return _u
}

// SetNillableUsageCount sets the "usage_count" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableUsageCount(v *int64) *FieldMappingUpdate {
	if v != nil {
		_u.SetUsageCount(*v)
	}
	return _u
}

// AddUsageCount adds value to the "usage_count" field.
func (_u *FieldMappingUpdate) AddUsageCount(v int64) *FieldMappingUpdate {
	_u.mutation.AddUsageCount(v)
	return _u
}

// SetSuccessCount sets the "success_count" field.
func (_u *FieldMappingUpdate) SetSuccessCount(v int64) *FieldMappingUpdate {
	_u.mutation.ResetSuccessCount()
	_u.mutation.SetSuccessCount(v)
	return _u
}

// SetNillableSuccessCount sets the "success_count" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableSuccessCount(v *int64) *FieldMappingUpdate {
	if v != nil {
		_u.SetSuccessCount(*v)
	}
	return _u
}

// AddSuccessCount adds value to the "success_count" field.
func (_u *FieldMappingUpdate) AddSuccessCount(v int64) *FieldMappingUpdate {
	_u.mutation.AddSuccessCount(v)
	return _u
}

// SetFailedCount sets the "failed_count" field.
func (_u *FieldMappingUpdate) SetFailedCount(v int64) *FieldMappingUpdate {
	_u.mutation.ResetFailedCount()
	_u.mutation.SetFailedCount(v)
	return _u
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableFailedCount(v *int64) *FieldMappingUpdate {
	if v != nil {
		_u.SetFailedCount(*v)
	}
	return _u
}

// AddFailedCount adds value to the "failed_count" field.
func (_u *FieldMappingUpdate) AddFailedCount(v int64) *FieldMappingUpdate {
	_u.mutation.AddFailedCount(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *FieldMappingUpdate) SetLastUsedAt(v time.Time) *FieldMappingUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableLastUsedAt(v *time.Time) *FieldMappingUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *FieldMappingUpdate) ClearLastUsedAt() *FieldMappingUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *FieldMappingUpdate) SetLastError(v string) *FieldMappingUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableLastError(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *FieldMappingUpdate) ClearLastError() *FieldMappingUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetLastErrorAt sets the "last_error_at" field.
func (_u *FieldMappingUpdate) SetLastErrorAt(v time.Time) *FieldMappingUpdate {
	_u.mutation.SetLastErrorAt(v)
	return _u
}

// SetNillableLastErrorAt sets the "last_error_at" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableLastErrorAt(v *time.Time) *FieldMappingUpdate {
	if v != nil {
		_u.SetLastErrorAt(*v)
	}
	return _u
}

// ClearLastErrorAt clears the value of the "last_error_at" field.
func (_u *FieldMappingUpdate) ClearLastErrorAt() *FieldMappingUpdate {
	_u.mutation.ClearLastErrorAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *FieldMappingUpdate) SetMetadata(v string) *FieldMappingUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *FieldMappingUpdate) SetNillableMetadata(v *string) *FieldMappingUpdate {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *FieldMappingUpdate) ClearMetadata() *FieldMappingUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// Mutation returns the FieldMappingMutation object of the builder.
func (_u *FieldMappingUpdate) Mutation() *FieldMappingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FieldMappingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FieldMappingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FieldMappingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FieldMappingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FieldMappingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := fieldmapping.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FieldMappingUpdate) check() error {
	if v, ok := _u.mutation.MappingName(); ok {
		if err := fieldmapping.MappingNameValidator(v); err != nil {
			return &ValidationError{Name: "mapping_name", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.mapping_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := fieldmapping.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MappingType(); ok {
		if err := fieldmapping.MappingTypeValidator(v); err != nil {
			return &ValidationError{Name: "mapping_type", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.mapping_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceField(); ok {
		if err := fieldmapping.SourceFieldValidator(v); err != nil {
			return &ValidationError{Name: "source_field", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.source_field": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceFieldPath(); ok {
		if err := fieldmapping.SourceFieldPathValidator(v); err != nil {
			return &ValidationError{Name: "source_field_path", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.source_field_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceDataType(); ok {
		if err := fieldmapping.SourceDataTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_data_type", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.source_data_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceFormat(); ok {
		if err := fieldmapping.SourceFormatValidator(v); err != nil {
			return &ValidationError{Name: "source_format", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.source_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetField(); ok {
		if err := fieldmapping.TargetFieldValidator(v); err != nil {
			return &ValidationError{Name: "target_field", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.target_field": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetFieldPath(); ok {
		if err := fieldmapping.TargetFieldPathValidator(v); err != nil {
			return &ValidationError{Name: "target_field_path", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.target_field_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetDataType(); ok {
		if err := fieldmapping.TargetDataTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_data_type", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.target_data_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetFormat(); ok {
		if err := fieldmapping.TargetFormatValidator(v); err != nil {
			return &ValidationError{Name: "target_format", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.target_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TransformType(); ok {
		if err := fieldmapping.TransformTypeValidator(v); err != nil {
			return &ValidationError{Name: "transform_type", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.transform_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultValue(); ok {
		if err := fieldmapping.DefaultValueValidator(v); err != nil {
			return &ValidationError{Name: "default_value", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.default_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValidationRegex(); ok {
		if err := fieldmapping.ValidationRegexValidator(v); err != nil {
			return &ValidationError{Name: "validation_regex", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.validation_regex": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *FieldMappingUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *FieldMappingUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *FieldMappingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fieldmapping.Table, fieldmapping.Columns, sqlgraph.NewFieldSpec(fieldmapping.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fieldmapping.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(fieldmapping.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(fieldmapping.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(fieldmapping.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.MappingName(); ok {
		_spec.SetField(fieldmapping.FieldMappingName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(fieldmapping.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(fieldmapping.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.MappingType(); ok {
		_spec.SetField(fieldmapping.FieldMappingType, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(fieldmapping.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SourceField(); ok {
		_spec.SetField(fieldmapping.FieldSourceField, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceFieldPath(); ok {
		_spec.SetField(fieldmapping.FieldSourceFieldPath, field.TypeString, value)
	}
	if _u.mutation.SourceFieldPathCleared() {
		_spec.ClearField(fieldmapping.FieldSourceFieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.SourceDataType(); ok {
		_spec.SetField(fieldmapping.FieldSourceDataType, field.TypeString, value)
	}
	if _u.mutation.SourceDataTypeCleared() {
		_spec.ClearField(fieldmapping.FieldSourceDataType, field.TypeString)
	}
	if value, ok := _u.mutation.SourceFormat(); ok {
		_spec.SetField(fieldmapping.FieldSourceFormat, field.TypeString, value)
	}
	if _u.mutation.SourceFormatCleared() {
		_spec.ClearField(fieldmapping.FieldSourceFormat, field.TypeString)
	}
	if value, ok := _u.mutation.TargetField(); ok {
		_spec.SetField(fieldmapping.FieldTargetField, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetFieldPath(); ok {
		_spec.SetField(fieldmapping.FieldTargetFieldPath, field.TypeString, value)
	}
	if _u.mutation.TargetFieldPathCleared() {
		_spec.ClearField(fieldmapping.FieldTargetFieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.TargetDataType(); ok {
		_spec.SetField(fieldmapping.FieldTargetDataType, field.TypeString, value)
	}
	if _u.mutation.TargetDataTypeCleared() {
		_spec.ClearField(fieldmapping.FieldTargetDataType, field.TypeString)
	}
	if value, ok := _u.mutation.TargetFormat(); ok {
		_spec.SetField(fieldmapping.FieldTargetFormat, field.TypeString, value)
	}
	if _u.mutation.TargetFormatCleared() {
		_spec.ClearField(fieldmapping.FieldTargetFormat, field.TypeString)
	}
	if value, ok := _u.mutation.TransformType(); ok {
		_spec.SetField(fieldmapping.FieldTransformType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TransformConfig(); ok {
		_spec.SetField(fieldmapping.FieldTransformConfig, field.TypeString, value)
	}
	if _u.mutation.TransformConfigCleared() {
		_spec.ClearField(fieldmapping.FieldTransformConfig, field.TypeString)
	}
	if value, ok := _u.mutation.DefaultValue(); ok {
		_spec.SetField(fieldmapping.FieldDefaultValue, field.TypeString, value)
	}
	if _u.mutation.DefaultValueCleared() {
		_spec.ClearField(fieldmapping.FieldDefaultValue, field.TypeString)
	}
	if value, ok := _u.mutation.AllowNull(); ok {
		_spec.SetField(fieldmapping.FieldAllowNull, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsRequired(); ok {
		_spec.SetField(fieldmapping.FieldIsRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ValidationRules(); ok {
		_spec.SetField(fieldmapping.FieldValidationRules, field.TypeString, value)
	}
	if _u.mutation.ValidationRulesCleared() {
		_spec.ClearField(fieldmapping.FieldValidationRules, field.TypeString)
	}
	if value, ok := _u.mutation.ValidationRegex(); ok {
		_spec.SetField(fieldmapping.FieldValidationRegex, field.TypeString, value)
	}
	if _u.mutation.ValidationRegexCleared() {
		_spec.ClearField(fieldmapping.FieldValidationRegex, field.TypeString)
	}
	if value, ok := _u.mutation.LookupTable(); ok {
		_spec.SetField(fieldmapping.FieldLookupTable, field.TypeString, value)
	}
	if _u.mutation.LookupTableCleared() {
		_spec.ClearField(fieldmapping.FieldLookupTable, field.TypeString)
	}
	if value, ok := _u.mutation.LookupCaseSensitive(); ok {
		_spec.SetField(fieldmapping.FieldLookupCaseSensitive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConditionRules(); ok {
		_spec.SetField(fieldmapping.FieldConditionRules, field.TypeString, value)
	}
	if _u.mutation.ConditionRulesCleared() {
		_spec.ClearField(fieldmapping.FieldConditionRules, field.TypeString)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(fieldmapping.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(fieldmapping.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(fieldmapping.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(fieldmapping.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DiscoveryPoolID(); ok {
		_spec.SetField(fieldmapping.FieldDiscoveryPoolID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDiscoveryPoolID(); ok {
		_spec.AddField(fieldmapping.FieldDiscoveryPoolID, field.TypeUint64, value)
	}
	if _u.mutation.DiscoveryPoolIDCleared() {
		_spec.ClearField(fieldmapping.FieldDiscoveryPoolID, field.TypeUint64)
	}
	if value, ok := _u.mutation.InputTaskID(); ok {
		_spec.SetField(fieldmapping.FieldInputTaskID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedInputTaskID(); ok {
		_spec.AddField(fieldmapping.FieldInputTaskID, field.TypeUint64, value)
	}
	if _u.mutation.InputTaskIDCleared() {
		_spec.ClearField(fieldmapping.FieldInputTaskID, field.TypeUint64)
	}
	if value, ok := _u.mutation.OutputTaskID(); ok {
		_spec.SetField(fieldmapping.FieldOutputTaskID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedOutputTaskID(); ok {
		_spec.AddField(fieldmapping.FieldOutputTaskID, field.TypeUint64, value)
	}
	if _u.mutation.OutputTaskIDCleared() {
		_spec.ClearField(fieldmapping.FieldOutputTaskID, field.TypeUint64)
	}
	if value, ok := _u.mutation.UsageCount(); ok {
		_spec.SetField(fieldmapping.FieldUsageCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageCount(); ok {
		_spec.AddField(fieldmapping.FieldUsageCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SuccessCount(); ok {
		_spec.SetField(fieldmapping.FieldSuccessCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSuccessCount(); ok {
		_spec.AddField(fieldmapping.FieldSuccessCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FailedCount(); ok {
		_spec.SetField(fieldmapping.FieldFailedCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFailedCount(); ok {
		_spec.AddField(fieldmapping.FieldFailedCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(fieldmapping.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(fieldmapping.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(fieldmapping.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(fieldmapping.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorAt(); ok {
		_spec.SetField(fieldmapping.FieldLastErrorAt, field.TypeTime, value)
	}
	if _u.mutation.LastErrorAtCleared() {
		_spec.ClearField(fieldmapping.FieldLastErrorAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(fieldmapping.FieldMetadata, field.TypeString, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(fieldmapping.FieldMetadata, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fieldmapping.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FieldMappingUpdateOne is the builder for updating a single FieldMapping entity.
type FieldMappingUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *FieldMappingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FieldMappingUpdateOne) SetUpdatedAt(v time.Time) *FieldMappingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *FieldMappingUpdateOne) SetStatus(v uint8) *FieldMappingUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableStatus(v *uint8) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *FieldMappingUpdateOne) AddStatus(v int8) *FieldMappingUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *FieldMappingUpdateOne) ClearStatus() *FieldMappingUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetMappingName sets the "mapping_name" field.
func (_u *FieldMappingUpdateOne) SetMappingName(v string) *FieldMappingUpdateOne {
	_u.mutation.SetMappingName(v)
	return _u
}

// SetNillableMappingName sets the "mapping_name" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableMappingName(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetMappingName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *FieldMappingUpdateOne) SetDescription(v string) *FieldMappingUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableDescription(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FieldMappingUpdateOne) ClearDescription() *FieldMappingUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetMappingType sets the "mapping_type" field.
func (_u *FieldMappingUpdateOne) SetMappingType(v string) *FieldMappingUpdateOne {
	_u.mutation.SetMappingType(v)
	return _u
}

// SetNillableMappingType sets the "mapping_type" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableMappingType(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetMappingType(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *FieldMappingUpdateOne) SetIsActive(v bool) *FieldMappingUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableIsActive(v *bool) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetSourceField sets the "source_field" field.
func (_u *FieldMappingUpdateOne) SetSourceField(v string) *FieldMappingUpdateOne {
	_u.mutation.SetSourceField(v)
	return _u
}

// SetNillableSourceField sets the "source_field" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableSourceField(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetSourceField(*v)
	}
	return _u
}

// SetSourceFieldPath sets the "source_field_path" field.
func (_u *FieldMappingUpdateOne) SetSourceFieldPath(v string) *FieldMappingUpdateOne {
	_u.mutation.SetSourceFieldPath(v)
	return _u
}

// SetNillableSourceFieldPath sets the "source_field_path" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableSourceFieldPath(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetSourceFieldPath(*v)
	}
	return _u
}

// ClearSourceFieldPath clears the value of the "source_field_path" field.
func (_u *FieldMappingUpdateOne) ClearSourceFieldPath() *FieldMappingUpdateOne {
	_u.mutation.ClearSourceFieldPath()
	return _u
}

// SetSourceDataType sets the "source_data_type" field.
func (_u *FieldMappingUpdateOne) SetSourceDataType(v string) *FieldMappingUpdateOne {
	_u.mutation.SetSourceDataType(v)
	return _u
}

// SetNillableSourceDataType sets the "source_data_type" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableSourceDataType(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetSourceDataType(*v)
	}
	return _u
}

// ClearSourceDataType clears the value of the "source_data_type" field.
func (_u *FieldMappingUpdateOne) ClearSourceDataType() *FieldMappingUpdateOne {
	_u.mutation.ClearSourceDataType()
	return _u
}

// SetSourceFormat sets the "source_format" field.
func (_u *FieldMappingUpdateOne) SetSourceFormat(v string) *FieldMappingUpdateOne {
	_u.mutation.SetSourceFormat(v)
	return _u
}

// SetNillableSourceFormat sets the "source_format" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableSourceFormat(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetSourceFormat(*v)
	}
	return _u
}

// ClearSourceFormat clears the value of the "source_format" field.
func (_u *FieldMappingUpdateOne) ClearSourceFormat() *FieldMappingUpdateOne {
	_u.mutation.ClearSourceFormat()
	return _u
}

// SetTargetField sets the "target_field" field.
func (_u *FieldMappingUpdateOne) SetTargetField(v string) *FieldMappingUpdateOne {
	_u.mutation.SetTargetField(v)
	return _u
}

// SetNillableTargetField sets the "target_field" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableTargetField(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetTargetField(*v)
	}
	return _u
}

// SetTargetFieldPath sets the "target_field_path" field.
func (_u *FieldMappingUpdateOne) SetTargetFieldPath(v string) *FieldMappingUpdateOne {
	_u.mutation.SetTargetFieldPath(v)
	return _u
}

// SetNillableTargetFieldPath sets the "target_field_path" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableTargetFieldPath(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetTargetFieldPath(*v)
	}
	return _u
}

// ClearTargetFieldPath clears the value of the "target_field_path" field.
func (_u *FieldMappingUpdateOne) ClearTargetFieldPath() *FieldMappingUpdateOne {
	_u.mutation.ClearTargetFieldPath()
	return _u
}

// SetTargetDataType sets the "target_data_type" field.
func (_u *FieldMappingUpdateOne) SetTargetDataType(v string) *FieldMappingUpdateOne {
	_u.mutation.SetTargetDataType(v)
	return _u
}

// SetNillableTargetDataType sets the "target_data_type" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableTargetDataType(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetTargetDataType(*v)
	}
	return _u
}

// ClearTargetDataType clears the value of the "target_data_type" field.
func (_u *FieldMappingUpdateOne) ClearTargetDataType() *FieldMappingUpdateOne {
	_u.mutation.ClearTargetDataType()
	return _u
}

// SetTargetFormat sets the "target_format" field.
func (_u *FieldMappingUpdateOne) SetTargetFormat(v string) *FieldMappingUpdateOne {
	_u.mutation.SetTargetFormat(v)
	return _u
}

// SetNillableTargetFormat sets the "target_format" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableTargetFormat(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetTargetFormat(*v)
	}
	return _u
}

// ClearTargetFormat clears the value of the "target_format" field.
func (_u *FieldMappingUpdateOne) ClearTargetFormat() *FieldMappingUpdateOne {
	_u.mutation.ClearTargetFormat()
	return _u
}

// SetTransformType sets the "transform_type" field.
func (_u *FieldMappingUpdateOne) SetTransformType(v string) *FieldMappingUpdateOne {
	_u.mutation.SetTransformType(v)
	return _u
}

// SetNillableTransformType sets the "transform_type" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableTransformType(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetTransformType(*v)
	}
	return _u
}

// SetTransformConfig sets the "transform_config" field.
func (_u *FieldMappingUpdateOne) SetTransformConfig(v string) *FieldMappingUpdateOne {
	_u.mutation.SetTransformConfig(v)
	return _u
}

// SetNillableTransformConfig sets the "transform_config" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableTransformConfig(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetTransformConfig(*v)
	}
	return _u
}

// ClearTransformConfig clears the value of the "transform_config" field.
func (_u *FieldMappingUpdateOne) ClearTransformConfig() *FieldMappingUpdateOne {
	_u.mutation.ClearTransformConfig()
	return _u
}

// SetDefaultValue sets the "default_value" field.
func (_u *FieldMappingUpdateOne) SetDefaultValue(v string) *FieldMappingUpdateOne {
	_u.mutation.SetDefaultValue(v)
	return _u
}

// SetNillableDefaultValue sets the "default_value" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableDefaultValue(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetDefaultValue(*v)
	}
	return _u
}

// ClearDefaultValue clears the value of the "default_value" field.
func (_u *FieldMappingUpdateOne) ClearDefaultValue() *FieldMappingUpdateOne {
	_u.mutation.ClearDefaultValue()
	return _u
}

// SetAllowNull sets the "allow_null" field.
func (_u *FieldMappingUpdateOne) SetAllowNull(v bool) *FieldMappingUpdateOne {
	_u.mutation.SetAllowNull(v)
	return _u
}

// SetNillableAllowNull sets the "allow_null" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableAllowNull(v *bool) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetAllowNull(*v)
	}
	return _u
}

// SetIsRequired sets the "is_required" field.
func (_u *FieldMappingUpdateOne) SetIsRequired(v bool) *FieldMappingUpdateOne {
	_u.mutation.SetIsRequired(v)
	return _u
}

// SetNillableIsRequired sets the "is_required" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableIsRequired(v *bool) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetIsRequired(*v)
	}
	return _u
}

// SetValidationRules sets the "validation_rules" field.
func (_u *FieldMappingUpdateOne) SetValidationRules(v string) *FieldMappingUpdateOne {
	_u.mutation.SetValidationRules(v)
	return _u
}

// SetNillableValidationRules sets the "validation_rules" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableValidationRules(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetValidationRules(*v)
	}
	return _u
}

// ClearValidationRules clears the value of the "validation_rules" field.
func (_u *FieldMappingUpdateOne) ClearValidationRules() *FieldMappingUpdateOne {
	_u.mutation.ClearValidationRules()
	return _u
}

// SetValidationRegex sets the "validation_regex" field.
func (_u *FieldMappingUpdateOne) SetValidationRegex(v string) *FieldMappingUpdateOne {
	_u.mutation.SetValidationRegex(v)
	return _u
}

// SetNillableValidationRegex sets the "validation_regex" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableValidationRegex(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetValidationRegex(*v)
	}
	return _u
}

// ClearValidationRegex clears the value of the "validation_regex" field.
func (_u *FieldMappingUpdateOne) ClearValidationRegex() *FieldMappingUpdateOne {
	_u.mutation.ClearValidationRegex()
	return _u
}

// SetLookupTable sets the "lookup_table" field.
func (_u *FieldMappingUpdateOne) SetLookupTable(v string) *FieldMappingUpdateOne {
	_u.mutation.SetLookupTable(v)
	return _u
}

// SetNillableLookupTable sets the "lookup_table" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableLookupTable(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetLookupTable(*v)
	}
	return _u
}

// ClearLookupTable clears the value of the "lookup_table" field.
func (_u *FieldMappingUpdateOne) ClearLookupTable() *FieldMappingUpdateOne {
	_u.mutation.ClearLookupTable()
	return _u
}

// SetLookupCaseSensitive sets the "lookup_case_sensitive" field.
func (_u *FieldMappingUpdateOne) SetLookupCaseSensitive(v bool) *FieldMappingUpdateOne {
	_u.mutation.SetLookupCaseSensitive(v)
	return _u
}

// SetNillableLookupCaseSensitive sets the "lookup_case_sensitive" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableLookupCaseSensitive(v *bool) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetLookupCaseSensitive(*v)
	}
	return _u
}

// SetConditionRules sets the "condition_rules" field.
func (_u *FieldMappingUpdateOne) SetConditionRules(v string) *FieldMappingUpdateOne {
	_u.mutation.SetConditionRules(v)
	return _u
}

// SetNillableConditionRules sets the "condition_rules" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableConditionRules(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetConditionRules(*v)
	}
	return _u
}

// ClearConditionRules clears the value of the "condition_rules" field.
func (_u *FieldMappingUpdateOne) ClearConditionRules() *FieldMappingUpdateOne {
	_u.mutation.ClearConditionRules()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *FieldMappingUpdateOne) SetPriority(v int) *FieldMappingUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillablePriority(v *int) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *FieldMappingUpdateOne) AddPriority(v int) *FieldMappingUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *FieldMappingUpdateOne) SetSortOrder(v int) *FieldMappingUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableSortOrder(v *int) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *FieldMappingUpdateOne) AddSortOrder(v int) *FieldMappingUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetDiscoveryPoolID sets the "discovery_pool_id" field.
func (_u *FieldMappingUpdateOne) SetDiscoveryPoolID(v uint64) *FieldMappingUpdateOne {
	_u.mutation.ResetDiscoveryPoolID()
	_u.mutation.SetDiscoveryPoolID(v)
	return _u
}

// SetNillableDiscoveryPoolID sets the "discovery_pool_id" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableDiscoveryPoolID(v *uint64) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetDiscoveryPoolID(*v)
	}
	return _u
}

// AddDiscoveryPoolID adds value to the "discovery_pool_id" field.
func (_u *FieldMappingUpdateOne) AddDiscoveryPoolID(v int64) *FieldMappingUpdateOne {
	_u.mutation.AddDiscoveryPoolID(v)
	return _u
}

// ClearDiscoveryPoolID clears the value of the "discovery_pool_id" field.
func (_u *FieldMappingUpdateOne) ClearDiscoveryPoolID() *FieldMappingUpdateOne {
	_u.mutation.ClearDiscoveryPoolID()
	return _u
}

// SetInputTaskID sets the "input_task_id" field.
func (_u *FieldMappingUpdateOne) SetInputTaskID(v uint64) *FieldMappingUpdateOne {
	_u.mutation.ResetInputTaskID()
	_u.mutation.SetInputTaskID(v)
	return _u
}

// SetNillableInputTaskID sets the "input_task_id" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableInputTaskID(v *uint64) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetInputTaskID(*v)
	}
	return _u
}

// AddInputTaskID adds value to the "input_task_id" field.
func (_u *FieldMappingUpdateOne) AddInputTaskID(v int64) *FieldMappingUpdateOne {
	_u.mutation.AddInputTaskID(v)
	return _u
}

// ClearInputTaskID clears the value of the "input_task_id" field.
func (_u *FieldMappingUpdateOne) ClearInputTaskID() *FieldMappingUpdateOne {
	_u.mutation.ClearInputTaskID()
	return _u
}

// SetOutputTaskID sets the "output_task_id" field.
func (_u *FieldMappingUpdateOne) SetOutputTaskID(v uint64) *FieldMappingUpdateOne {
	_u.mutation.ResetOutputTaskID()
	_u.mutation.SetOutputTaskID(v)
	return _u
}

// SetNillableOutputTaskID sets the "output_task_id" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableOutputTaskID(v *uint64) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetOutputTaskID(*v)
	}
	return _u
}

// AddOutputTaskID adds value to the "output_task_id" field.
func (_u *FieldMappingUpdateOne) AddOutputTaskID(v int64) *FieldMappingUpdateOne {
	_u.mutation.AddOutputTaskID(v)
	return _u
}

// ClearOutputTaskID clears the value of the "output_task_id" field.
func (_u *FieldMappingUpdateOne) ClearOutputTaskID() *FieldMappingUpdateOne {
	_u.mutation.ClearOutputTaskID()
	return _u
}

// SetUsageCount sets the "usage_count" field.
func (_u *FieldMappingUpdateOne) SetUsageCount(v int64) *FieldMappingUpdateOne {
	_u.mutation.ResetUsageCount()
	_u.mutation.SetUsageCount(v)
	return _u
}

// SetNillableUsageCount sets the "usage_count" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableUsageCount(v *int64) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetUsageCount(*v)
	}
	return _u
}

// AddUsageCount adds value to the "usage_count" field.
func (_u *FieldMappingUpdateOne) AddUsageCount(v int64) *FieldMappingUpdateOne {
	_u.mutation.AddUsageCount(v)
	return _u
}

// SetSuccessCount sets the "success_count" field.
func (_u *FieldMappingUpdateOne) SetSuccessCount(v int64) *FieldMappingUpdateOne {
	_u.mutation.ResetSuccessCount()
	_u.mutation.SetSuccessCount(v)
	return _u
}

// SetNillableSuccessCount sets the "success_count" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableSuccessCount(v *int64) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetSuccessCount(*v)
	}
	return _u
}

// AddSuccessCount adds value to the "success_count" field.
func (_u *FieldMappingUpdateOne) AddSuccessCount(v int64) *FieldMappingUpdateOne {
	_u.mutation.AddSuccessCount(v)
	return _u
}

// SetFailedCount sets the "failed_count" field.
func (_u *FieldMappingUpdateOne) SetFailedCount(v int64) *FieldMappingUpdateOne {
	_u.mutation.ResetFailedCount()
	_u.mutation.SetFailedCount(v)
	return _u
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableFailedCount(v *int64) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetFailedCount(*v)
	}
	return _u
}

// AddFailedCount adds value to the "failed_count" field.
func (_u *FieldMappingUpdateOne) AddFailedCount(v int64) *FieldMappingUpdateOne {
	_u.mutation.AddFailedCount(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *FieldMappingUpdateOne) SetLastUsedAt(v time.Time) *FieldMappingUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableLastUsedAt(v *time.Time) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *FieldMappingUpdateOne) ClearLastUsedAt() *FieldMappingUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *FieldMappingUpdateOne) SetLastError(v string) *FieldMappingUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableLastError(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *FieldMappingUpdateOne) ClearLastError() *FieldMappingUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetLastErrorAt sets the "last_error_at" field.
func (_u *FieldMappingUpdateOne) SetLastErrorAt(v time.Time) *FieldMappingUpdateOne {
	_u.mutation.SetLastErrorAt(v)
	return _u
}

// SetNillableLastErrorAt sets the "last_error_at" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableLastErrorAt(v *time.Time) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetLastErrorAt(*v)
	}
	return _u
}

// ClearLastErrorAt clears the value of the "last_error_at" field.
func (_u *FieldMappingUpdateOne) ClearLastErrorAt() *FieldMappingUpdateOne {
	_u.mutation.ClearLastErrorAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *FieldMappingUpdateOne) SetMetadata(v string) *FieldMappingUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *FieldMappingUpdateOne) SetNillableMetadata(v *string) *FieldMappingUpdateOne {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *FieldMappingUpdateOne) ClearMetadata() *FieldMappingUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// Mutation returns the FieldMappingMutation object of the builder.
func (_u *FieldMappingUpdateOne) Mutation() *FieldMappingMutation {
	return _u.mutation
}

// Where appends a list predicates to the FieldMappingUpdate builder.
func (_u *FieldMappingUpdateOne) Where(ps ...predicate.FieldMapping) *FieldMappingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FieldMappingUpdateOne) Select(field string, fields ...string) *FieldMappingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FieldMapping entity.
func (_u *FieldMappingUpdateOne) Save(ctx context.Context) (*FieldMapping, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FieldMappingUpdateOne) SaveX(ctx context.Context) *FieldMapping {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FieldMappingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FieldMappingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FieldMappingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := fieldmapping.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FieldMappingUpdateOne) check() error {
	if v, ok := _u.mutation.MappingName(); ok {
		if err := fieldmapping.MappingNameValidator(v); err != nil {
			return &ValidationError{Name: "mapping_name", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.mapping_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := fieldmapping.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MappingType(); ok {
		if err := fieldmapping.MappingTypeValidator(v); err != nil {
			return &ValidationError{Name: "mapping_type", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.mapping_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceField(); ok {
		if err := fieldmapping.SourceFieldValidator(v); err != nil {
			return &ValidationError{Name: "source_field", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.source_field": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceFieldPath(); ok {
		if err := fieldmapping.SourceFieldPathValidator(v); err != nil {
			return &ValidationError{Name: "source_field_path", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.source_field_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceDataType(); ok {
		if err := fieldmapping.SourceDataTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_data_type", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.source_data_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceFormat(); ok {
		if err := fieldmapping.SourceFormatValidator(v); err != nil {
			return &ValidationError{Name: "source_format", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.source_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetField(); ok {
		if err := fieldmapping.TargetFieldValidator(v); err != nil {
			return &ValidationError{Name: "target_field", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.target_field": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetFieldPath(); ok {
		if err := fieldmapping.TargetFieldPathValidator(v); err != nil {
			return &ValidationError{Name: "target_field_path", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.target_field_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetDataType(); ok {
		if err := fieldmapping.TargetDataTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_data_type", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.target_data_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetFormat(); ok {
		if err := fieldmapping.TargetFormatValidator(v); err != nil {
			return &ValidationError{Name: "target_format", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.target_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TransformType(); ok {
		if err := fieldmapping.TransformTypeValidator(v); err != nil {
			return &ValidationError{Name: "transform_type", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.transform_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultValue(); ok {
		if err := fieldmapping.DefaultValueValidator(v); err != nil {
			return &ValidationError{Name: "default_value", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.default_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValidationRegex(); ok {
		if err := fieldmapping.ValidationRegexValidator(v); err != nil {
			return &ValidationError{Name: "validation_regex", err: fmt.Errorf(`ent: validator failed for field "FieldMapping.validation_regex": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *FieldMappingUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *FieldMappingUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *FieldMappingUpdateOne) sqlSave(ctx context.Context) (_node *FieldMapping, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fieldmapping.Table, fieldmapping.Columns, sqlgraph.NewFieldSpec(fieldmapping.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FieldMapping.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fieldmapping.FieldID)
		for _, f := range fields {
			if !fieldmapping.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fieldmapping.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fieldmapping.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(fieldmapping.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(fieldmapping.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(fieldmapping.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.MappingName(); ok {
		_spec.SetField(fieldmapping.FieldMappingName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(fieldmapping.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(fieldmapping.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.MappingType(); ok {
		_spec.SetField(fieldmapping.FieldMappingType, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(fieldmapping.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SourceField(); ok {
		_spec.SetField(fieldmapping.FieldSourceField, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceFieldPath(); ok {
		_spec.SetField(fieldmapping.FieldSourceFieldPath, field.TypeString, value)
	}
	if _u.mutation.SourceFieldPathCleared() {
		_spec.ClearField(fieldmapping.FieldSourceFieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.SourceDataType(); ok {
		_spec.SetField(fieldmapping.FieldSourceDataType, field.TypeString, value)
	}
	if _u.mutation.SourceDataTypeCleared() {
		_spec.ClearField(fieldmapping.FieldSourceDataType, field.TypeString)
	}
	if value, ok := _u.mutation.SourceFormat(); ok {
		_spec.SetField(fieldmapping.FieldSourceFormat, field.TypeString, value)
	}
	if _u.mutation.SourceFormatCleared() {
		_spec.ClearField(fieldmapping.FieldSourceFormat, field.TypeString)
	}
	if value, ok := _u.mutation.TargetField(); ok {
		_spec.SetField(fieldmapping.FieldTargetField, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetFieldPath(); ok {
		_spec.SetField(fieldmapping.FieldTargetFieldPath, field.TypeString, value)
	}
	if _u.mutation.TargetFieldPathCleared() {
		_spec.ClearField(fieldmapping.FieldTargetFieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.TargetDataType(); ok {
		_spec.SetField(fieldmapping.FieldTargetDataType, field.TypeString, value)
	}
	if _u.mutation.TargetDataTypeCleared() {
		_spec.ClearField(fieldmapping.FieldTargetDataType, field.TypeString)
	}
	if value, ok := _u.mutation.TargetFormat(); ok {
		_spec.SetField(fieldmapping.FieldTargetFormat, field.TypeString, value)
	}
	if _u.mutation.TargetFormatCleared() {
		_spec.ClearField(fieldmapping.FieldTargetFormat, field.TypeString)
	}
	if value, ok := _u.mutation.TransformType(); ok {
		_spec.SetField(fieldmapping.FieldTransformType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TransformConfig(); ok {
		_spec.SetField(fieldmapping.FieldTransformConfig, field.TypeString, value)
	}
	if _u.mutation.TransformConfigCleared() {
		_spec.ClearField(fieldmapping.FieldTransformConfig, field.TypeString)
	}
	if value, ok := _u.mutation.DefaultValue(); ok {
		_spec.SetField(fieldmapping.FieldDefaultValue, field.TypeString, value)
	}
	if _u.mutation.DefaultValueCleared() {
		_spec.ClearField(fieldmapping.FieldDefaultValue, field.TypeString)
	}
	if value, ok := _u.mutation.AllowNull(); ok {
		_spec.SetField(fieldmapping.FieldAllowNull, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsRequired(); ok {
		_spec.SetField(fieldmapping.FieldIsRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ValidationRules(); ok {
		_spec.SetField(fieldmapping.FieldValidationRules, field.TypeString, value)
	}
	if _u.mutation.ValidationRulesCleared() {
		_spec.ClearField(fieldmapping.FieldValidationRules, field.TypeString)
	}
	if value, ok := _u.mutation.ValidationRegex(); ok {
		_spec.SetField(fieldmapping.FieldValidationRegex, field.TypeString, value)
	}
	if _u.mutation.ValidationRegexCleared() {
		_spec.ClearField(fieldmapping.FieldValidationRegex, field.TypeString)
	}
	if value, ok := _u.mutation.LookupTable(); ok {
		_spec.SetField(fieldmapping.FieldLookupTable, field.TypeString, value)
	}
	if _u.mutation.LookupTableCleared() {
		_spec.ClearField(fieldmapping.FieldLookupTable, field.TypeString)
	}
	if value, ok := _u.mutation.LookupCaseSensitive(); ok {
		_spec.SetField(fieldmapping.FieldLookupCaseSensitive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConditionRules(); ok {
		_spec.SetField(fieldmapping.FieldConditionRules, field.TypeString, value)
	}
	if _u.mutation.ConditionRulesCleared() {
		_spec.ClearField(fieldmapping.FieldConditionRules, field.TypeString)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(fieldmapping.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(fieldmapping.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(fieldmapping.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(fieldmapping.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DiscoveryPoolID(); ok {
		_spec.SetField(fieldmapping.FieldDiscoveryPoolID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDiscoveryPoolID(); ok {
		_spec.AddField(fieldmapping.FieldDiscoveryPoolID, field.TypeUint64, value)
	}
	if _u.mutation.DiscoveryPoolIDCleared() {
		_spec.ClearField(fieldmapping.FieldDiscoveryPoolID, field.TypeUint64)
	}
	if value, ok := _u.mutation.InputTaskID(); ok {
		_spec.SetField(fieldmapping.FieldInputTaskID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedInputTaskID(); ok {
		_spec.AddField(fieldmapping.FieldInputTaskID, field.TypeUint64, value)
	}
	if _u.mutation.InputTaskIDCleared() {
		_spec.ClearField(fieldmapping.FieldInputTaskID, field.TypeUint64)
	}
	if value, ok := _u.mutation.OutputTaskID(); ok {
		_spec.SetField(fieldmapping.FieldOutputTaskID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedOutputTaskID(); ok {
		_spec.AddField(fieldmapping.FieldOutputTaskID, field.TypeUint64, value)
	}
	if _u.mutation.OutputTaskIDCleared() {
		_spec.ClearField(fieldmapping.FieldOutputTaskID, field.TypeUint64)
	}
	if value, ok := _u.mutation.UsageCount(); ok {
		_spec.SetField(fieldmapping.FieldUsageCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageCount(); ok {
		_spec.AddField(fieldmapping.FieldUsageCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SuccessCount(); ok {
		_spec.SetField(fieldmapping.FieldSuccessCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSuccessCount(); ok {
		_spec.AddField(fieldmapping.FieldSuccessCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FailedCount(); ok {
		_spec.SetField(fieldmapping.FieldFailedCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFailedCount(); ok {
		_spec.AddField(fieldmapping.FieldFailedCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(fieldmapping.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(fieldmapping.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(fieldmapping.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(fieldmapping.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorAt(); ok {
		_spec.SetField(fieldmapping.FieldLastErrorAt, field.TypeTime, value)
	}
	if _u.mutation.LastErrorAtCleared() {
		_spec.ClearField(fieldmapping.FieldLastErrorAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(fieldmapping.FieldMetadata, field.TypeString, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(fieldmapping.FieldMetadata, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &FieldMapping{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fieldmapping.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
