// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-io-rpc/ent/outboxmessage"
	"github.com/coder-lulu/newbee-io-rpc/ent/predicate"
)

// OutboxMessageUpdate is the builder for updating OutboxMessage entities.
type OutboxMessageUpdate struct {
	config
	hooks     []Hook
	mutation  *OutboxMessageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the OutboxMessageUpdate builder.
func (_u *OutboxMessageUpdate) Where(ps ...predicate.OutboxMessage) *OutboxMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OutboxMessageUpdate) SetUpdatedAt(v time.Time) *OutboxMessageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *OutboxMessageUpdate) SetStatus(v uint8) *OutboxMessageUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OutboxMessageUpdate) SetNillableStatus(v *uint8) *OutboxMessageUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *OutboxMessageUpdate) AddStatus(v int8) *OutboxMessageUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *OutboxMessageUpdate) ClearStatus() *OutboxMessageUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetAggregateType sets the "aggregate_type" field.
func (_u *OutboxMessageUpdate) SetAggregateType(v string) *OutboxMessageUpdate {
	_u.mutation.SetAggregateType(v)
	return _u
}

// SetNillableAggregateType sets the "aggregate_type" field if the given value is not nil.
func (_u *OutboxMessageUpdate) SetNillableAggregateType(v *string) *OutboxMessageUpdate {
	if v != nil {
		_u.SetAggregateType(*v)
	}
	return _u
}

// SetAggregateID sets the "aggregate_id" field.
func (_u *OutboxMessageUpdate) SetAggregateID(v string) *OutboxMessageUpdate {
	_u.mutation.SetAggregateID(v)
	return _u
}

// SetNillableAggregateID sets the "aggregate_id" field if the given value is not nil.
func (_u *OutboxMessageUpdate) SetNillableAggregateID(v *string) *OutboxMessageUpdate {
	if v != nil {
		_u.SetAggregateID(*v)
	}
	return _u
}

// SetTopic sets the "topic" field.
func (_u *OutboxMessageUpdate) SetTopic(v string) *OutboxMessageUpdate {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *OutboxMessageUpdate) SetNillableTopic(v *string) *OutboxMessageUpdate {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetMessageKey sets the "message_key" field.
func (_u *OutboxMessageUpdate) SetMessageKey(v string) *OutboxMessageUpdate {
	_u.mutation.SetMessageKey(v)
	return _u
}

// SetNillableMessageKey sets the "message_key" field if the given value is not nil.
func (_u *OutboxMessageUpdate) SetNillableMessageKey(v *string) *OutboxMessageUpdate {
	if v != nil {
		_u.SetMessageKey(*v)
	}
	return _u
}

// ClearMessageKey clears the value of the "message_key" field.
func (_u *OutboxMessageUpdate) ClearMessageKey() *OutboxMessageUpdate {
	_u.mutation.ClearMessageKey()
	return _u
}

// SetMessageValue sets the "message_value" field.
func (_u *OutboxMessageUpdate) SetMessageValue(v []byte) *OutboxMessageUpdate {
	_u.mutation.SetMessageValue(v)
	return _u
}

// SetMessageHeaders sets the "message_headers" field.
func (_u *OutboxMessageUpdate) SetMessageHeaders(v map[string]string) *OutboxMessageUpdate {
	_u.mutation.SetMessageHeaders(v)
	return _u
}

// ClearMessageHeaders clears the value of the "message_headers" field.
func (_u *OutboxMessageUpdate) ClearMessageHeaders() *OutboxMessageUpdate {
	_u.mutation.ClearMessageHeaders()
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *OutboxMessageUpdate) SetEventType(v string) *OutboxMessageUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *OutboxMessageUpdate) SetNillableEventType(v *string) *OutboxMessageUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetSendStatus sets the "send_status" field.
func (_u *OutboxMessageUpdate) SetSendStatus(v string) *OutboxMessageUpdate {
	_u.mutation.SetSendStatus(v)
	return _u
}

// SetNillableSendStatus sets the "send_status" field if the given value is not nil.
func (_u *OutboxMessageUpdate) SetNillableSendStatus(v *string) *OutboxMessageUpdate {
	if v != nil {
		_u.SetSendStatus(*v)
	}
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *OutboxMessageUpdate) SetRetryCount(v int) *OutboxMessageUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *OutboxMessageUpdate) SetNillableRetryCount(v *int) *OutboxMessageUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *OutboxMessageUpdate) AddRetryCount(v int) *OutboxMessageUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetMaxRetries sets the "max_retries" field.
func (_u *OutboxMessageUpdate) SetMaxRetries(v int) *OutboxMessageUpdate {
	_u.mutation.ResetMaxRetries()
	_u.mutation.SetMaxRetries(v)
	return _u
}

// SetNillableMaxRetries sets the "max_retries" field if the given value is not nil.
func (_u *OutboxMessageUpdate) SetNillableMaxRetries(v *int) *OutboxMessageUpdate {
	if v != nil {
		_u.SetMaxRetries(*v)
	}
	return _u
}

// AddMaxRetries adds value to the "max_retries" field.
func (_u *OutboxMessageUpdate) AddMaxRetries(v int) *OutboxMessageUpdate {
	_u.mutation.AddMaxRetries(v)
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *OutboxMessageUpdate) SetSentAt(v time.Time) *OutboxMessageUpdate {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *OutboxMessageUpdate) SetNillableSentAt(v *time.Time) *OutboxMessageUpdate {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *OutboxMessageUpdate) ClearSentAt() *OutboxMessageUpdate {
	_u.mutation.ClearSentAt()
	return _u
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_u *OutboxMessageUpdate) SetNextRetryAt(v time.Time) *OutboxMessageUpdate {
	_u.mutation.SetNextRetryAt(v)
	return _u
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_u *OutboxMessageUpdate) SetNillableNextRetryAt(v *time.Time) *OutboxMessageUpdate {
	if v != nil {
		_u.SetNextRetryAt(*v)
	}
	return _u
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (_u *OutboxMessageUpdate) ClearNextRetryAt() *OutboxMessageUpdate {
	_u.mutation.ClearNextRetryAt()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *OutboxMessageUpdate) SetErrorMessage(v string) *OutboxMessageUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *OutboxMessageUpdate) SetNillableErrorMessage(v *string) *OutboxMessageUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *OutboxMessageUpdate) ClearErrorMessage() *OutboxMessageUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *OutboxMessageUpdate) SetLastError(v string) *OutboxMessageUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *OutboxMessageUpdate) SetNillableLastError(v *string) *OutboxMessageUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *OutboxMessageUpdate) ClearLastError() *OutboxMessageUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *OutboxMessageUpdate) SetMetadata(v map[string]interface{}) *OutboxMessageUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *OutboxMessageUpdate) ClearMetadata() *OutboxMessageUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *OutboxMessageUpdate) SetPriority(v int) *OutboxMessageUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *OutboxMessageUpdate) SetNillablePriority(v *int) *OutboxMessageUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *OutboxMessageUpdate) AddPriority(v int) *OutboxMessageUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// Mutation returns the OutboxMessageMutation object of the builder.
func (_u *OutboxMessageUpdate) Mutation() *OutboxMessageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OutboxMessageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutboxMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OutboxMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutboxMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OutboxMessageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := outboxmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OutboxMessageUpdate) check() error {
	if v, ok := _u.mutation.AggregateType(); ok {
		if err := outboxmessage.AggregateTypeValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_type", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.aggregate_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AggregateID(); ok {
		if err := outboxmessage.AggregateIDValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_id", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.aggregate_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Topic(); ok {
		if err := outboxmessage.TopicValidator(v); err != nil {
			return &ValidationError{Name: "topic", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.topic": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MessageKey(); ok {
		if err := outboxmessage.MessageKeyValidator(v); err != nil {
			return &ValidationError{Name: "message_key", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.message_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := outboxmessage.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SendStatus(); ok {
		if err := outboxmessage.SendStatusValidator(v); err != nil {
			return &ValidationError{Name: "send_status", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.send_status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OutboxMessageUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OutboxMessageUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OutboxMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(outboxmessage.Table, outboxmessage.Columns, sqlgraph.NewFieldSpec(outboxmessage.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(outboxmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(outboxmessage.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(outboxmessage.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(outboxmessage.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.AggregateType(); ok {
		_spec.SetField(outboxmessage.FieldAggregateType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AggregateID(); ok {
		_spec.SetField(outboxmessage.FieldAggregateID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(outboxmessage.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageKey(); ok {
		_spec.SetField(outboxmessage.FieldMessageKey, field.TypeString, value)
	}
	if _u.mutation.MessageKeyCleared() {
		_spec.ClearField(outboxmessage.FieldMessageKey, field.TypeString)
	}
	if value, ok := _u.mutation.MessageValue(); ok {
		_spec.SetField(outboxmessage.FieldMessageValue, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.MessageHeaders(); ok {
		_spec.SetField(outboxmessage.FieldMessageHeaders, field.TypeJSON, value)
	}
	if _u.mutation.MessageHeadersCleared() {
		_spec.ClearField(outboxmessage.FieldMessageHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(outboxmessage.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SendStatus(); ok {
		_spec.SetField(outboxmessage.FieldSendStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(outboxmessage.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(outboxmessage.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxRetries(); ok {
		_spec.SetField(outboxmessage.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxRetries(); ok {
		_spec.AddField(outboxmessage.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(outboxmessage.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(outboxmessage.FieldSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextRetryAt(); ok {
		_spec.SetField(outboxmessage.FieldNextRetryAt, field.TypeTime, value)
	}
	if _u.mutation.NextRetryAtCleared() {
		_spec.ClearField(outboxmessage.FieldNextRetryAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(outboxmessage.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(outboxmessage.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(outboxmessage.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(outboxmessage.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(outboxmessage.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(outboxmessage.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(outboxmessage.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(outboxmessage.FieldPriority, field.TypeInt, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outboxmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OutboxMessageUpdateOne is the builder for updating a single OutboxMessage entity.
type OutboxMessageUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *OutboxMessageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OutboxMessageUpdateOne) SetUpdatedAt(v time.Time) *OutboxMessageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *OutboxMessageUpdateOne) SetStatus(v uint8) *OutboxMessageUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OutboxMessageUpdateOne) SetNillableStatus(v *uint8) *OutboxMessageUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *OutboxMessageUpdateOne) AddStatus(v int8) *OutboxMessageUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *OutboxMessageUpdateOne) ClearStatus() *OutboxMessageUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetAggregateType sets the "aggregate_type" field.
func (_u *OutboxMessageUpdateOne) SetAggregateType(v string) *OutboxMessageUpdateOne {
	_u.mutation.SetAggregateType(v)
	return _u
}

// SetNillableAggregateType sets the "aggregate_type" field if the given value is not nil.
func (_u *OutboxMessageUpdateOne) SetNillableAggregateType(v *string) *OutboxMessageUpdateOne {
	if v != nil {
		_u.SetAggregateType(*v)
	}
	return _u
}

// SetAggregateID sets the "aggregate_id" field.
func (_u *OutboxMessageUpdateOne) SetAggregateID(v string) *OutboxMessageUpdateOne {
	_u.mutation.SetAggregateID(v)
	return _u
}

// SetNillableAggregateID sets the "aggregate_id" field if the given value is not nil.
func (_u *OutboxMessageUpdateOne) SetNillableAggregateID(v *string) *OutboxMessageUpdateOne {
	if v != nil {
		_u.SetAggregateID(*v)
	}
	return _u
}

// SetTopic sets the "topic" field.
func (_u *OutboxMessageUpdateOne) SetTopic(v string) *OutboxMessageUpdateOne {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *OutboxMessageUpdateOne) SetNillableTopic(v *string) *OutboxMessageUpdateOne {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetMessageKey sets the "message_key" field.
func (_u *OutboxMessageUpdateOne) SetMessageKey(v string) *OutboxMessageUpdateOne {
	_u.mutation.SetMessageKey(v)
	return _u
}

// SetNillableMessageKey sets the "message_key" field if the given value is not nil.
func (_u *OutboxMessageUpdateOne) SetNillableMessageKey(v *string) *OutboxMessageUpdateOne {
	if v != nil {
		_u.SetMessageKey(*v)
	}
	return _u
}

// ClearMessageKey clears the value of the "message_key" field.
func (_u *OutboxMessageUpdateOne) ClearMessageKey() *OutboxMessageUpdateOne {
	_u.mutation.ClearMessageKey()
	return _u
}

// SetMessageValue sets the "message_value" field.
func (_u *OutboxMessageUpdateOne) SetMessageValue(v []byte) *OutboxMessageUpdateOne {
	_u.mutation.SetMessageValue(v)
	return _u
}

// SetMessageHeaders sets the "message_headers" field.
func (_u *OutboxMessageUpdateOne) SetMessageHeaders(v map[string]string) *OutboxMessageUpdateOne {
	_u.mutation.SetMessageHeaders(v)
	return _u
}

// ClearMessageHeaders clears the value of the "message_headers" field.
func (_u *OutboxMessageUpdateOne) ClearMessageHeaders() *OutboxMessageUpdateOne {
	_u.mutation.ClearMessageHeaders()
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *OutboxMessageUpdateOne) SetEventType(v string) *OutboxMessageUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *OutboxMessageUpdateOne) SetNillableEventType(v *string) *OutboxMessageUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetSendStatus sets the "send_status" field.
func (_u *OutboxMessageUpdateOne) SetSendStatus(v string) *OutboxMessageUpdateOne {
	_u.mutation.SetSendStatus(v)
	return _u
}

// SetNillableSendStatus sets the "send_status" field if the given value is not nil.
func (_u *OutboxMessageUpdateOne) SetNillableSendStatus(v *string) *OutboxMessageUpdateOne {
	if v != nil {
		_u.SetSendStatus(*v)
	}
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *OutboxMessageUpdateOne) SetRetryCount(v int) *OutboxMessageUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *OutboxMessageUpdateOne) SetNillableRetryCount(v *int) *OutboxMessageUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *OutboxMessageUpdateOne) AddRetryCount(v int) *OutboxMessageUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetMaxRetries sets the "max_retries" field.
func (_u *OutboxMessageUpdateOne) SetMaxRetries(v int) *OutboxMessageUpdateOne {
	_u.mutation.ResetMaxRetries()
	_u.mutation.SetMaxRetries(v)
	return _u
}

// SetNillableMaxRetries sets the "max_retries" field if the given value is not nil.
func (_u *OutboxMessageUpdateOne) SetNillableMaxRetries(v *int) *OutboxMessageUpdateOne {
	if v != nil {
		_u.SetMaxRetries(*v)
	}
	return _u
}

// AddMaxRetries adds value to the "max_retries" field.
func (_u *OutboxMessageUpdateOne) AddMaxRetries(v int) *OutboxMessageUpdateOne {
	_u.mutation.AddMaxRetries(v)
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *OutboxMessageUpdateOne) SetSentAt(v time.Time) *OutboxMessageUpdateOne {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *OutboxMessageUpdateOne) SetNillableSentAt(v *time.Time) *OutboxMessageUpdateOne {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *OutboxMessageUpdateOne) ClearSentAt() *OutboxMessageUpdateOne {
	_u.mutation.ClearSentAt()
	return _u
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_u *OutboxMessageUpdateOne) SetNextRetryAt(v time.Time) *OutboxMessageUpdateOne {
	_u.mutation.SetNextRetryAt(v)
	return _u
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_u *OutboxMessageUpdateOne) SetNillableNextRetryAt(v *time.Time) *OutboxMessageUpdateOne {
	if v != nil {
		_u.SetNextRetryAt(*v)
	}
	return _u
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (_u *OutboxMessageUpdateOne) ClearNextRetryAt() *OutboxMessageUpdateOne {
	_u.mutation.ClearNextRetryAt()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *OutboxMessageUpdateOne) SetErrorMessage(v string) *OutboxMessageUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *OutboxMessageUpdateOne) SetNillableErrorMessage(v *string) *OutboxMessageUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *OutboxMessageUpdateOne) ClearErrorMessage() *OutboxMessageUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *OutboxMessageUpdateOne) SetLastError(v string) *OutboxMessageUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *OutboxMessageUpdateOne) SetNillableLastError(v *string) *OutboxMessageUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *OutboxMessageUpdateOne) ClearLastError() *OutboxMessageUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *OutboxMessageUpdateOne) SetMetadata(v map[string]interface{}) *OutboxMessageUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *OutboxMessageUpdateOne) ClearMetadata() *OutboxMessageUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *OutboxMessageUpdateOne) SetPriority(v int) *OutboxMessageUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *OutboxMessageUpdateOne) SetNillablePriority(v *int) *OutboxMessageUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *OutboxMessageUpdateOne) AddPriority(v int) *OutboxMessageUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// Mutation returns the OutboxMessageMutation object of the builder.
func (_u *OutboxMessageUpdateOne) Mutation() *OutboxMessageMutation {
	return _u.mutation
}

// Where appends a list predicates to the OutboxMessageUpdate builder.
func (_u *OutboxMessageUpdateOne) Where(ps ...predicate.OutboxMessage) *OutboxMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OutboxMessageUpdateOne) Select(field string, fields ...string) *OutboxMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OutboxMessage entity.
func (_u *OutboxMessageUpdateOne) Save(ctx context.Context) (*OutboxMessage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutboxMessageUpdateOne) SaveX(ctx context.Context) *OutboxMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OutboxMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutboxMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OutboxMessageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := outboxmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OutboxMessageUpdateOne) check() error {
	if v, ok := _u.mutation.AggregateType(); ok {
		if err := outboxmessage.AggregateTypeValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_type", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.aggregate_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AggregateID(); ok {
		if err := outboxmessage.AggregateIDValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_id", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.aggregate_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Topic(); ok {
		if err := outboxmessage.TopicValidator(v); err != nil {
			return &ValidationError{Name: "topic", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.topic": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MessageKey(); ok {
		if err := outboxmessage.MessageKeyValidator(v); err != nil {
			return &ValidationError{Name: "message_key", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.message_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := outboxmessage.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SendStatus(); ok {
		if err := outboxmessage.SendStatusValidator(v); err != nil {
			return &ValidationError{Name: "send_status", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.send_status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OutboxMessageUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OutboxMessageUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OutboxMessageUpdateOne) sqlSave(ctx context.Context) (_node *OutboxMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(outboxmessage.Table, outboxmessage.Columns, sqlgraph.NewFieldSpec(outboxmessage.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OutboxMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, outboxmessage.FieldID)
		for _, f := range fields {
			if !outboxmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != outboxmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(outboxmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(outboxmessage.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(outboxmessage.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(outboxmessage.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.AggregateType(); ok {
		_spec.SetField(outboxmessage.FieldAggregateType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AggregateID(); ok {
		_spec.SetField(outboxmessage.FieldAggregateID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(outboxmessage.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageKey(); ok {
		_spec.SetField(outboxmessage.FieldMessageKey, field.TypeString, value)
	}
	if _u.mutation.MessageKeyCleared() {
		_spec.ClearField(outboxmessage.FieldMessageKey, field.TypeString)
	}
	if value, ok := _u.mutation.MessageValue(); ok {
		_spec.SetField(outboxmessage.FieldMessageValue, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.MessageHeaders(); ok {
		_spec.SetField(outboxmessage.FieldMessageHeaders, field.TypeJSON, value)
	}
	if _u.mutation.MessageHeadersCleared() {
		_spec.ClearField(outboxmessage.FieldMessageHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(outboxmessage.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SendStatus(); ok {
		_spec.SetField(outboxmessage.FieldSendStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(outboxmessage.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(outboxmessage.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxRetries(); ok {
		_spec.SetField(outboxmessage.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxRetries(); ok {
		_spec.AddField(outboxmessage.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(outboxmessage.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(outboxmessage.FieldSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextRetryAt(); ok {
		_spec.SetField(outboxmessage.FieldNextRetryAt, field.TypeTime, value)
	}
	if _u.mutation.NextRetryAtCleared() {
		_spec.ClearField(outboxmessage.FieldNextRetryAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(outboxmessage.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(outboxmessage.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(outboxmessage.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(outboxmessage.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(outboxmessage.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(outboxmessage.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(outboxmessage.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(outboxmessage.FieldPriority, field.TypeInt, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &OutboxMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outboxmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
