// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-io-rpc/ent/workermetrics"
)

// WorkerMetricsCreate is the builder for creating a WorkerMetrics entity.
type WorkerMetricsCreate struct {
	config
	mutation *WorkerMetricsMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *WorkerMetricsCreate) SetCreatedAt(v time.Time) *WorkerMetricsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WorkerMetricsCreate) SetNillableCreatedAt(v *time.Time) *WorkerMetricsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WorkerMetricsCreate) SetUpdatedAt(v time.Time) *WorkerMetricsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WorkerMetricsCreate) SetNillableUpdatedAt(v *time.Time) *WorkerMetricsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetWorkerID sets the "worker_id" field.
func (_c *WorkerMetricsCreate) SetWorkerID(v string) *WorkerMetricsCreate {
	_c.mutation.SetWorkerID(v)
	return _c
}

// SetWorkerName sets the "worker_name" field.
func (_c *WorkerMetricsCreate) SetWorkerName(v string) *WorkerMetricsCreate {
	_c.mutation.SetWorkerName(v)
	return _c
}

// SetWorkerStatus sets the "worker_status" field.
func (_c *WorkerMetricsCreate) SetWorkerStatus(v string) *WorkerMetricsCreate {
	_c.mutation.SetWorkerStatus(v)
	return _c
}

// SetNillableWorkerStatus sets the "worker_status" field if the given value is not nil.
func (_c *WorkerMetricsCreate) SetNillableWorkerStatus(v *string) *WorkerMetricsCreate {
	if v != nil {
		_c.SetWorkerStatus(*v)
	}
	return _c
}

// SetCurrentTasks sets the "current_tasks" field.
func (_c *WorkerMetricsCreate) SetCurrentTasks(v int) *WorkerMetricsCreate {
	_c.mutation.SetCurrentTasks(v)
	return _c
}

// SetNillableCurrentTasks sets the "current_tasks" field if the given value is not nil.
func (_c *WorkerMetricsCreate) SetNillableCurrentTasks(v *int) *WorkerMetricsCreate {
	if v != nil {
		_c.SetCurrentTasks(*v)
	}
	return _c
}

// SetTotalTasks sets the "total_tasks" field.
func (_c *WorkerMetricsCreate) SetTotalTasks(v int) *WorkerMetricsCreate {
	_c.mutation.SetTotalTasks(v)
	return _c
}

// SetNillableTotalTasks sets the "total_tasks" field if the given value is not nil.
func (_c *WorkerMetricsCreate) SetNillableTotalTasks(v *int) *WorkerMetricsCreate {
	if v != nil {
		_c.SetTotalTasks(*v)
	}
	return _c
}

// SetSuccessTasks sets the "success_tasks" field.
func (_c *WorkerMetricsCreate) SetSuccessTasks(v int) *WorkerMetricsCreate {
	_c.mutation.SetSuccessTasks(v)
	return _c
}

// SetNillableSuccessTasks sets the "success_tasks" field if the given value is not nil.
func (_c *WorkerMetricsCreate) SetNillableSuccessTasks(v *int) *WorkerMetricsCreate {
	if v != nil {
		_c.SetSuccessTasks(*v)
	}
	return _c
}

// SetFailedTasks sets the "failed_tasks" field.
func (_c *WorkerMetricsCreate) SetFailedTasks(v int) *WorkerMetricsCreate {
	_c.mutation.SetFailedTasks(v)
	return _c
}

// SetNillableFailedTasks sets the "failed_tasks" field if the given value is not nil.
func (_c *WorkerMetricsCreate) SetNillableFailedTasks(v *int) *WorkerMetricsCreate {
	if v != nil {
		_c.SetFailedTasks(*v)
	}
	return _c
}

// SetCPUUsage sets the "cpu_usage" field.
func (_c *WorkerMetricsCreate) SetCPUUsage(v float64) *WorkerMetricsCreate {
	_c.mutation.SetCPUUsage(v)
	return _c
}

// SetNillableCPUUsage sets the "cpu_usage" field if the given value is not nil.
func (_c *WorkerMetricsCreate) SetNillableCPUUsage(v *float64) *WorkerMetricsCreate {
	if v != nil {
		_c.SetCPUUsage(*v)
	}
	return _c
}

// SetMemoryUsage sets the "memory_usage" field.
func (_c *WorkerMetricsCreate) SetMemoryUsage(v float64) *WorkerMetricsCreate {
	_c.mutation.SetMemoryUsage(v)
	return _c
}

// SetNillableMemoryUsage sets the "memory_usage" field if the given value is not nil.
func (_c *WorkerMetricsCreate) SetNillableMemoryUsage(v *float64) *WorkerMetricsCreate {
	if v != nil {
		_c.SetMemoryUsage(*v)
	}
	return _c
}

// SetLastHeartbeat sets the "last_heartbeat" field.
func (_c *WorkerMetricsCreate) SetLastHeartbeat(v time.Time) *WorkerMetricsCreate {
	_c.mutation.SetLastHeartbeat(v)
	return _c
}

// SetNillableLastHeartbeat sets the "last_heartbeat" field if the given value is not nil.
func (_c *WorkerMetricsCreate) SetNillableLastHeartbeat(v *time.Time) *WorkerMetricsCreate {
	if v != nil {
		_c.SetLastHeartbeat(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *WorkerMetricsCreate) SetMetadata(v string) *WorkerMetricsCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_c *WorkerMetricsCreate) SetNillableMetadata(v *string) *WorkerMetricsCreate {
	if v != nil {
		_c.SetMetadata(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WorkerMetricsCreate) SetID(v uint64) *WorkerMetricsCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the WorkerMetricsMutation object of the builder.
func (_c *WorkerMetricsCreate) Mutation() *WorkerMetricsMutation {
	return _c.mutation
}

// Save creates the WorkerMetrics in the database.
func (_c *WorkerMetricsCreate) Save(ctx context.Context) (*WorkerMetrics, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkerMetricsCreate) SaveX(ctx context.Context) *WorkerMetrics {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkerMetricsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkerMetricsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkerMetricsCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := workermetrics.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := workermetrics.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.WorkerStatus(); !ok {
		v := workermetrics.DefaultWorkerStatus
		_c.mutation.SetWorkerStatus(v)
	}
	if _, ok := _c.mutation.CurrentTasks(); !ok {
		v := workermetrics.DefaultCurrentTasks
		_c.mutation.SetCurrentTasks(v)
	}
	if _, ok := _c.mutation.TotalTasks(); !ok {
		v := workermetrics.DefaultTotalTasks
		_c.mutation.SetTotalTasks(v)
	}
	if _, ok := _c.mutation.SuccessTasks(); !ok {
		v := workermetrics.DefaultSuccessTasks
		_c.mutation.SetSuccessTasks(v)
	}
	if _, ok := _c.mutation.FailedTasks(); !ok {
		v := workermetrics.DefaultFailedTasks
		_c.mutation.SetFailedTasks(v)
	}
	if _, ok := _c.mutation.CPUUsage(); !ok {
		v := workermetrics.DefaultCPUUsage
		_c.mutation.SetCPUUsage(v)
	}
	if _, ok := _c.mutation.MemoryUsage(); !ok {
		v := workermetrics.DefaultMemoryUsage
		_c.mutation.SetMemoryUsage(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkerMetricsCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WorkerMetrics.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WorkerMetrics.updated_at"`)}
	}
	if _, ok := _c.mutation.WorkerID(); !ok {
		return &ValidationError{Name: "worker_id", err: errors.New(`ent: missing required field "WorkerMetrics.worker_id"`)}
	}
	if v, ok := _c.mutation.WorkerID(); ok {
		if err := workermetrics.WorkerIDValidator(v); err != nil {
			return &ValidationError{Name: "worker_id", err: fmt.Errorf(`ent: validator failed for field "WorkerMetrics.worker_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WorkerName(); !ok {
		return &ValidationError{Name: "worker_name", err: errors.New(`ent: missing required field "WorkerMetrics.worker_name"`)}
	}
	if v, ok := _c.mutation.WorkerName(); ok {
		if err := workermetrics.WorkerNameValidator(v); err != nil {
			return &ValidationError{Name: "worker_name", err: fmt.Errorf(`ent: validator failed for field "WorkerMetrics.worker_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WorkerStatus(); !ok {
		return &ValidationError{Name: "worker_status", err: errors.New(`ent: missing required field "WorkerMetrics.worker_status"`)}
	}
	if v, ok := _c.mutation.WorkerStatus(); ok {
		if err := workermetrics.WorkerStatusValidator(v); err != nil {
			return &ValidationError{Name: "worker_status", err: fmt.Errorf(`ent: validator failed for field "WorkerMetrics.worker_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CurrentTasks(); !ok {
		return &ValidationError{Name: "current_tasks", err: errors.New(`ent: missing required field "WorkerMetrics.current_tasks"`)}
	}
	if _, ok := _c.mutation.TotalTasks(); !ok {
		return &ValidationError{Name: "total_tasks", err: errors.New(`ent: missing required field "WorkerMetrics.total_tasks"`)}
	}
	if _, ok := _c.mutation.SuccessTasks(); !ok {
		return &ValidationError{Name: "success_tasks", err: errors.New(`ent: missing required field "WorkerMetrics.success_tasks"`)}
	}
	if _, ok := _c.mutation.FailedTasks(); !ok {
		return &ValidationError{Name: "failed_tasks", err: errors.New(`ent: missing required field "WorkerMetrics.failed_tasks"`)}
	}
	if _, ok := _c.mutation.CPUUsage(); !ok {
		return &ValidationError{Name: "cpu_usage", err: errors.New(`ent: missing required field "WorkerMetrics.cpu_usage"`)}
	}
	if _, ok := _c.mutation.MemoryUsage(); !ok {
		return &ValidationError{Name: "memory_usage", err: errors.New(`ent: missing required field "WorkerMetrics.memory_usage"`)}
	}
	return nil
}

func (_c *WorkerMetricsCreate) sqlSave(ctx context.Context) (*WorkerMetrics, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkerMetricsCreate) createSpec() (*WorkerMetrics, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkerMetrics{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(workermetrics.Table, sqlgraph.NewFieldSpec(workermetrics.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(workermetrics.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(workermetrics.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.WorkerID(); ok {
		_spec.SetField(workermetrics.FieldWorkerID, field.TypeString, value)
		_node.WorkerID = value
	}
	if value, ok := _c.mutation.WorkerName(); ok {
		_spec.SetField(workermetrics.FieldWorkerName, field.TypeString, value)
		_node.WorkerName = value
	}
	if value, ok := _c.mutation.WorkerStatus(); ok {
		_spec.SetField(workermetrics.FieldWorkerStatus, field.TypeString, value)
		_node.WorkerStatus = value
	}
	if value, ok := _c.mutation.CurrentTasks(); ok {
		_spec.SetField(workermetrics.FieldCurrentTasks, field.TypeInt, value)
		_node.CurrentTasks = value
	}
	if value, ok := _c.mutation.TotalTasks(); ok {
		_spec.SetField(workermetrics.FieldTotalTasks, field.TypeInt, value)
		_node.TotalTasks = value
	}
	if value, ok := _c.mutation.SuccessTasks(); ok {
		_spec.SetField(workermetrics.FieldSuccessTasks, field.TypeInt, value)
		_node.SuccessTasks = value
	}
	if value, ok := _c.mutation.FailedTasks(); ok {
		_spec.SetField(workermetrics.FieldFailedTasks, field.TypeInt, value)
		_node.FailedTasks = value
	}
	if value, ok := _c.mutation.CPUUsage(); ok {
		_spec.SetField(workermetrics.FieldCPUUsage, field.TypeFloat64, value)
		_node.CPUUsage = value
	}
	if value, ok := _c.mutation.MemoryUsage(); ok {
		_spec.SetField(workermetrics.FieldMemoryUsage, field.TypeFloat64, value)
		_node.MemoryUsage = value
	}
	if value, ok := _c.mutation.LastHeartbeat(); ok {
		_spec.SetField(workermetrics.FieldLastHeartbeat, field.TypeTime, value)
		_node.LastHeartbeat = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(workermetrics.FieldMetadata, field.TypeString, value)
		_node.Metadata = value
	}
	return _node, _spec
}

// WorkerMetricsCreateBulk is the builder for creating many WorkerMetrics entities in bulk.
type WorkerMetricsCreateBulk struct {
	config
	err      error
	builders []*WorkerMetricsCreate
}

// Save creates the WorkerMetrics entities in the database.
func (_c *WorkerMetricsCreateBulk) Save(ctx context.Context) ([]*WorkerMetrics, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WorkerMetrics, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkerMetricsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkerMetricsCreateBulk) SaveX(ctx context.Context) []*WorkerMetrics {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkerMetricsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkerMetricsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
