// Code generated by ent, DO NOT EDIT.

package fieldmapping

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/coder-lulu/newbee-io-rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldTenantID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v uint8) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldStatus, v))
}

// MappingName applies equality check predicate on the "mapping_name" field. It's identical to MappingNameEQ.
func MappingName(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldMappingName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldDescription, v))
}

// MappingType applies equality check predicate on the "mapping_type" field. It's identical to MappingTypeEQ.
func MappingType(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldMappingType, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldIsActive, v))
}

// SourceField applies equality check predicate on the "source_field" field. It's identical to SourceFieldEQ.
func SourceField(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldSourceField, v))
}

// SourceFieldPath applies equality check predicate on the "source_field_path" field. It's identical to SourceFieldPathEQ.
func SourceFieldPath(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldSourceFieldPath, v))
}

// SourceDataType applies equality check predicate on the "source_data_type" field. It's identical to SourceDataTypeEQ.
func SourceDataType(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldSourceDataType, v))
}

// SourceFormat applies equality check predicate on the "source_format" field. It's identical to SourceFormatEQ.
func SourceFormat(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldSourceFormat, v))
}

// TargetField applies equality check predicate on the "target_field" field. It's identical to TargetFieldEQ.
func TargetField(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldTargetField, v))
}

// TargetFieldPath applies equality check predicate on the "target_field_path" field. It's identical to TargetFieldPathEQ.
func TargetFieldPath(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldTargetFieldPath, v))
}

// TargetDataType applies equality check predicate on the "target_data_type" field. It's identical to TargetDataTypeEQ.
func TargetDataType(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldTargetDataType, v))
}

// TargetFormat applies equality check predicate on the "target_format" field. It's identical to TargetFormatEQ.
func TargetFormat(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldTargetFormat, v))
}

// TransformType applies equality check predicate on the "transform_type" field. It's identical to TransformTypeEQ.
func TransformType(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldTransformType, v))
}

// TransformConfig applies equality check predicate on the "transform_config" field. It's identical to TransformConfigEQ.
func TransformConfig(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldTransformConfig, v))
}

// DefaultValue applies equality check predicate on the "default_value" field. It's identical to DefaultValueEQ.
func DefaultValue(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldDefaultValue, v))
}

// AllowNull applies equality check predicate on the "allow_null" field. It's identical to AllowNullEQ.
func AllowNull(v bool) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldAllowNull, v))
}

// IsRequired applies equality check predicate on the "is_required" field. It's identical to IsRequiredEQ.
func IsRequired(v bool) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldIsRequired, v))
}

// ValidationRules applies equality check predicate on the "validation_rules" field. It's identical to ValidationRulesEQ.
func ValidationRules(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldValidationRules, v))
}

// ValidationRegex applies equality check predicate on the "validation_regex" field. It's identical to ValidationRegexEQ.
func ValidationRegex(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldValidationRegex, v))
}

// LookupTable applies equality check predicate on the "lookup_table" field. It's identical to LookupTableEQ.
func LookupTable(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldLookupTable, v))
}

// LookupCaseSensitive applies equality check predicate on the "lookup_case_sensitive" field. It's identical to LookupCaseSensitiveEQ.
func LookupCaseSensitive(v bool) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldLookupCaseSensitive, v))
}

// ConditionRules applies equality check predicate on the "condition_rules" field. It's identical to ConditionRulesEQ.
func ConditionRules(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldConditionRules, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldPriority, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldSortOrder, v))
}

// DiscoveryPoolID applies equality check predicate on the "discovery_pool_id" field. It's identical to DiscoveryPoolIDEQ.
func DiscoveryPoolID(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldDiscoveryPoolID, v))
}

// InputTaskID applies equality check predicate on the "input_task_id" field. It's identical to InputTaskIDEQ.
func InputTaskID(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldInputTaskID, v))
}

// OutputTaskID applies equality check predicate on the "output_task_id" field. It's identical to OutputTaskIDEQ.
func OutputTaskID(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldOutputTaskID, v))
}

// UsageCount applies equality check predicate on the "usage_count" field. It's identical to UsageCountEQ.
func UsageCount(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldUsageCount, v))
}

// SuccessCount applies equality check predicate on the "success_count" field. It's identical to SuccessCountEQ.
func SuccessCount(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldSuccessCount, v))
}

// FailedCount applies equality check predicate on the "failed_count" field. It's identical to FailedCountEQ.
func FailedCount(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldFailedCount, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldLastError, v))
}

// LastErrorAt applies equality check predicate on the "last_error_at" field. It's identical to LastErrorAtEQ.
func LastErrorAt(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldLastErrorAt, v))
}

// Metadata applies equality check predicate on the "metadata" field. It's identical to MetadataEQ.
func Metadata(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldMetadata, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldTenantID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v uint8) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v uint8) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...uint8) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...uint8) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v uint8) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v uint8) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v uint8) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v uint8) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldStatus))
}

// MappingNameEQ applies the EQ predicate on the "mapping_name" field.
func MappingNameEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldMappingName, v))
}

// MappingNameNEQ applies the NEQ predicate on the "mapping_name" field.
func MappingNameNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldMappingName, v))
}

// MappingNameIn applies the In predicate on the "mapping_name" field.
func MappingNameIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldMappingName, vs...))
}

// MappingNameNotIn applies the NotIn predicate on the "mapping_name" field.
func MappingNameNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldMappingName, vs...))
}

// MappingNameGT applies the GT predicate on the "mapping_name" field.
func MappingNameGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldMappingName, v))
}

// MappingNameGTE applies the GTE predicate on the "mapping_name" field.
func MappingNameGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldMappingName, v))
}

// MappingNameLT applies the LT predicate on the "mapping_name" field.
func MappingNameLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldMappingName, v))
}

// MappingNameLTE applies the LTE predicate on the "mapping_name" field.
func MappingNameLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldMappingName, v))
}

// MappingNameContains applies the Contains predicate on the "mapping_name" field.
func MappingNameContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldMappingName, v))
}

// MappingNameHasPrefix applies the HasPrefix predicate on the "mapping_name" field.
func MappingNameHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldMappingName, v))
}

// MappingNameHasSuffix applies the HasSuffix predicate on the "mapping_name" field.
func MappingNameHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldMappingName, v))
}

// MappingNameEqualFold applies the EqualFold predicate on the "mapping_name" field.
func MappingNameEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldMappingName, v))
}

// MappingNameContainsFold applies the ContainsFold predicate on the "mapping_name" field.
func MappingNameContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldMappingName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldDescription, v))
}

// MappingTypeEQ applies the EQ predicate on the "mapping_type" field.
func MappingTypeEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldMappingType, v))
}

// MappingTypeNEQ applies the NEQ predicate on the "mapping_type" field.
func MappingTypeNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldMappingType, v))
}

// MappingTypeIn applies the In predicate on the "mapping_type" field.
func MappingTypeIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldMappingType, vs...))
}

// MappingTypeNotIn applies the NotIn predicate on the "mapping_type" field.
func MappingTypeNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldMappingType, vs...))
}

// MappingTypeGT applies the GT predicate on the "mapping_type" field.
func MappingTypeGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldMappingType, v))
}

// MappingTypeGTE applies the GTE predicate on the "mapping_type" field.
func MappingTypeGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldMappingType, v))
}

// MappingTypeLT applies the LT predicate on the "mapping_type" field.
func MappingTypeLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldMappingType, v))
}

// MappingTypeLTE applies the LTE predicate on the "mapping_type" field.
func MappingTypeLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldMappingType, v))
}

// MappingTypeContains applies the Contains predicate on the "mapping_type" field.
func MappingTypeContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldMappingType, v))
}

// MappingTypeHasPrefix applies the HasPrefix predicate on the "mapping_type" field.
func MappingTypeHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldMappingType, v))
}

// MappingTypeHasSuffix applies the HasSuffix predicate on the "mapping_type" field.
func MappingTypeHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldMappingType, v))
}

// MappingTypeEqualFold applies the EqualFold predicate on the "mapping_type" field.
func MappingTypeEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldMappingType, v))
}

// MappingTypeContainsFold applies the ContainsFold predicate on the "mapping_type" field.
func MappingTypeContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldMappingType, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldIsActive, v))
}

// SourceFieldEQ applies the EQ predicate on the "source_field" field.
func SourceFieldEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldSourceField, v))
}

// SourceFieldNEQ applies the NEQ predicate on the "source_field" field.
func SourceFieldNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldSourceField, v))
}

// SourceFieldIn applies the In predicate on the "source_field" field.
func SourceFieldIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldSourceField, vs...))
}

// SourceFieldNotIn applies the NotIn predicate on the "source_field" field.
func SourceFieldNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldSourceField, vs...))
}

// SourceFieldGT applies the GT predicate on the "source_field" field.
func SourceFieldGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldSourceField, v))
}

// SourceFieldGTE applies the GTE predicate on the "source_field" field.
func SourceFieldGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldSourceField, v))
}

// SourceFieldLT applies the LT predicate on the "source_field" field.
func SourceFieldLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldSourceField, v))
}

// SourceFieldLTE applies the LTE predicate on the "source_field" field.
func SourceFieldLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldSourceField, v))
}

// SourceFieldContains applies the Contains predicate on the "source_field" field.
func SourceFieldContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldSourceField, v))
}

// SourceFieldHasPrefix applies the HasPrefix predicate on the "source_field" field.
func SourceFieldHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldSourceField, v))
}

// SourceFieldHasSuffix applies the HasSuffix predicate on the "source_field" field.
func SourceFieldHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldSourceField, v))
}

// SourceFieldEqualFold applies the EqualFold predicate on the "source_field" field.
func SourceFieldEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldSourceField, v))
}

// SourceFieldContainsFold applies the ContainsFold predicate on the "source_field" field.
func SourceFieldContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldSourceField, v))
}

// SourceFieldPathEQ applies the EQ predicate on the "source_field_path" field.
func SourceFieldPathEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldSourceFieldPath, v))
}

// SourceFieldPathNEQ applies the NEQ predicate on the "source_field_path" field.
func SourceFieldPathNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldSourceFieldPath, v))
}

// SourceFieldPathIn applies the In predicate on the "source_field_path" field.
func SourceFieldPathIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldSourceFieldPath, vs...))
}

// SourceFieldPathNotIn applies the NotIn predicate on the "source_field_path" field.
func SourceFieldPathNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldSourceFieldPath, vs...))
}

// SourceFieldPathGT applies the GT predicate on the "source_field_path" field.
func SourceFieldPathGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldSourceFieldPath, v))
}

// SourceFieldPathGTE applies the GTE predicate on the "source_field_path" field.
func SourceFieldPathGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldSourceFieldPath, v))
}

// SourceFieldPathLT applies the LT predicate on the "source_field_path" field.
func SourceFieldPathLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldSourceFieldPath, v))
}

// SourceFieldPathLTE applies the LTE predicate on the "source_field_path" field.
func SourceFieldPathLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldSourceFieldPath, v))
}

// SourceFieldPathContains applies the Contains predicate on the "source_field_path" field.
func SourceFieldPathContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldSourceFieldPath, v))
}

// SourceFieldPathHasPrefix applies the HasPrefix predicate on the "source_field_path" field.
func SourceFieldPathHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldSourceFieldPath, v))
}

// SourceFieldPathHasSuffix applies the HasSuffix predicate on the "source_field_path" field.
func SourceFieldPathHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldSourceFieldPath, v))
}

// SourceFieldPathIsNil applies the IsNil predicate on the "source_field_path" field.
func SourceFieldPathIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldSourceFieldPath))
}

// SourceFieldPathNotNil applies the NotNil predicate on the "source_field_path" field.
func SourceFieldPathNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldSourceFieldPath))
}

// SourceFieldPathEqualFold applies the EqualFold predicate on the "source_field_path" field.
func SourceFieldPathEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldSourceFieldPath, v))
}

// SourceFieldPathContainsFold applies the ContainsFold predicate on the "source_field_path" field.
func SourceFieldPathContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldSourceFieldPath, v))
}

// SourceDataTypeEQ applies the EQ predicate on the "source_data_type" field.
func SourceDataTypeEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldSourceDataType, v))
}

// SourceDataTypeNEQ applies the NEQ predicate on the "source_data_type" field.
func SourceDataTypeNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldSourceDataType, v))
}

// SourceDataTypeIn applies the In predicate on the "source_data_type" field.
func SourceDataTypeIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldSourceDataType, vs...))
}

// SourceDataTypeNotIn applies the NotIn predicate on the "source_data_type" field.
func SourceDataTypeNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldSourceDataType, vs...))
}

// SourceDataTypeGT applies the GT predicate on the "source_data_type" field.
func SourceDataTypeGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldSourceDataType, v))
}

// SourceDataTypeGTE applies the GTE predicate on the "source_data_type" field.
func SourceDataTypeGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldSourceDataType, v))
}

// SourceDataTypeLT applies the LT predicate on the "source_data_type" field.
func SourceDataTypeLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldSourceDataType, v))
}

// SourceDataTypeLTE applies the LTE predicate on the "source_data_type" field.
func SourceDataTypeLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldSourceDataType, v))
}

// SourceDataTypeContains applies the Contains predicate on the "source_data_type" field.
func SourceDataTypeContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldSourceDataType, v))
}

// SourceDataTypeHasPrefix applies the HasPrefix predicate on the "source_data_type" field.
func SourceDataTypeHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldSourceDataType, v))
}

// SourceDataTypeHasSuffix applies the HasSuffix predicate on the "source_data_type" field.
func SourceDataTypeHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldSourceDataType, v))
}

// SourceDataTypeIsNil applies the IsNil predicate on the "source_data_type" field.
func SourceDataTypeIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldSourceDataType))
}

// SourceDataTypeNotNil applies the NotNil predicate on the "source_data_type" field.
func SourceDataTypeNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldSourceDataType))
}

// SourceDataTypeEqualFold applies the EqualFold predicate on the "source_data_type" field.
func SourceDataTypeEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldSourceDataType, v))
}

// SourceDataTypeContainsFold applies the ContainsFold predicate on the "source_data_type" field.
func SourceDataTypeContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldSourceDataType, v))
}

// SourceFormatEQ applies the EQ predicate on the "source_format" field.
func SourceFormatEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldSourceFormat, v))
}

// SourceFormatNEQ applies the NEQ predicate on the "source_format" field.
func SourceFormatNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldSourceFormat, v))
}

// SourceFormatIn applies the In predicate on the "source_format" field.
func SourceFormatIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldSourceFormat, vs...))
}

// SourceFormatNotIn applies the NotIn predicate on the "source_format" field.
func SourceFormatNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldSourceFormat, vs...))
}

// SourceFormatGT applies the GT predicate on the "source_format" field.
func SourceFormatGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldSourceFormat, v))
}

// SourceFormatGTE applies the GTE predicate on the "source_format" field.
func SourceFormatGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldSourceFormat, v))
}

// SourceFormatLT applies the LT predicate on the "source_format" field.
func SourceFormatLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldSourceFormat, v))
}

// SourceFormatLTE applies the LTE predicate on the "source_format" field.
func SourceFormatLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldSourceFormat, v))
}

// SourceFormatContains applies the Contains predicate on the "source_format" field.
func SourceFormatContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldSourceFormat, v))
}

// SourceFormatHasPrefix applies the HasPrefix predicate on the "source_format" field.
func SourceFormatHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldSourceFormat, v))
}

// SourceFormatHasSuffix applies the HasSuffix predicate on the "source_format" field.
func SourceFormatHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldSourceFormat, v))
}

// SourceFormatIsNil applies the IsNil predicate on the "source_format" field.
func SourceFormatIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldSourceFormat))
}

// SourceFormatNotNil applies the NotNil predicate on the "source_format" field.
func SourceFormatNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldSourceFormat))
}

// SourceFormatEqualFold applies the EqualFold predicate on the "source_format" field.
func SourceFormatEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldSourceFormat, v))
}

// SourceFormatContainsFold applies the ContainsFold predicate on the "source_format" field.
func SourceFormatContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldSourceFormat, v))
}

// TargetFieldEQ applies the EQ predicate on the "target_field" field.
func TargetFieldEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldTargetField, v))
}

// TargetFieldNEQ applies the NEQ predicate on the "target_field" field.
func TargetFieldNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldTargetField, v))
}

// TargetFieldIn applies the In predicate on the "target_field" field.
func TargetFieldIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldTargetField, vs...))
}

// TargetFieldNotIn applies the NotIn predicate on the "target_field" field.
func TargetFieldNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldTargetField, vs...))
}

// TargetFieldGT applies the GT predicate on the "target_field" field.
func TargetFieldGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldTargetField, v))
}

// TargetFieldGTE applies the GTE predicate on the "target_field" field.
func TargetFieldGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldTargetField, v))
}

// TargetFieldLT applies the LT predicate on the "target_field" field.
func TargetFieldLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldTargetField, v))
}

// TargetFieldLTE applies the LTE predicate on the "target_field" field.
func TargetFieldLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldTargetField, v))
}

// TargetFieldContains applies the Contains predicate on the "target_field" field.
func TargetFieldContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldTargetField, v))
}

// TargetFieldHasPrefix applies the HasPrefix predicate on the "target_field" field.
func TargetFieldHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldTargetField, v))
}

// TargetFieldHasSuffix applies the HasSuffix predicate on the "target_field" field.
func TargetFieldHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldTargetField, v))
}

// TargetFieldEqualFold applies the EqualFold predicate on the "target_field" field.
func TargetFieldEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldTargetField, v))
}

// TargetFieldContainsFold applies the ContainsFold predicate on the "target_field" field.
func TargetFieldContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldTargetField, v))
}

// TargetFieldPathEQ applies the EQ predicate on the "target_field_path" field.
func TargetFieldPathEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldTargetFieldPath, v))
}

// TargetFieldPathNEQ applies the NEQ predicate on the "target_field_path" field.
func TargetFieldPathNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldTargetFieldPath, v))
}

// TargetFieldPathIn applies the In predicate on the "target_field_path" field.
func TargetFieldPathIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldTargetFieldPath, vs...))
}

// TargetFieldPathNotIn applies the NotIn predicate on the "target_field_path" field.
func TargetFieldPathNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldTargetFieldPath, vs...))
}

// TargetFieldPathGT applies the GT predicate on the "target_field_path" field.
func TargetFieldPathGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldTargetFieldPath, v))
}

// TargetFieldPathGTE applies the GTE predicate on the "target_field_path" field.
func TargetFieldPathGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldTargetFieldPath, v))
}

// TargetFieldPathLT applies the LT predicate on the "target_field_path" field.
func TargetFieldPathLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldTargetFieldPath, v))
}

// TargetFieldPathLTE applies the LTE predicate on the "target_field_path" field.
func TargetFieldPathLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldTargetFieldPath, v))
}

// TargetFieldPathContains applies the Contains predicate on the "target_field_path" field.
func TargetFieldPathContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldTargetFieldPath, v))
}

// TargetFieldPathHasPrefix applies the HasPrefix predicate on the "target_field_path" field.
func TargetFieldPathHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldTargetFieldPath, v))
}

// TargetFieldPathHasSuffix applies the HasSuffix predicate on the "target_field_path" field.
func TargetFieldPathHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldTargetFieldPath, v))
}

// TargetFieldPathIsNil applies the IsNil predicate on the "target_field_path" field.
func TargetFieldPathIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldTargetFieldPath))
}

// TargetFieldPathNotNil applies the NotNil predicate on the "target_field_path" field.
func TargetFieldPathNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldTargetFieldPath))
}

// TargetFieldPathEqualFold applies the EqualFold predicate on the "target_field_path" field.
func TargetFieldPathEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldTargetFieldPath, v))
}

// TargetFieldPathContainsFold applies the ContainsFold predicate on the "target_field_path" field.
func TargetFieldPathContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldTargetFieldPath, v))
}

// TargetDataTypeEQ applies the EQ predicate on the "target_data_type" field.
func TargetDataTypeEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldTargetDataType, v))
}

// TargetDataTypeNEQ applies the NEQ predicate on the "target_data_type" field.
func TargetDataTypeNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldTargetDataType, v))
}

// TargetDataTypeIn applies the In predicate on the "target_data_type" field.
func TargetDataTypeIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldTargetDataType, vs...))
}

// TargetDataTypeNotIn applies the NotIn predicate on the "target_data_type" field.
func TargetDataTypeNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldTargetDataType, vs...))
}

// TargetDataTypeGT applies the GT predicate on the "target_data_type" field.
func TargetDataTypeGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldTargetDataType, v))
}

// TargetDataTypeGTE applies the GTE predicate on the "target_data_type" field.
func TargetDataTypeGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldTargetDataType, v))
}

// TargetDataTypeLT applies the LT predicate on the "target_data_type" field.
func TargetDataTypeLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldTargetDataType, v))
}

// TargetDataTypeLTE applies the LTE predicate on the "target_data_type" field.
func TargetDataTypeLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldTargetDataType, v))
}

// TargetDataTypeContains applies the Contains predicate on the "target_data_type" field.
func TargetDataTypeContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldTargetDataType, v))
}

// TargetDataTypeHasPrefix applies the HasPrefix predicate on the "target_data_type" field.
func TargetDataTypeHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldTargetDataType, v))
}

// TargetDataTypeHasSuffix applies the HasSuffix predicate on the "target_data_type" field.
func TargetDataTypeHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldTargetDataType, v))
}

// TargetDataTypeIsNil applies the IsNil predicate on the "target_data_type" field.
func TargetDataTypeIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldTargetDataType))
}

// TargetDataTypeNotNil applies the NotNil predicate on the "target_data_type" field.
func TargetDataTypeNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldTargetDataType))
}

// TargetDataTypeEqualFold applies the EqualFold predicate on the "target_data_type" field.
func TargetDataTypeEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldTargetDataType, v))
}

// TargetDataTypeContainsFold applies the ContainsFold predicate on the "target_data_type" field.
func TargetDataTypeContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldTargetDataType, v))
}

// TargetFormatEQ applies the EQ predicate on the "target_format" field.
func TargetFormatEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldTargetFormat, v))
}

// TargetFormatNEQ applies the NEQ predicate on the "target_format" field.
func TargetFormatNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldTargetFormat, v))
}

// TargetFormatIn applies the In predicate on the "target_format" field.
func TargetFormatIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldTargetFormat, vs...))
}

// TargetFormatNotIn applies the NotIn predicate on the "target_format" field.
func TargetFormatNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldTargetFormat, vs...))
}

// TargetFormatGT applies the GT predicate on the "target_format" field.
func TargetFormatGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldTargetFormat, v))
}

// TargetFormatGTE applies the GTE predicate on the "target_format" field.
func TargetFormatGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldTargetFormat, v))
}

// TargetFormatLT applies the LT predicate on the "target_format" field.
func TargetFormatLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldTargetFormat, v))
}

// TargetFormatLTE applies the LTE predicate on the "target_format" field.
func TargetFormatLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldTargetFormat, v))
}

// TargetFormatContains applies the Contains predicate on the "target_format" field.
func TargetFormatContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldTargetFormat, v))
}

// TargetFormatHasPrefix applies the HasPrefix predicate on the "target_format" field.
func TargetFormatHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldTargetFormat, v))
}

// TargetFormatHasSuffix applies the HasSuffix predicate on the "target_format" field.
func TargetFormatHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldTargetFormat, v))
}

// TargetFormatIsNil applies the IsNil predicate on the "target_format" field.
func TargetFormatIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldTargetFormat))
}

// TargetFormatNotNil applies the NotNil predicate on the "target_format" field.
func TargetFormatNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldTargetFormat))
}

// TargetFormatEqualFold applies the EqualFold predicate on the "target_format" field.
func TargetFormatEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldTargetFormat, v))
}

// TargetFormatContainsFold applies the ContainsFold predicate on the "target_format" field.
func TargetFormatContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldTargetFormat, v))
}

// TransformTypeEQ applies the EQ predicate on the "transform_type" field.
func TransformTypeEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldTransformType, v))
}

// TransformTypeNEQ applies the NEQ predicate on the "transform_type" field.
func TransformTypeNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldTransformType, v))
}

// TransformTypeIn applies the In predicate on the "transform_type" field.
func TransformTypeIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldTransformType, vs...))
}

// TransformTypeNotIn applies the NotIn predicate on the "transform_type" field.
func TransformTypeNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldTransformType, vs...))
}

// TransformTypeGT applies the GT predicate on the "transform_type" field.
func TransformTypeGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldTransformType, v))
}

// TransformTypeGTE applies the GTE predicate on the "transform_type" field.
func TransformTypeGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldTransformType, v))
}

// TransformTypeLT applies the LT predicate on the "transform_type" field.
func TransformTypeLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldTransformType, v))
}

// TransformTypeLTE applies the LTE predicate on the "transform_type" field.
func TransformTypeLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldTransformType, v))
}

// TransformTypeContains applies the Contains predicate on the "transform_type" field.
func TransformTypeContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldTransformType, v))
}

// TransformTypeHasPrefix applies the HasPrefix predicate on the "transform_type" field.
func TransformTypeHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldTransformType, v))
}

// TransformTypeHasSuffix applies the HasSuffix predicate on the "transform_type" field.
func TransformTypeHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldTransformType, v))
}

// TransformTypeEqualFold applies the EqualFold predicate on the "transform_type" field.
func TransformTypeEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldTransformType, v))
}

// TransformTypeContainsFold applies the ContainsFold predicate on the "transform_type" field.
func TransformTypeContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldTransformType, v))
}

// TransformConfigEQ applies the EQ predicate on the "transform_config" field.
func TransformConfigEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldTransformConfig, v))
}

// TransformConfigNEQ applies the NEQ predicate on the "transform_config" field.
func TransformConfigNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldTransformConfig, v))
}

// TransformConfigIn applies the In predicate on the "transform_config" field.
func TransformConfigIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldTransformConfig, vs...))
}

// TransformConfigNotIn applies the NotIn predicate on the "transform_config" field.
func TransformConfigNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldTransformConfig, vs...))
}

// TransformConfigGT applies the GT predicate on the "transform_config" field.
func TransformConfigGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldTransformConfig, v))
}

// TransformConfigGTE applies the GTE predicate on the "transform_config" field.
func TransformConfigGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldTransformConfig, v))
}

// TransformConfigLT applies the LT predicate on the "transform_config" field.
func TransformConfigLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldTransformConfig, v))
}

// TransformConfigLTE applies the LTE predicate on the "transform_config" field.
func TransformConfigLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldTransformConfig, v))
}

// TransformConfigContains applies the Contains predicate on the "transform_config" field.
func TransformConfigContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldTransformConfig, v))
}

// TransformConfigHasPrefix applies the HasPrefix predicate on the "transform_config" field.
func TransformConfigHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldTransformConfig, v))
}

// TransformConfigHasSuffix applies the HasSuffix predicate on the "transform_config" field.
func TransformConfigHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldTransformConfig, v))
}

// TransformConfigIsNil applies the IsNil predicate on the "transform_config" field.
func TransformConfigIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldTransformConfig))
}

// TransformConfigNotNil applies the NotNil predicate on the "transform_config" field.
func TransformConfigNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldTransformConfig))
}

// TransformConfigEqualFold applies the EqualFold predicate on the "transform_config" field.
func TransformConfigEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldTransformConfig, v))
}

// TransformConfigContainsFold applies the ContainsFold predicate on the "transform_config" field.
func TransformConfigContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldTransformConfig, v))
}

// DefaultValueEQ applies the EQ predicate on the "default_value" field.
func DefaultValueEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldDefaultValue, v))
}

// DefaultValueNEQ applies the NEQ predicate on the "default_value" field.
func DefaultValueNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldDefaultValue, v))
}

// DefaultValueIn applies the In predicate on the "default_value" field.
func DefaultValueIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldDefaultValue, vs...))
}

// DefaultValueNotIn applies the NotIn predicate on the "default_value" field.
func DefaultValueNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldDefaultValue, vs...))
}

// DefaultValueGT applies the GT predicate on the "default_value" field.
func DefaultValueGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldDefaultValue, v))
}

// DefaultValueGTE applies the GTE predicate on the "default_value" field.
func DefaultValueGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldDefaultValue, v))
}

// DefaultValueLT applies the LT predicate on the "default_value" field.
func DefaultValueLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldDefaultValue, v))
}

// DefaultValueLTE applies the LTE predicate on the "default_value" field.
func DefaultValueLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldDefaultValue, v))
}

// DefaultValueContains applies the Contains predicate on the "default_value" field.
func DefaultValueContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldDefaultValue, v))
}

// DefaultValueHasPrefix applies the HasPrefix predicate on the "default_value" field.
func DefaultValueHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldDefaultValue, v))
}

// DefaultValueHasSuffix applies the HasSuffix predicate on the "default_value" field.
func DefaultValueHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldDefaultValue, v))
}

// DefaultValueIsNil applies the IsNil predicate on the "default_value" field.
func DefaultValueIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldDefaultValue))
}

// DefaultValueNotNil applies the NotNil predicate on the "default_value" field.
func DefaultValueNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldDefaultValue))
}

// DefaultValueEqualFold applies the EqualFold predicate on the "default_value" field.
func DefaultValueEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldDefaultValue, v))
}

// DefaultValueContainsFold applies the ContainsFold predicate on the "default_value" field.
func DefaultValueContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldDefaultValue, v))
}

// AllowNullEQ applies the EQ predicate on the "allow_null" field.
func AllowNullEQ(v bool) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldAllowNull, v))
}

// AllowNullNEQ applies the NEQ predicate on the "allow_null" field.
func AllowNullNEQ(v bool) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldAllowNull, v))
}

// IsRequiredEQ applies the EQ predicate on the "is_required" field.
func IsRequiredEQ(v bool) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldIsRequired, v))
}

// IsRequiredNEQ applies the NEQ predicate on the "is_required" field.
func IsRequiredNEQ(v bool) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldIsRequired, v))
}

// ValidationRulesEQ applies the EQ predicate on the "validation_rules" field.
func ValidationRulesEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldValidationRules, v))
}

// ValidationRulesNEQ applies the NEQ predicate on the "validation_rules" field.
func ValidationRulesNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldValidationRules, v))
}

// ValidationRulesIn applies the In predicate on the "validation_rules" field.
func ValidationRulesIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldValidationRules, vs...))
}

// ValidationRulesNotIn applies the NotIn predicate on the "validation_rules" field.
func ValidationRulesNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldValidationRules, vs...))
}

// ValidationRulesGT applies the GT predicate on the "validation_rules" field.
func ValidationRulesGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldValidationRules, v))
}

// ValidationRulesGTE applies the GTE predicate on the "validation_rules" field.
func ValidationRulesGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldValidationRules, v))
}

// ValidationRulesLT applies the LT predicate on the "validation_rules" field.
func ValidationRulesLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldValidationRules, v))
}

// ValidationRulesLTE applies the LTE predicate on the "validation_rules" field.
func ValidationRulesLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldValidationRules, v))
}

// ValidationRulesContains applies the Contains predicate on the "validation_rules" field.
func ValidationRulesContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldValidationRules, v))
}

// ValidationRulesHasPrefix applies the HasPrefix predicate on the "validation_rules" field.
func ValidationRulesHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldValidationRules, v))
}

// ValidationRulesHasSuffix applies the HasSuffix predicate on the "validation_rules" field.
func ValidationRulesHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldValidationRules, v))
}

// ValidationRulesIsNil applies the IsNil predicate on the "validation_rules" field.
func ValidationRulesIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldValidationRules))
}

// ValidationRulesNotNil applies the NotNil predicate on the "validation_rules" field.
func ValidationRulesNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldValidationRules))
}

// ValidationRulesEqualFold applies the EqualFold predicate on the "validation_rules" field.
func ValidationRulesEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldValidationRules, v))
}

// ValidationRulesContainsFold applies the ContainsFold predicate on the "validation_rules" field.
func ValidationRulesContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldValidationRules, v))
}

// ValidationRegexEQ applies the EQ predicate on the "validation_regex" field.
func ValidationRegexEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldValidationRegex, v))
}

// ValidationRegexNEQ applies the NEQ predicate on the "validation_regex" field.
func ValidationRegexNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldValidationRegex, v))
}

// ValidationRegexIn applies the In predicate on the "validation_regex" field.
func ValidationRegexIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldValidationRegex, vs...))
}

// ValidationRegexNotIn applies the NotIn predicate on the "validation_regex" field.
func ValidationRegexNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldValidationRegex, vs...))
}

// ValidationRegexGT applies the GT predicate on the "validation_regex" field.
func ValidationRegexGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldValidationRegex, v))
}

// ValidationRegexGTE applies the GTE predicate on the "validation_regex" field.
func ValidationRegexGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldValidationRegex, v))
}

// ValidationRegexLT applies the LT predicate on the "validation_regex" field.
func ValidationRegexLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldValidationRegex, v))
}

// ValidationRegexLTE applies the LTE predicate on the "validation_regex" field.
func ValidationRegexLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldValidationRegex, v))
}

// ValidationRegexContains applies the Contains predicate on the "validation_regex" field.
func ValidationRegexContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldValidationRegex, v))
}

// ValidationRegexHasPrefix applies the HasPrefix predicate on the "validation_regex" field.
func ValidationRegexHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldValidationRegex, v))
}

// ValidationRegexHasSuffix applies the HasSuffix predicate on the "validation_regex" field.
func ValidationRegexHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldValidationRegex, v))
}

// ValidationRegexIsNil applies the IsNil predicate on the "validation_regex" field.
func ValidationRegexIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldValidationRegex))
}

// ValidationRegexNotNil applies the NotNil predicate on the "validation_regex" field.
func ValidationRegexNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldValidationRegex))
}

// ValidationRegexEqualFold applies the EqualFold predicate on the "validation_regex" field.
func ValidationRegexEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldValidationRegex, v))
}

// ValidationRegexContainsFold applies the ContainsFold predicate on the "validation_regex" field.
func ValidationRegexContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldValidationRegex, v))
}

// LookupTableEQ applies the EQ predicate on the "lookup_table" field.
func LookupTableEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldLookupTable, v))
}

// LookupTableNEQ applies the NEQ predicate on the "lookup_table" field.
func LookupTableNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldLookupTable, v))
}

// LookupTableIn applies the In predicate on the "lookup_table" field.
func LookupTableIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldLookupTable, vs...))
}

// LookupTableNotIn applies the NotIn predicate on the "lookup_table" field.
func LookupTableNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldLookupTable, vs...))
}

// LookupTableGT applies the GT predicate on the "lookup_table" field.
func LookupTableGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldLookupTable, v))
}

// LookupTableGTE applies the GTE predicate on the "lookup_table" field.
func LookupTableGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldLookupTable, v))
}

// LookupTableLT applies the LT predicate on the "lookup_table" field.
func LookupTableLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldLookupTable, v))
}

// LookupTableLTE applies the LTE predicate on the "lookup_table" field.
func LookupTableLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldLookupTable, v))
}

// LookupTableContains applies the Contains predicate on the "lookup_table" field.
func LookupTableContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldLookupTable, v))
}

// LookupTableHasPrefix applies the HasPrefix predicate on the "lookup_table" field.
func LookupTableHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldLookupTable, v))
}

// LookupTableHasSuffix applies the HasSuffix predicate on the "lookup_table" field.
func LookupTableHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldLookupTable, v))
}

// LookupTableIsNil applies the IsNil predicate on the "lookup_table" field.
func LookupTableIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldLookupTable))
}

// LookupTableNotNil applies the NotNil predicate on the "lookup_table" field.
func LookupTableNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldLookupTable))
}

// LookupTableEqualFold applies the EqualFold predicate on the "lookup_table" field.
func LookupTableEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldLookupTable, v))
}

// LookupTableContainsFold applies the ContainsFold predicate on the "lookup_table" field.
func LookupTableContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldLookupTable, v))
}

// LookupCaseSensitiveEQ applies the EQ predicate on the "lookup_case_sensitive" field.
func LookupCaseSensitiveEQ(v bool) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldLookupCaseSensitive, v))
}

// LookupCaseSensitiveNEQ applies the NEQ predicate on the "lookup_case_sensitive" field.
func LookupCaseSensitiveNEQ(v bool) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldLookupCaseSensitive, v))
}

// ConditionRulesEQ applies the EQ predicate on the "condition_rules" field.
func ConditionRulesEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldConditionRules, v))
}

// ConditionRulesNEQ applies the NEQ predicate on the "condition_rules" field.
func ConditionRulesNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldConditionRules, v))
}

// ConditionRulesIn applies the In predicate on the "condition_rules" field.
func ConditionRulesIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldConditionRules, vs...))
}

// ConditionRulesNotIn applies the NotIn predicate on the "condition_rules" field.
func ConditionRulesNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldConditionRules, vs...))
}

// ConditionRulesGT applies the GT predicate on the "condition_rules" field.
func ConditionRulesGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldConditionRules, v))
}

// ConditionRulesGTE applies the GTE predicate on the "condition_rules" field.
func ConditionRulesGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldConditionRules, v))
}

// ConditionRulesLT applies the LT predicate on the "condition_rules" field.
func ConditionRulesLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldConditionRules, v))
}

// ConditionRulesLTE applies the LTE predicate on the "condition_rules" field.
func ConditionRulesLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldConditionRules, v))
}

// ConditionRulesContains applies the Contains predicate on the "condition_rules" field.
func ConditionRulesContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldConditionRules, v))
}

// ConditionRulesHasPrefix applies the HasPrefix predicate on the "condition_rules" field.
func ConditionRulesHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldConditionRules, v))
}

// ConditionRulesHasSuffix applies the HasSuffix predicate on the "condition_rules" field.
func ConditionRulesHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldConditionRules, v))
}

// ConditionRulesIsNil applies the IsNil predicate on the "condition_rules" field.
func ConditionRulesIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldConditionRules))
}

// ConditionRulesNotNil applies the NotNil predicate on the "condition_rules" field.
func ConditionRulesNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldConditionRules))
}

// ConditionRulesEqualFold applies the EqualFold predicate on the "condition_rules" field.
func ConditionRulesEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldConditionRules, v))
}

// ConditionRulesContainsFold applies the ContainsFold predicate on the "condition_rules" field.
func ConditionRulesContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldConditionRules, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldPriority, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldSortOrder, v))
}

// DiscoveryPoolIDEQ applies the EQ predicate on the "discovery_pool_id" field.
func DiscoveryPoolIDEQ(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldDiscoveryPoolID, v))
}

// DiscoveryPoolIDNEQ applies the NEQ predicate on the "discovery_pool_id" field.
func DiscoveryPoolIDNEQ(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldDiscoveryPoolID, v))
}

// DiscoveryPoolIDIn applies the In predicate on the "discovery_pool_id" field.
func DiscoveryPoolIDIn(vs ...uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldDiscoveryPoolID, vs...))
}

// DiscoveryPoolIDNotIn applies the NotIn predicate on the "discovery_pool_id" field.
func DiscoveryPoolIDNotIn(vs ...uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldDiscoveryPoolID, vs...))
}

// DiscoveryPoolIDGT applies the GT predicate on the "discovery_pool_id" field.
func DiscoveryPoolIDGT(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldDiscoveryPoolID, v))
}

// DiscoveryPoolIDGTE applies the GTE predicate on the "discovery_pool_id" field.
func DiscoveryPoolIDGTE(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldDiscoveryPoolID, v))
}

// DiscoveryPoolIDLT applies the LT predicate on the "discovery_pool_id" field.
func DiscoveryPoolIDLT(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldDiscoveryPoolID, v))
}

// DiscoveryPoolIDLTE applies the LTE predicate on the "discovery_pool_id" field.
func DiscoveryPoolIDLTE(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldDiscoveryPoolID, v))
}

// DiscoveryPoolIDIsNil applies the IsNil predicate on the "discovery_pool_id" field.
func DiscoveryPoolIDIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldDiscoveryPoolID))
}

// DiscoveryPoolIDNotNil applies the NotNil predicate on the "discovery_pool_id" field.
func DiscoveryPoolIDNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldDiscoveryPoolID))
}

// InputTaskIDEQ applies the EQ predicate on the "input_task_id" field.
func InputTaskIDEQ(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldInputTaskID, v))
}

// InputTaskIDNEQ applies the NEQ predicate on the "input_task_id" field.
func InputTaskIDNEQ(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldInputTaskID, v))
}

// InputTaskIDIn applies the In predicate on the "input_task_id" field.
func InputTaskIDIn(vs ...uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldInputTaskID, vs...))
}

// InputTaskIDNotIn applies the NotIn predicate on the "input_task_id" field.
func InputTaskIDNotIn(vs ...uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldInputTaskID, vs...))
}

// InputTaskIDGT applies the GT predicate on the "input_task_id" field.
func InputTaskIDGT(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldInputTaskID, v))
}

// InputTaskIDGTE applies the GTE predicate on the "input_task_id" field.
func InputTaskIDGTE(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldInputTaskID, v))
}

// InputTaskIDLT applies the LT predicate on the "input_task_id" field.
func InputTaskIDLT(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldInputTaskID, v))
}

// InputTaskIDLTE applies the LTE predicate on the "input_task_id" field.
func InputTaskIDLTE(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldInputTaskID, v))
}

// InputTaskIDIsNil applies the IsNil predicate on the "input_task_id" field.
func InputTaskIDIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldInputTaskID))
}

// InputTaskIDNotNil applies the NotNil predicate on the "input_task_id" field.
func InputTaskIDNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldInputTaskID))
}

// OutputTaskIDEQ applies the EQ predicate on the "output_task_id" field.
func OutputTaskIDEQ(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldOutputTaskID, v))
}

// OutputTaskIDNEQ applies the NEQ predicate on the "output_task_id" field.
func OutputTaskIDNEQ(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldOutputTaskID, v))
}

// OutputTaskIDIn applies the In predicate on the "output_task_id" field.
func OutputTaskIDIn(vs ...uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldOutputTaskID, vs...))
}

// OutputTaskIDNotIn applies the NotIn predicate on the "output_task_id" field.
func OutputTaskIDNotIn(vs ...uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldOutputTaskID, vs...))
}

// OutputTaskIDGT applies the GT predicate on the "output_task_id" field.
func OutputTaskIDGT(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldOutputTaskID, v))
}

// OutputTaskIDGTE applies the GTE predicate on the "output_task_id" field.
func OutputTaskIDGTE(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldOutputTaskID, v))
}

// OutputTaskIDLT applies the LT predicate on the "output_task_id" field.
func OutputTaskIDLT(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldOutputTaskID, v))
}

// OutputTaskIDLTE applies the LTE predicate on the "output_task_id" field.
func OutputTaskIDLTE(v uint64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldOutputTaskID, v))
}

// OutputTaskIDIsNil applies the IsNil predicate on the "output_task_id" field.
func OutputTaskIDIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldOutputTaskID))
}

// OutputTaskIDNotNil applies the NotNil predicate on the "output_task_id" field.
func OutputTaskIDNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldOutputTaskID))
}

// UsageCountEQ applies the EQ predicate on the "usage_count" field.
func UsageCountEQ(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldUsageCount, v))
}

// UsageCountNEQ applies the NEQ predicate on the "usage_count" field.
func UsageCountNEQ(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldUsageCount, v))
}

// UsageCountIn applies the In predicate on the "usage_count" field.
func UsageCountIn(vs ...int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldUsageCount, vs...))
}

// UsageCountNotIn applies the NotIn predicate on the "usage_count" field.
func UsageCountNotIn(vs ...int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldUsageCount, vs...))
}

// UsageCountGT applies the GT predicate on the "usage_count" field.
func UsageCountGT(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldUsageCount, v))
}

// UsageCountGTE applies the GTE predicate on the "usage_count" field.
func UsageCountGTE(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldUsageCount, v))
}

// UsageCountLT applies the LT predicate on the "usage_count" field.
func UsageCountLT(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldUsageCount, v))
}

// UsageCountLTE applies the LTE predicate on the "usage_count" field.
func UsageCountLTE(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldUsageCount, v))
}

// SuccessCountEQ applies the EQ predicate on the "success_count" field.
func SuccessCountEQ(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldSuccessCount, v))
}

// SuccessCountNEQ applies the NEQ predicate on the "success_count" field.
func SuccessCountNEQ(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldSuccessCount, v))
}

// SuccessCountIn applies the In predicate on the "success_count" field.
func SuccessCountIn(vs ...int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldSuccessCount, vs...))
}

// SuccessCountNotIn applies the NotIn predicate on the "success_count" field.
func SuccessCountNotIn(vs ...int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldSuccessCount, vs...))
}

// SuccessCountGT applies the GT predicate on the "success_count" field.
func SuccessCountGT(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldSuccessCount, v))
}

// SuccessCountGTE applies the GTE predicate on the "success_count" field.
func SuccessCountGTE(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldSuccessCount, v))
}

// SuccessCountLT applies the LT predicate on the "success_count" field.
func SuccessCountLT(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldSuccessCount, v))
}

// SuccessCountLTE applies the LTE predicate on the "success_count" field.
func SuccessCountLTE(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldSuccessCount, v))
}

// FailedCountEQ applies the EQ predicate on the "failed_count" field.
func FailedCountEQ(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldFailedCount, v))
}

// FailedCountNEQ applies the NEQ predicate on the "failed_count" field.
func FailedCountNEQ(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldFailedCount, v))
}

// FailedCountIn applies the In predicate on the "failed_count" field.
func FailedCountIn(vs ...int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldFailedCount, vs...))
}

// FailedCountNotIn applies the NotIn predicate on the "failed_count" field.
func FailedCountNotIn(vs ...int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldFailedCount, vs...))
}

// FailedCountGT applies the GT predicate on the "failed_count" field.
func FailedCountGT(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldFailedCount, v))
}

// FailedCountGTE applies the GTE predicate on the "failed_count" field.
func FailedCountGTE(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldFailedCount, v))
}

// FailedCountLT applies the LT predicate on the "failed_count" field.
func FailedCountLT(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldFailedCount, v))
}

// FailedCountLTE applies the LTE predicate on the "failed_count" field.
func FailedCountLTE(v int64) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldFailedCount, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldLastUsedAt))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldLastError, v))
}

// LastErrorAtEQ applies the EQ predicate on the "last_error_at" field.
func LastErrorAtEQ(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldLastErrorAt, v))
}

// LastErrorAtNEQ applies the NEQ predicate on the "last_error_at" field.
func LastErrorAtNEQ(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldLastErrorAt, v))
}

// LastErrorAtIn applies the In predicate on the "last_error_at" field.
func LastErrorAtIn(vs ...time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldLastErrorAt, vs...))
}

// LastErrorAtNotIn applies the NotIn predicate on the "last_error_at" field.
func LastErrorAtNotIn(vs ...time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldLastErrorAt, vs...))
}

// LastErrorAtGT applies the GT predicate on the "last_error_at" field.
func LastErrorAtGT(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldLastErrorAt, v))
}

// LastErrorAtGTE applies the GTE predicate on the "last_error_at" field.
func LastErrorAtGTE(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldLastErrorAt, v))
}

// LastErrorAtLT applies the LT predicate on the "last_error_at" field.
func LastErrorAtLT(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldLastErrorAt, v))
}

// LastErrorAtLTE applies the LTE predicate on the "last_error_at" field.
func LastErrorAtLTE(v time.Time) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldLastErrorAt, v))
}

// LastErrorAtIsNil applies the IsNil predicate on the "last_error_at" field.
func LastErrorAtIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldLastErrorAt))
}

// LastErrorAtNotNil applies the NotNil predicate on the "last_error_at" field.
func LastErrorAtNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldLastErrorAt))
}

// MetadataEQ applies the EQ predicate on the "metadata" field.
func MetadataEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEQ(FieldMetadata, v))
}

// MetadataNEQ applies the NEQ predicate on the "metadata" field.
func MetadataNEQ(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNEQ(FieldMetadata, v))
}

// MetadataIn applies the In predicate on the "metadata" field.
func MetadataIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIn(FieldMetadata, vs...))
}

// MetadataNotIn applies the NotIn predicate on the "metadata" field.
func MetadataNotIn(vs ...string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotIn(FieldMetadata, vs...))
}

// MetadataGT applies the GT predicate on the "metadata" field.
func MetadataGT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGT(FieldMetadata, v))
}

// MetadataGTE applies the GTE predicate on the "metadata" field.
func MetadataGTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldGTE(FieldMetadata, v))
}

// MetadataLT applies the LT predicate on the "metadata" field.
func MetadataLT(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLT(FieldMetadata, v))
}

// MetadataLTE applies the LTE predicate on the "metadata" field.
func MetadataLTE(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldLTE(FieldMetadata, v))
}

// MetadataContains applies the Contains predicate on the "metadata" field.
func MetadataContains(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContains(FieldMetadata, v))
}

// MetadataHasPrefix applies the HasPrefix predicate on the "metadata" field.
func MetadataHasPrefix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasPrefix(FieldMetadata, v))
}

// MetadataHasSuffix applies the HasSuffix predicate on the "metadata" field.
func MetadataHasSuffix(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldHasSuffix(FieldMetadata, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldNotNull(FieldMetadata))
}

// MetadataEqualFold applies the EqualFold predicate on the "metadata" field.
func MetadataEqualFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldEqualFold(FieldMetadata, v))
}

// MetadataContainsFold applies the ContainsFold predicate on the "metadata" field.
func MetadataContainsFold(v string) predicate.FieldMapping {
	return predicate.FieldMapping(sql.FieldContainsFold(FieldMetadata, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FieldMapping) predicate.FieldMapping {
	return predicate.FieldMapping(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FieldMapping) predicate.FieldMapping {
	return predicate.FieldMapping(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FieldMapping) predicate.FieldMapping {
	return predicate.FieldMapping(sql.NotPredicates(p))
}
