// Code generated by ent, DO NOT EDIT.

package crontask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/coder-lulu/newbee-io-rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v uint8) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldStatus, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldTenantID, v))
}

// TaskName applies equality check predicate on the "task_name" field. It's identical to TaskNameEQ.
func TaskName(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldTaskName, v))
}

// CronExpression applies equality check predicate on the "cron_expression" field. It's identical to CronExpressionEQ.
func CronExpression(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldCronExpression, v))
}

// InputSource applies equality check predicate on the "input_source" field. It's identical to InputSourceEQ.
func InputSource(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldInputSource, v))
}

// SourceConfig applies equality check predicate on the "source_config" field. It's identical to SourceConfigEQ.
func SourceConfig(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldSourceConfig, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldEnabled, v))
}

// NextRunTime applies equality check predicate on the "next_run_time" field. It's identical to NextRunTimeEQ.
func NextRunTime(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldNextRunTime, v))
}

// LastRunTime applies equality check predicate on the "last_run_time" field. It's identical to LastRunTimeEQ.
func LastRunTime(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldLastRunTime, v))
}

// ExecutionCount applies equality check predicate on the "execution_count" field. It's identical to ExecutionCountEQ.
func ExecutionCount(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldExecutionCount, v))
}

// SuccessCount applies equality check predicate on the "success_count" field. It's identical to SuccessCountEQ.
func SuccessCount(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldSuccessCount, v))
}

// FailureCount applies equality check predicate on the "failure_count" field. It's identical to FailureCountEQ.
func FailureCount(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldFailureCount, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldLTE(FieldUpdatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v uint8) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v uint8) predicate.CronTask {
	return predicate.CronTask(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...uint8) predicate.CronTask {
	return predicate.CronTask(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...uint8) predicate.CronTask {
	return predicate.CronTask(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v uint8) predicate.CronTask {
	return predicate.CronTask(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v uint8) predicate.CronTask {
	return predicate.CronTask(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v uint8) predicate.CronTask {
	return predicate.CronTask(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v uint8) predicate.CronTask {
	return predicate.CronTask(sql.FieldLTE(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.CronTask {
	return predicate.CronTask(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.CronTask {
	return predicate.CronTask(sql.FieldNotNull(FieldStatus))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint64) predicate.CronTask {
	return predicate.CronTask(sql.FieldLTE(FieldTenantID, v))
}

// TaskNameEQ applies the EQ predicate on the "task_name" field.
func TaskNameEQ(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldTaskName, v))
}

// TaskNameNEQ applies the NEQ predicate on the "task_name" field.
func TaskNameNEQ(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldNEQ(FieldTaskName, v))
}

// TaskNameIn applies the In predicate on the "task_name" field.
func TaskNameIn(vs ...string) predicate.CronTask {
	return predicate.CronTask(sql.FieldIn(FieldTaskName, vs...))
}

// TaskNameNotIn applies the NotIn predicate on the "task_name" field.
func TaskNameNotIn(vs ...string) predicate.CronTask {
	return predicate.CronTask(sql.FieldNotIn(FieldTaskName, vs...))
}

// TaskNameGT applies the GT predicate on the "task_name" field.
func TaskNameGT(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldGT(FieldTaskName, v))
}

// TaskNameGTE applies the GTE predicate on the "task_name" field.
func TaskNameGTE(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldGTE(FieldTaskName, v))
}

// TaskNameLT applies the LT predicate on the "task_name" field.
func TaskNameLT(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldLT(FieldTaskName, v))
}

// TaskNameLTE applies the LTE predicate on the "task_name" field.
func TaskNameLTE(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldLTE(FieldTaskName, v))
}

// TaskNameContains applies the Contains predicate on the "task_name" field.
func TaskNameContains(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldContains(FieldTaskName, v))
}

// TaskNameHasPrefix applies the HasPrefix predicate on the "task_name" field.
func TaskNameHasPrefix(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldHasPrefix(FieldTaskName, v))
}

// TaskNameHasSuffix applies the HasSuffix predicate on the "task_name" field.
func TaskNameHasSuffix(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldHasSuffix(FieldTaskName, v))
}

// TaskNameEqualFold applies the EqualFold predicate on the "task_name" field.
func TaskNameEqualFold(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldEqualFold(FieldTaskName, v))
}

// TaskNameContainsFold applies the ContainsFold predicate on the "task_name" field.
func TaskNameContainsFold(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldContainsFold(FieldTaskName, v))
}

// CronExpressionEQ applies the EQ predicate on the "cron_expression" field.
func CronExpressionEQ(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldCronExpression, v))
}

// CronExpressionNEQ applies the NEQ predicate on the "cron_expression" field.
func CronExpressionNEQ(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldNEQ(FieldCronExpression, v))
}

// CronExpressionIn applies the In predicate on the "cron_expression" field.
func CronExpressionIn(vs ...string) predicate.CronTask {
	return predicate.CronTask(sql.FieldIn(FieldCronExpression, vs...))
}

// CronExpressionNotIn applies the NotIn predicate on the "cron_expression" field.
func CronExpressionNotIn(vs ...string) predicate.CronTask {
	return predicate.CronTask(sql.FieldNotIn(FieldCronExpression, vs...))
}

// CronExpressionGT applies the GT predicate on the "cron_expression" field.
func CronExpressionGT(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldGT(FieldCronExpression, v))
}

// CronExpressionGTE applies the GTE predicate on the "cron_expression" field.
func CronExpressionGTE(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldGTE(FieldCronExpression, v))
}

// CronExpressionLT applies the LT predicate on the "cron_expression" field.
func CronExpressionLT(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldLT(FieldCronExpression, v))
}

// CronExpressionLTE applies the LTE predicate on the "cron_expression" field.
func CronExpressionLTE(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldLTE(FieldCronExpression, v))
}

// CronExpressionContains applies the Contains predicate on the "cron_expression" field.
func CronExpressionContains(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldContains(FieldCronExpression, v))
}

// CronExpressionHasPrefix applies the HasPrefix predicate on the "cron_expression" field.
func CronExpressionHasPrefix(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldHasPrefix(FieldCronExpression, v))
}

// CronExpressionHasSuffix applies the HasSuffix predicate on the "cron_expression" field.
func CronExpressionHasSuffix(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldHasSuffix(FieldCronExpression, v))
}

// CronExpressionEqualFold applies the EqualFold predicate on the "cron_expression" field.
func CronExpressionEqualFold(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldEqualFold(FieldCronExpression, v))
}

// CronExpressionContainsFold applies the ContainsFold predicate on the "cron_expression" field.
func CronExpressionContainsFold(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldContainsFold(FieldCronExpression, v))
}

// InputSourceEQ applies the EQ predicate on the "input_source" field.
func InputSourceEQ(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldInputSource, v))
}

// InputSourceNEQ applies the NEQ predicate on the "input_source" field.
func InputSourceNEQ(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldNEQ(FieldInputSource, v))
}

// InputSourceIn applies the In predicate on the "input_source" field.
func InputSourceIn(vs ...string) predicate.CronTask {
	return predicate.CronTask(sql.FieldIn(FieldInputSource, vs...))
}

// InputSourceNotIn applies the NotIn predicate on the "input_source" field.
func InputSourceNotIn(vs ...string) predicate.CronTask {
	return predicate.CronTask(sql.FieldNotIn(FieldInputSource, vs...))
}

// InputSourceGT applies the GT predicate on the "input_source" field.
func InputSourceGT(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldGT(FieldInputSource, v))
}

// InputSourceGTE applies the GTE predicate on the "input_source" field.
func InputSourceGTE(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldGTE(FieldInputSource, v))
}

// InputSourceLT applies the LT predicate on the "input_source" field.
func InputSourceLT(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldLT(FieldInputSource, v))
}

// InputSourceLTE applies the LTE predicate on the "input_source" field.
func InputSourceLTE(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldLTE(FieldInputSource, v))
}

// InputSourceContains applies the Contains predicate on the "input_source" field.
func InputSourceContains(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldContains(FieldInputSource, v))
}

// InputSourceHasPrefix applies the HasPrefix predicate on the "input_source" field.
func InputSourceHasPrefix(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldHasPrefix(FieldInputSource, v))
}

// InputSourceHasSuffix applies the HasSuffix predicate on the "input_source" field.
func InputSourceHasSuffix(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldHasSuffix(FieldInputSource, v))
}

// InputSourceEqualFold applies the EqualFold predicate on the "input_source" field.
func InputSourceEqualFold(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldEqualFold(FieldInputSource, v))
}

// InputSourceContainsFold applies the ContainsFold predicate on the "input_source" field.
func InputSourceContainsFold(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldContainsFold(FieldInputSource, v))
}

// SourceConfigEQ applies the EQ predicate on the "source_config" field.
func SourceConfigEQ(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldSourceConfig, v))
}

// SourceConfigNEQ applies the NEQ predicate on the "source_config" field.
func SourceConfigNEQ(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldNEQ(FieldSourceConfig, v))
}

// SourceConfigIn applies the In predicate on the "source_config" field.
func SourceConfigIn(vs ...string) predicate.CronTask {
	return predicate.CronTask(sql.FieldIn(FieldSourceConfig, vs...))
}

// SourceConfigNotIn applies the NotIn predicate on the "source_config" field.
func SourceConfigNotIn(vs ...string) predicate.CronTask {
	return predicate.CronTask(sql.FieldNotIn(FieldSourceConfig, vs...))
}

// SourceConfigGT applies the GT predicate on the "source_config" field.
func SourceConfigGT(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldGT(FieldSourceConfig, v))
}

// SourceConfigGTE applies the GTE predicate on the "source_config" field.
func SourceConfigGTE(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldGTE(FieldSourceConfig, v))
}

// SourceConfigLT applies the LT predicate on the "source_config" field.
func SourceConfigLT(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldLT(FieldSourceConfig, v))
}

// SourceConfigLTE applies the LTE predicate on the "source_config" field.
func SourceConfigLTE(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldLTE(FieldSourceConfig, v))
}

// SourceConfigContains applies the Contains predicate on the "source_config" field.
func SourceConfigContains(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldContains(FieldSourceConfig, v))
}

// SourceConfigHasPrefix applies the HasPrefix predicate on the "source_config" field.
func SourceConfigHasPrefix(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldHasPrefix(FieldSourceConfig, v))
}

// SourceConfigHasSuffix applies the HasSuffix predicate on the "source_config" field.
func SourceConfigHasSuffix(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldHasSuffix(FieldSourceConfig, v))
}

// SourceConfigIsNil applies the IsNil predicate on the "source_config" field.
func SourceConfigIsNil() predicate.CronTask {
	return predicate.CronTask(sql.FieldIsNull(FieldSourceConfig))
}

// SourceConfigNotNil applies the NotNil predicate on the "source_config" field.
func SourceConfigNotNil() predicate.CronTask {
	return predicate.CronTask(sql.FieldNotNull(FieldSourceConfig))
}

// SourceConfigEqualFold applies the EqualFold predicate on the "source_config" field.
func SourceConfigEqualFold(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldEqualFold(FieldSourceConfig, v))
}

// SourceConfigContainsFold applies the ContainsFold predicate on the "source_config" field.
func SourceConfigContainsFold(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldContainsFold(FieldSourceConfig, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.CronTask {
	return predicate.CronTask(sql.FieldNEQ(FieldEnabled, v))
}

// NextRunTimeEQ applies the EQ predicate on the "next_run_time" field.
func NextRunTimeEQ(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldNextRunTime, v))
}

// NextRunTimeNEQ applies the NEQ predicate on the "next_run_time" field.
func NextRunTimeNEQ(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldNEQ(FieldNextRunTime, v))
}

// NextRunTimeIn applies the In predicate on the "next_run_time" field.
func NextRunTimeIn(vs ...time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldIn(FieldNextRunTime, vs...))
}

// NextRunTimeNotIn applies the NotIn predicate on the "next_run_time" field.
func NextRunTimeNotIn(vs ...time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldNotIn(FieldNextRunTime, vs...))
}

// NextRunTimeGT applies the GT predicate on the "next_run_time" field.
func NextRunTimeGT(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldGT(FieldNextRunTime, v))
}

// NextRunTimeGTE applies the GTE predicate on the "next_run_time" field.
func NextRunTimeGTE(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldGTE(FieldNextRunTime, v))
}

// NextRunTimeLT applies the LT predicate on the "next_run_time" field.
func NextRunTimeLT(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldLT(FieldNextRunTime, v))
}

// NextRunTimeLTE applies the LTE predicate on the "next_run_time" field.
func NextRunTimeLTE(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldLTE(FieldNextRunTime, v))
}

// NextRunTimeIsNil applies the IsNil predicate on the "next_run_time" field.
func NextRunTimeIsNil() predicate.CronTask {
	return predicate.CronTask(sql.FieldIsNull(FieldNextRunTime))
}

// NextRunTimeNotNil applies the NotNil predicate on the "next_run_time" field.
func NextRunTimeNotNil() predicate.CronTask {
	return predicate.CronTask(sql.FieldNotNull(FieldNextRunTime))
}

// LastRunTimeEQ applies the EQ predicate on the "last_run_time" field.
func LastRunTimeEQ(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldLastRunTime, v))
}

// LastRunTimeNEQ applies the NEQ predicate on the "last_run_time" field.
func LastRunTimeNEQ(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldNEQ(FieldLastRunTime, v))
}

// LastRunTimeIn applies the In predicate on the "last_run_time" field.
func LastRunTimeIn(vs ...time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldIn(FieldLastRunTime, vs...))
}

// LastRunTimeNotIn applies the NotIn predicate on the "last_run_time" field.
func LastRunTimeNotIn(vs ...time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldNotIn(FieldLastRunTime, vs...))
}

// LastRunTimeGT applies the GT predicate on the "last_run_time" field.
func LastRunTimeGT(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldGT(FieldLastRunTime, v))
}

// LastRunTimeGTE applies the GTE predicate on the "last_run_time" field.
func LastRunTimeGTE(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldGTE(FieldLastRunTime, v))
}

// LastRunTimeLT applies the LT predicate on the "last_run_time" field.
func LastRunTimeLT(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldLT(FieldLastRunTime, v))
}

// LastRunTimeLTE applies the LTE predicate on the "last_run_time" field.
func LastRunTimeLTE(v time.Time) predicate.CronTask {
	return predicate.CronTask(sql.FieldLTE(FieldLastRunTime, v))
}

// LastRunTimeIsNil applies the IsNil predicate on the "last_run_time" field.
func LastRunTimeIsNil() predicate.CronTask {
	return predicate.CronTask(sql.FieldIsNull(FieldLastRunTime))
}

// LastRunTimeNotNil applies the NotNil predicate on the "last_run_time" field.
func LastRunTimeNotNil() predicate.CronTask {
	return predicate.CronTask(sql.FieldNotNull(FieldLastRunTime))
}

// ExecutionCountEQ applies the EQ predicate on the "execution_count" field.
func ExecutionCountEQ(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldExecutionCount, v))
}

// ExecutionCountNEQ applies the NEQ predicate on the "execution_count" field.
func ExecutionCountNEQ(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldNEQ(FieldExecutionCount, v))
}

// ExecutionCountIn applies the In predicate on the "execution_count" field.
func ExecutionCountIn(vs ...int) predicate.CronTask {
	return predicate.CronTask(sql.FieldIn(FieldExecutionCount, vs...))
}

// ExecutionCountNotIn applies the NotIn predicate on the "execution_count" field.
func ExecutionCountNotIn(vs ...int) predicate.CronTask {
	return predicate.CronTask(sql.FieldNotIn(FieldExecutionCount, vs...))
}

// ExecutionCountGT applies the GT predicate on the "execution_count" field.
func ExecutionCountGT(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldGT(FieldExecutionCount, v))
}

// ExecutionCountGTE applies the GTE predicate on the "execution_count" field.
func ExecutionCountGTE(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldGTE(FieldExecutionCount, v))
}

// ExecutionCountLT applies the LT predicate on the "execution_count" field.
func ExecutionCountLT(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldLT(FieldExecutionCount, v))
}

// ExecutionCountLTE applies the LTE predicate on the "execution_count" field.
func ExecutionCountLTE(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldLTE(FieldExecutionCount, v))
}

// SuccessCountEQ applies the EQ predicate on the "success_count" field.
func SuccessCountEQ(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldSuccessCount, v))
}

// SuccessCountNEQ applies the NEQ predicate on the "success_count" field.
func SuccessCountNEQ(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldNEQ(FieldSuccessCount, v))
}

// SuccessCountIn applies the In predicate on the "success_count" field.
func SuccessCountIn(vs ...int) predicate.CronTask {
	return predicate.CronTask(sql.FieldIn(FieldSuccessCount, vs...))
}

// SuccessCountNotIn applies the NotIn predicate on the "success_count" field.
func SuccessCountNotIn(vs ...int) predicate.CronTask {
	return predicate.CronTask(sql.FieldNotIn(FieldSuccessCount, vs...))
}

// SuccessCountGT applies the GT predicate on the "success_count" field.
func SuccessCountGT(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldGT(FieldSuccessCount, v))
}

// SuccessCountGTE applies the GTE predicate on the "success_count" field.
func SuccessCountGTE(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldGTE(FieldSuccessCount, v))
}

// SuccessCountLT applies the LT predicate on the "success_count" field.
func SuccessCountLT(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldLT(FieldSuccessCount, v))
}

// SuccessCountLTE applies the LTE predicate on the "success_count" field.
func SuccessCountLTE(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldLTE(FieldSuccessCount, v))
}

// FailureCountEQ applies the EQ predicate on the "failure_count" field.
func FailureCountEQ(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldFailureCount, v))
}

// FailureCountNEQ applies the NEQ predicate on the "failure_count" field.
func FailureCountNEQ(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldNEQ(FieldFailureCount, v))
}

// FailureCountIn applies the In predicate on the "failure_count" field.
func FailureCountIn(vs ...int) predicate.CronTask {
	return predicate.CronTask(sql.FieldIn(FieldFailureCount, vs...))
}

// FailureCountNotIn applies the NotIn predicate on the "failure_count" field.
func FailureCountNotIn(vs ...int) predicate.CronTask {
	return predicate.CronTask(sql.FieldNotIn(FieldFailureCount, vs...))
}

// FailureCountGT applies the GT predicate on the "failure_count" field.
func FailureCountGT(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldGT(FieldFailureCount, v))
}

// FailureCountGTE applies the GTE predicate on the "failure_count" field.
func FailureCountGTE(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldGTE(FieldFailureCount, v))
}

// FailureCountLT applies the LT predicate on the "failure_count" field.
func FailureCountLT(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldLT(FieldFailureCount, v))
}

// FailureCountLTE applies the LTE predicate on the "failure_count" field.
func FailureCountLTE(v int) predicate.CronTask {
	return predicate.CronTask(sql.FieldLTE(FieldFailureCount, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.CronTask {
	return predicate.CronTask(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.CronTask {
	return predicate.CronTask(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.CronTask {
	return predicate.CronTask(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.CronTask {
	return predicate.CronTask(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.CronTask {
	return predicate.CronTask(sql.FieldContainsFold(FieldDescription, v))
}

// HasExecutions applies the HasEdge predicate on the "executions" edge.
func HasExecutions() predicate.CronTask {
	return predicate.CronTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ExecutionsTable, ExecutionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExecutionsWith applies the HasEdge predicate on the "executions" edge with a given conditions (other predicates).
func HasExecutionsWith(preds ...predicate.InputTask) predicate.CronTask {
	return predicate.CronTask(func(s *sql.Selector) {
		step := newExecutionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CronTask) predicate.CronTask {
	return predicate.CronTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CronTask) predicate.CronTask {
	return predicate.CronTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CronTask) predicate.CronTask {
	return predicate.CronTask(sql.NotPredicates(p))
}
