// Code generated by ent, DO NOT EDIT.

package tasklog

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tasklog type in the database.
	Label = "task_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldTaskType holds the string denoting the task_type field in the database.
	FieldTaskType = "task_type"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldLogLevel holds the string denoting the log_level field in the database.
	FieldLogLevel = "log_level"
	// FieldLogMessage holds the string denoting the log_message field in the database.
	FieldLogMessage = "log_message"
	// FieldLogDetail holds the string denoting the log_detail field in the database.
	FieldLogDetail = "log_detail"
	// FieldLoggedAt holds the string denoting the logged_at field in the database.
	FieldLoggedAt = "logged_at"
	// Table holds the table name of the tasklog in the database.
	Table = "io_task_logs"
)

// Columns holds all SQL columns for tasklog fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTenantID,
	FieldTaskType,
	FieldTaskID,
	FieldLogLevel,
	FieldLogMessage,
	FieldLogDetail,
	FieldLoggedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint64
	// TaskTypeValidator is a validator for the "task_type" field. It is called by the builders before save.
	TaskTypeValidator func(string) error
	// DefaultLogLevel holds the default value on creation for the "log_level" field.
	DefaultLogLevel string
	// LogLevelValidator is a validator for the "log_level" field. It is called by the builders before save.
	LogLevelValidator func(string) error
)

// OrderOption defines the ordering options for the TaskLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByTaskType orders the results by the task_type field.
func ByTaskType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskType, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByLogLevel orders the results by the log_level field.
func ByLogLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogLevel, opts...).ToFunc()
}

// ByLogMessage orders the results by the log_message field.
func ByLogMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogMessage, opts...).ToFunc()
}

// ByLogDetail orders the results by the log_detail field.
func ByLogDetail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogDetail, opts...).ToFunc()
}

// ByLoggedAt orders the results by the logged_at field.
func ByLoggedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoggedAt, opts...).ToFunc()
}
